Updated openstack/openstack Project: openstack/neutron  9daca5d385f17492b77bb38fdf9de01c3f93fd16
Un-break tox for unit tests

Running 'tox -e py27 $some_unit_test' is always failing now
with tox 1.6.0, with this being printed at the beginning:

ERROR: InvocationError: could not find executable 'dsvm-functional:'

Seems commit 540e4d791ff2573aae38810f4c39f2d6f46d8898
(Automate host configuration for functional testing)
added some code to tox.ini that requires version 1.8 or later,
so make that the minimum.

Change-Id: I56313d0a22dbc4007142b8bb4890d1ac8bebff94