Update git submodules
* Update kayobe from branch 'master'
  to 22fc03f15ef2930fe53442b53ac0003216e6ca8b
  - CI: Fix CentOS Stream 10 host configure job
    
    The kayobe-overcloud-host-configure-centos10s job was failing with:
    
        Traceback (most recent call last):
          File "/tmp/ansible_pip_payload_zectmelk/ansible_pip_payload.zip/ansible/modules/pip.py", line 310, in <module>
            from packaging.requirements import Requirement as parse_requirement
        ModuleNotFoundError: No module named 'packaging'
    
    This is resolved by ensuring setuptools is installed, which is the case
    on other operating system images used in CI.
    
    Change-Id: I3f91bc05e46497e37b8cdcea1d283da5a7286a83
    Signed-off-by: Pierre Riteau <pierre@stackhpc.com>