Update git submodules
* Update puppet-ec2api from branch 'master'
  to c1ee6f950709f3b2f527d0ec748949f24497fa8e
  - setuptools: Disable auto discovery
    
    The latest release of setuptools 61.0 made a breaking change[1] and
    because of this change 'pip install' fails with the following error.
    
    ~~~
    error: Multiple top-level packages discovered in a flat-layout:
    ['lib', 'spec', 'manifests', 'releasenotes'].
    ~~~
    
    Users that don't set 'packages', 'py_modules', or configuration'
    are still likely to observe the auto-discovery behavior, which may
    halt the build if the project contains multiple directories and/or
    multiple Python files directly under the project root.
    
    To disable auto discovery, one can do below in setup.py
    
    ~~~
    setuptools.setup(..,packages=[],..)
    ~~~
    
    or
    
    ~~~
    setuptools.setup(..,py_modules=[],..)
    ~~~
    
    [1] https://github.com/pypa/setuptools/issues/3197
    
    Note setup.py is not used to install puppet modules. However it is used
    to generate a release note, thus should be fixed.
    
    Signed-off-by: Jiri Podivin <jpodivin@redhat.com>
    Change-Id: I1849d008833a689d8fb17efc815dadb3ec8e2d22