Updated openstack/openstack Project: openstack-infra/system-config  73ef799d751167929efa607fbb2b41636ff0362e
Don't use newer sphinx

Newer sphinx >=1.6.0 breaks theme templating. Avoid these problems
entirely by installing <1.6.0.

Example of resulting error:

  Exception occurred:
    File "/home/jenkins/workspace/gate-system-config-docs-ubuntu-xenial/.tox/venv/local/lib/python2.7/site-packages/sphinx/themes/basic/../basic/layout.html", line 108, in template
      {%- for css in css_files %}
  TypeError: 'NoneType' object is not iterable

Change-Id: Ibd7e932360c86be380184ccf4f415dbb8d70b757