Updated openstack/openstack Project: openstack/heat  aacc27138e31a3fe064acd2fcd776f70eb677fde
Raise NotImplementedError instead of NotImplemented

NotImplementedError is the name of the exception
(https://docs.python.org/2/library/exceptions.html).
NotImplemented is the name of a constant
(https://docs.python.org/2/library/constants.html).
>>> raise NotImplemented()
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
>>> raise NotImplementedError()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    raise NotImplementedError()
NotImplementedError
This patch fix it.

Change-Id: I939eaa4b4b7c574f7a6447725e3a6ad5b128f1b7
Closes-Bug: #1339855