Update git submodules
* Update tripleo-common from branch 'master'
  - Switch tripleo-cross-tripleoclient to python 3.7
    
    tripleoclient isn't gating on python 3.8 but on python 3.7. In fact,
    python 3.8 is still non voting and it seems to be broken for openstack
    client as of today:
    
      AttributeError: 'EntryPoint' object has no attribute 'module'
    
    So let's stick to how tripleoclient is tested, which is python 3.7.
    
    Change-Id: I79bbf0eb420cc445cb687f2c5929f634c3c233fc