Updated openstack/openstack Project: openstack/python-openstackclient  d843255bd8c43bb3f17cd06b969e31e2fd58b2c1
Change test order to avoid incompatibliity

If py26 or py27 tests are run first, there is a incompatibility in
the .testrepository that breaks several tests.  To get around this,
you need to run the py33 tests first.  This change was made over in
the cliff project.

Before:
    (.venv)terry@brat:~/cli$ rm -rf .testrepository/
    (.venv)terry@brat:~/cli$ tox
      ...
      py26: commands succeeded
      py27: commands succeeded
    ERROR:   py33: commands failed
    ERROR:   py34: commands failed
      pep8: commands succeeded
After:
    (.venv)terry@brat:~/cli$ rm -rf .testrepository/
    (.venv)terry@brat:~/cli$ tox
      ...
      py33: commands succeeded
      py34: commands succeeded
      py26: commands succeeded
      py27: commands succeeded
      pep8: commands succeeded
      congratulations :)
    (.venv)terry@brat:~/cli$

Change-Id: Ie1717efd6827eae36683f2e7fe7ff8ec58ff4aa8