Update git submodules
* Update puppet-tripleo from branch 'master'
  to e087576ffc06ef04a54fc059379e5b25f27ceec2
  - Merge "Trim line breaks from pacemaker bundle function"
  - Trim line breaks from pacemaker bundle function
    
    On CentOS9, the cibadmin query is returning '\n' if the bundle is not
    defined which results in:
    
    Error: Evaluation Error: Error while evaluating a Function Call, invalid
    value for Integer(): "\n" (line: 1, column: 1) on node
    standalone-0.localdomain
    
    This change strips whitespace from the check to ensure it has a value
    before we attempt to convert to an integer.
    
    Change-Id: I369644d491357a8cdeae3eff51f4f595b1033b66