Updated openstack/openstack Project: openstack/requirements  5707503c9fa97480d3daa2011ff98e4c9ec74fe7
Require requests >= 2.14

2.14.0 had a this release feature:

"When users provide invalid paths to certificate bundle files or directories Requests now raises IOError,
rather than failing at the time of the HTTPS request with a fairly inscrutable certificate validation error."

It turns out we're relying on this behavior in several places, like for
example python-glanceclient:

When users provide invalid paths to certificate bundle files or directories Requests now raises IOError, rather than failing at the time of the HTTPS request with a fairly inscrutable certificate validation error.

FAIL: glanceclient.tests.unit.test_ssl.TestHTTPSVerifyCert.test_v2_requests_bad_ca
tags: worker-3
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "glanceclient/tests/unit/test_ssl.py", line 253, in test_v2_requests_bad_ca
    gc.images.get('image123')
  File "glanceclient/v2/images.py", line 197, in get
    return self._get(image_id)
  File "glanceclient/common/utils.py", line 545, in inner
    return RequestIdProxy(wrapped(*args, **kwargs))
  File "glanceclient/v2/images.py", line 190, in _get
    resp, body = self.http_client.get(url, headers=header)
  File "glanceclient/common/http.py", line 289, in get
    return self._request('GET', url, **kwargs)
  File "glanceclient/common/http.py", line 260, in _request
    raise exc.CommunicationError(message=message)
glanceclient.exc.CommunicationError: Error finding address for https://0.0.0.0:37335/v2/images/image123: [Errno 2] No such file or directory

requests 2.14.0 bundles urllib3 1.21.1, so raise the lower version of
that one as well to ensure minimum version consistency

Change-Id: If3711576efbef54d0e917caffaf458eefca3a5b2