Update git submodules
* Update cinder from branch 'master'
  to 832a8c4c99c9bc09034c0bf4a98670f70d2297db
  - Merge "Set worker=1 as default in service.serve()"
  - Set worker=1 as default in service.serve()
    
    When serve() is called without workers, it defaults to None and
    explicitly passes worker=None to oslo.service.launch(), overriding
    default worker=1, in evenelet mode None is handled at launch level.
    In threading mode, oslo_service(cotyledon) backend requires explicit
    int for worker parameter, passing None causes ValueError during service
    startup.
    
    ValueError: 'workers' must be an int >= 1, not: None (NoneType)
    
    By defaulting to worker=1 in cinder serve call, we align with
    oslo.service's default.
    
    Change-Id: I81ea6ab64fa3673b424bb1db65af43778e1a54fb
    Signed-off-by: Amit Uniyal <auniyal@redhat.com>