Update git submodules
* Update kolla-ansible from branch 'master'
  to c78cedfa75d7efb0c5d1b1c0cb21ecf217c0f36f
  - Merge "Fix Nova scp failures on Debian Bookworm"
  - Fix Nova scp failures on Debian Bookworm
    
    The addition of an instance resize operation [1] to CI testing is
    triggering a failure in kolla-ansible-debian-ovn jobs, which are using a
    nodeset with multiple nodes:
    
        oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
        Command: scp -r /var/lib/nova/instances/8ca2c7e8-acae-404c-af7d-6cac38e354b8_resize/disk 192.0.2.2:/var/lib/nova/instances/8ca2c7e8-acae-404c-af7d-6cac38e354b8/disk
        Exit code: 255
        Stdout: ''
        Stderr: "Warning: Permanently added '[192.0.2.2]:8022' (ED25519) to the list of known hosts.\r\nsubsystem request failed on channel 0\r\nscp: Connection closed\r\n"
    
    This is not seen on Ubuntu Jammy, which uses OpenSSH 8.9, while Debian
    Bookworm uses OpenSSH 9.2. This is likely related to this change in
    OpenSSH 9.0 [2]:
    
        This release switches scp(1) from using the legacy scp/rcp protocol
        to using the SFTP protocol by default.
    
    Configure sftp subsystem like on RHEL9 derivatives. Even though it is
    not yet required for Ubuntu, we also configure it so we are ready for
    the Noble release.
    
    [1] https://review.opendev.org/c/openstack/kolla-ansible/+/904249
    [2] https://www.openssh.com/txt/release-9.0
    
    Closes-Bug: #2048700
    Change-Id: I9f1129136d7664d5cc3b57ae5f7e8d05c499a2a5