Update git submodules
* Update octavia from branch 'master'
  to 1d77e93f2889627cb87f1aed3259b83e91e83239
  - Merge "Fix new errors with SQLAlchemy 1.4"
  - Fix new errors with SQLAlchemy 1.4
    
    Fixed in Repositories.get_amphora_stats:
      TypeError: unsupported operand type(s) for +:
      'ImmutableColumnCollection' and 'list'
    
    Fixed in many places:
      KeyError: "Deferred loader for attribute 'id' failed to populate
      correctly"
    
      Modifying an object without using a transaction created some issues
      with the next query. SQLAlchemy flushed and expired the modified
      object while it still needed to read one attribute. This is a weird
      behavior in SQLAlchemy>=1.4 (perhaps a bug), but using transactions
      seems the correct way to update the objects.
    
      Note: The message in the SQLAlchemy exception is totally bogus.
    
    Change-Id: I64b5c70fca7f1cacb2ef10c2b61f28b9000c7504