Updated openstack/openstack Project: openstack/keystone  e3579c65f24650d898ca5f484118dd7c746f8ea7
Raise NotImplementedError instead of NotImplemented

NotImplementedError is the name of the exception
(https://docs.python.org/2/library/exceptions.html).
NotImplemented is the name of a constant
(https://docs.python.org/2/library/constants.html).
>>> raise NotImplemented()
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
>>> raise NotImplementedError()
Traceback (most recent call last):
  File "<pyshell#32>", line 1, in <module>
    raise NotImplementedError()
NotImplementedError

This patch fix it.

Change-Id: I36292e5ee18bd792205a8ff527f4ae9705c61b61
Closes-Bug: #1339855