Updated openstack/openstack Project: openstack/nova  2429b91cef13eefab562cf1a5ce30296e7b0d9ef
docs - Fix docstring issues in virt tree

Fix the following errors in several files.

ERROR: Unexpected indentation.
ERROR: Unknown interpreted text role "paramref".
WARNING: Block quote ends without a blank line; unexpected unindent.
WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: Enumerated list ends without a blank line; unexpected unindent.
WARNING: Field list ends without a blank line; unexpected unindent.

Specifically the "Unknown interpreted text role" was fixed by adding
a separate import instead of importing 'text' directly. Others were
indentation, new lines, or adding lists.

Change-Id: I241ce1ca9831d9df00d022297ea622953a6fdc60