Update git submodules
* Update requirements from branch 'master'
  to 12c21da56867f1ca4746b1f351194b23ce55b802
  - Updated from generate-constraints
    
    Fixes applied to automated upper-constraints.txt update:
    
    Pin versions for packages that are not ready for updating:
    
    - pyasn1,pyasn1_modules
    - pysnmp-lextudio:
        ironic: "AttributeError: module 'pysnmp.hlapi' has no attribute 'usmHMACMD5AuthProtocol'"
    - pyroute2: issues with neutron
    
    Pins only relevant for python_version==3.10:
    
    - backports.strenum===1.3.1
    
    Co-Authored-by: Dr. Jens Harbott <harbott@osism.tech>
    Change-Id: Ifdce39f736a5a61586e304c8978d4d159ab0bbd2
    Signed-off-by: OpenStack Proposal Bot <openstack-infra@lists.openstack.org>
    Generated-By: openstack/project-config:playbooks/proposal/propose_update.sh