Updated openstack/openstack Project: openstack/python-neutronclient  77b4c9bda9e49a9f6016a035058be6f85e9133b7
Reverse order of tests to avoid incompatibility

If py26 tests are run first, there is a incompatibility in the
.testrepository that breaks several tests.  To get around this, you
need to run the py33 tests first.  This change was made over in the
cliff project.

Before:

    (.venv)terry@brat:~/hp/ncli$ rm -rf .testrepository/
    (.venv)terry@brat:~/hp/ncli$ tox
      ...
      py26: commands succeeded
      py27: commands succeeded
    ERROR:   py33: commands failed
    ERROR:   py34: commands failed
    ERROR:   pypy: commands failed
      pep8: commands succeeded

After:

    (.venv)terry@brat:~/hp/ncli$ rm -rf .testrepository/
    (.venv)terry@brat:~/hp/ncli$ tox
      ...
      py33: commands succeeded
      py34: commands succeeded
      py26: commands succeeded
      py27: commands succeeded
      pypy: commands succeeded
      pep8: commands succeeded
      congratulations :)
    (.venv)terry@brat:~/hp/ncli$

Closes-Bug: 1415446

Change-Id: Ia0b44cc4a05dd1c668204d8d4dce5381d35373fe