Updated openstack/openstack Project: openstack/nova  9dce3e873649ebc1f85ec93e8021000f482a135b
Add debug log for url not found

I got following error from unit tests
apparently it's not helpful to know what's the root cause to make the failure
This patch adds a debug log

2014-11-21 16:47:52,943 DEBUG [nova.openstack.common.fileutils] Reloading cached file /tmp/tmpTBjKpX/tmpiC7e2k/policy.json
2014-11-21 16:47:52,950 DEBUG [nova.openstack.common.policy] Rules successfully reloaded
2014-11-21 16:47:52,951 WARNING [nova.openstack.common.policy] Can not find policy directories policy.d
2014-11-21 16:47:52,954 DEBUG [nova.network.minidns] minidns file is |/tmp/tmpTBjKpX/tmpdjtU4j/dnstest.txt|
2014-11-21 16:47:52,955 DEBUG [nova.network.minidns] minidns file is |/tmp/tmpTBjKpX/tmpCHMwMh/dnstest.txt|
2014-11-21 16:47:52,958 DEBUG [nova.network.minidns] minidns file is |/tmp/tmpTBjKpX/tmpggVMPv/dnstest.txt|
2014-11-21 16:47:52,959 DEBUG [nova.network.minidns] minidns file is |/tmp/tmpTBjKpX/tmpz2Ptbv/dnstest.txt|
}}}

Traceback (most recent call last):
  File "/home/jichen/git/nova/nova/tests/unit/api/openstack/compute/contrib/test_virtual_interfaces.py", line 84, in test_get_virtual_interfaces_list
    self.assertEqual(res.status_int, 200)
  File "/home/jichen/git/nova/.venv/local/lib/python2.7/site-packages/testtools/testcase.py", line 348, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/jichen/git/nova/.venv/local/lib/python2.7/site-packages/testtools/testcase.py", line 433, in assertThat
    raise mismatch_error
MismatchError: 404 != 200

Change-Id: I30a302cf624f023cb7e2228ced7774036a6d7fba