Updated openstack/openstack Project: openstack/trove  49a6f565c161f6ab592b4320120bde1db9df2529
unwedge the gate

This commit is a composite of two commits [1] and [2] to help unwedge
the gate. Both of them are required for the gate to possibly pass.

It introduces an unsafe change to unblock the gate temporarily. It
still needs to be debugged and addressed. The change in question is in
_remove_incompatible_context_args() in
trove/common/context.py. Without this check, initial tests indicate
that the system works as expected and testing locally is
successful. Why this is the case, I don't know yet but will
investigate in parallel.

[1] https://review.openstack.org/#/c/425857/
[2] https://review.openstack.org/#/c/423086/
[3] https://review.openstack.org/#/c/412497

From [1]

Fix a ``tox -eapi-ref`` warning

Currently, generating api-ref results in a warning that is treated as
an error.

See [1]. Since api-ref is now a jenkins voting gate, this needs to be
fixed.

[1] http://logs.openstack.org/56/401456/9/check/gate-trove-api-ref/e2e0d9d/console.html#_2017-01-26_17_23_10_952073

From [2]

SessionClient' object has no attribute 'user' Now gate py27 and py34
are being error:'SessionClient' object has no attribute 'user'" I
observed that this is because novaclient from 6.0.0 into 7.0.0 caused,
In novaclient 7.0.0,password and username is merge to auth[1],[2], I
tried to make a change, get password and username from auth[3].

[1]:https://github.com/openstack/python-novaclient/blob/6.0.0/novaclient/client.py#L164
[2]:https://github.com/openstack/python-novaclient/blob/7.0.0/novaclient/client.py#L147
[3]:https://github.com/openstack/keystoneauth/blob/master/keystoneauth1/identity/generic/password.py#L37

Change-Id: I6fb2bdcc4b83457e08b24599fb4a297ef6ec6c14
Closes-Bug: #1657968
Co-Authored-By: Andrey Kurilin <akurilin@mirantis.com>
Co-Authored-By: jiansong <jian.song@easystack.cn>
Co-Authored-By: Tin Lam <tinlam@gmail.com>
Related: I45a40d599b3a302726dc21e409a8da26c9f1f741
Related: I93c1942bb41bd77ea169f0e47d37132ce5d3637d
Related: I41f4144821e491da689c188e25bc2b916867bdca