Updated openstack/openstack Project: openstack-dev/pbr  1dfe9ef348c777bef67b2c2b1d35e50ebc720333
Remove sphinx_config.init_values() manual call

The function signature for Sphinx's config.init_values() changed since
version 1.3. That leads to:

TypeError: init_values() takes exactly 2 arguments (1 given)

But the function is already correctly called from
application.Sphinx()'s constructor. So use the configuration object
from the application instead of creating an own config object.

Change-Id: I343c26560bfe5116d5348b50b1890b3442ed845a
Closes-Bug: #1379998