Update git submodules
* Update puppet-openstack-integration from branch 'master'
  to fe9a9105cb91de1c92f1d0b361b1111b055a7118
  - Drop usage of 'update-ca-trust force-enable'
    
    ... because the subcommand does not exist actually. The command fails
    with the following error in recent CentOS Stream 9.
    
    ```
    Error: Unknown command: force-enable
    
    Usage: /usr/bin/update-ca-trust [extract] [-o DIR|--output=DIR]
    
    Update the system trust store in /etc/pki/ca-trust/extracted.
    
    COMMANDS
    (absent/empty command): Same as the extract command described below.
    
    extract: Instruct update-ca-trust to scan the source configuration in
    /usr/share/pki/ca-trust-source and /etc/pki/ca-trust/source and produce
    updated versions of the consolidated configuration files stored below
    the /etc/pki/ca-trust/extracted directory hierarchy.
    
    EXTRACT OPTIONS
    -o DIR, --output=DIR: Write the extracted trust store into the given
    directory instead of updating /etc/pki/ca-trust/extracted.
    ```
    
    Change-Id: I38bbfc08a73823d2fd6e00974e277130cbff7e12