Update git submodules
* Update puppet-tempest from branch 'master'
  to 20871082dd2ba688022e77975e291f15cf7c9e6a
  - Remove usage of deleted manifest_dir
    
    Recent update in rspec-puppet removed some of the config interfaces for
    old puppet versions[1]. This drops usage of these interfaces to resolve
    the following error in unit tests.
    
    ```
    An error occurred while loading ./spec/unit/provider/manila_spec.rb.
    Failure/Error: c.manifest_dir = File.join(fixture_path, 'manifests')
    
    NoMethodError:
      undefined method `manifest_dir='...
    ```
    
    [1] https://github.com/puppetlabs/rspec-puppet/commit/316d95923cdbab4daf980629cbded351dd61354c
    
    Change-Id: I0121e1c34e25ca2c5e812c03d68f289b7f235140