Update git submodules
* Update placement from branch 'master'
  to 91b0ff88498a774b6040ff4d6bde6ae245be9943
  - Merge "Correctly handle integrity errors on MySQL 8.x"
  - Correctly handle integrity errors on MySQL 8.x
    
    We attempt to parse the 'DBDuplicateEntry' exceptions raised by oslo.db
    in the event of an integrity error to provide more useful information to
    the user about what they did wrong. To do that, we're looking at the
    'columns' attribute of this exception, which should list the conflicting
    column(s), and extracting entries from the user-provided data based on
    these columns names. However, on MySQL 8.x this does not return a column
    name but rather a constraint name. This results in a KeyError when we
    attempt to show the offending data by pulling it out by "column" name.
    For example:
    
      KeyError: 'resource_providers.uniq_resource_providers0name'
    
    The solution is simple. Since there are only two unique constraints for
    the 'ResourceProvider' model, we can simply check for these and map them
    to their corresponding columns if found. The existing code can be
    retained as a fallback for other database backends and legacy MySQL
    versions.
    
    Change-Id: I1dda02d46cb019eedd6e3ef64e327ac85bb7c484
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
    Story: 2008750
    Task: 42110