Update git submodules
* Update openstackdocstheme from branch 'master'
  - Catch OSError when trying to get the last_update from git
    
    The "git" executable might not be available (eg. in build environments
    where the .git dir is anyway no there because tarballs are used). In
    that case, the current code failed with an
    
    OSError: [Errno 2] No such file or directory
    
    exception. This is now catched and the code works even if "git" is not
    available.
    
    Change-Id: I10f69d1b2cadced4cd155ef9b7f700a2806f44f9
    
  - Merge "Update hacking version"
  - Translations: Handle directories
    
    We need to handle translations of sub-directories the same way
    they are handled in our scripts to push to the translation server,
    update the code.
    
    Change-Id: I501289767d273760b0a69d52d1a9dda867fc4e04
    Co-Authored-By: Ian Y. Choi <ianyrchoi@gmail.com>
    
  - Update hacking version
    
    Use latest release 1.1.0.
    
    Change-Id: I00659c453a50c55f9569ec99dd69b923dbb087d4
    
  - Merge "Change openstack-dev to openstack-discuss"
  - Merge "use git modification timestamps as last-updated time for each page"
  - Change openstack-dev to openstack-discuss
    
    Mailinglists have been updated. Openstack-discuss replaces openstack-dev.
    
    Change-Id: I01bb71d78bf8c08afd5e3420f93bdf4417761765
    
  - use git modification timestamps as last-updated time for each page
    
    Look at the git history to determine the last time a page was modified
    and use that date as the last-updated date instead of the default
    value of the current time.
    
    Change-Id: I80db00eb2016859e1095c6a1db952f17df3e00d6
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Import tools for building translated documents
    
    Import from i18n repo the scripts get-lang-display-name.py and
    build-docs.sh, update comments so that they are generic.
    
    Add the two files to setup.cfg so that they get distributed with the
    package and can be executed from tox for building of translated
    documents.
    
    Change-Id: I80fcb1ed857da8452b310e6707cce3940577a35a
    
  - Fix typo
    
    s/diplayed/displayed/
    
    Change-Id: Idd22343b2b204b1cfc4c911036e7ecfb6d5c8321
    
  - Remove setup.py check from pep8 job
    
    Using "python setup.py check -r -s" method of checking the package has
    been deprecated with the new recommendation to build the sdist and
    wheel, then running "twine check" against the output.
    
    Luckily, there is already a job that covers this that only runs when the
    README, setup.py, or setup.cfg files change, making running this in the
    pep8 job redundant. This covered by the test-release-openstack-python3
    that is defined in the publish-to-pypi-python3 template.
    
    More details can be found in this mailing list post:
    
    http://lists.openstack.org/pipermail/openstack-dev/2018-October/136136.html
    
    Change-Id: I7c17371b9f43c50bf07a460e1a3a731bf6d6a793
    Signed-off-by: Sean McGinnis <sean.mcginnis@gmail.com>
    
  - StarlingX nav fix to remove "Software Update" links
    
    The "Software Update" target page for the StarlingX Docs has gone
    away.  The starlingx theme still had that link in the left-hand
    nav panel.  I have removed it.
    
    Change-Id: I23e3ae6382766da9326f5abd545edfcdeacebe30
    Signed-off-by: Scott Rifenbark <srifenbark@gmail.com>
    
  - The theme is openstackdocs
    
    Fix path lookup, see
    https://review.openstack.org/#/c/607298/12/openstackdocstheme/paths.py
    and  openstackdocstheme/ext.py where we check for "openstackdocs" and
    not "openstack".
    
    Change-Id: I669b0368f27916b027205828cf3982657c64326d
    
  - Readd get_openstack_logo_path
    
    Change I594136a0ea66d61f60dafc6a853137470efc7d42 broke the API of this
    package with renaming get_openstack_logo_path which broke a couple
    of users, readd it.
    
    Change-Id: Ia2f6760e0f6f53d94a8d3358d5c4e2fe0a2d7bf3
    
  - Set default paths for OpenStack
    
    Several previous openstackdocstheme deployments
    used get_pdf_theme_path() and get_openstack_logo_path()
    without arguments. This patch adds default arguments as 'openstack'
    to correctly work on such deployments.
    
    Change-Id: I23a5ae26b3367514a8e531925f93ddc97d56f6be
    
  - Make a bare-bones starlingxdocs theme
    
    We can use this as a starting point for further changes.  These files
    are copies of those from openstacdocs with most of the openstac-specific
    bits removed.  This way we can track additional changes made as we progress.
    
    Change-Id: I41c2a7d63ba7796aa3cf3cc001e077d5de28a14d
    Signed-off-by: Dean Troyer <dtroyer@gmail.com>
    
  - Merge "Remove example of deprecated app.info"
  - Add scripts to the head section
    
    For consumers that also call the add_javascript() function scripts are
    added to the _static folder but not loaded in the HTML resulting in them
    not working.
    
    This change iterates over the script_files lists and adds the needed
    <script></script> element.
    
    Closes-Bug: 1798002
    Needed-By: https://review.openstack.org/#/c/607538/
    Change-Id: Ie39e138314fed91f59cd9cb5d78d676c04fb78e6
    
  - Remove example of deprecated app.info
    
    Using the app instance for logging is deprecated. Thus updates example
    output to show using a logger instead.
    
    Change-Id: I060dbb528d303a00bc4b4b91a0816e35b561e07b
    Signed-off-by: Sean McGinnis <sean.mcginnis@gmail.com>
    
  - Add starlingxdocs theme support
    
    At the PTG the Docs team and dhellmann decided that openstackdocstheme
    was the proper place to keep the modifications required to build
    a theme for StarlingX and other OpenStack Foundation-related projects.
    
    This is a minimal set of changes to support a second theme with a couple
    of visual changes thrown in to make obvious that the correct theme
    is being used. The remainder of the visual work will follow.
    Both PNG and SVG versions of the logo are included.
    
    Add an additional jobs to build the docs and PDF with the new theme.
    
    Modify the wording in README.rst and the docs index page regarding
    the distinction between openstackdocstheme the module and openstackdocs
    and starlingxdocs the themes and their intended uses.
    
    There are a number of hard-coded OpenStack-isms that will eventually
    need to be addressed.
    
    Change-Id: I594136a0ea66d61f60dafc6a853137470efc7d42
    Signed-off-by: Dean Troyer <dtroyer@gmail.com>
    
  - Merge "Import build-openstack-api-ref"
  - Fix regressions introduced in 1.25.0
    
    The 1.25.0 theme failed to pick up the new root_title option
    and ate a meaningful space in "Page Contents". This should fix
    both issues.
    
    Change-Id: I3e77586850daef9b1e7cd2ae24889bc00a074413
    
  - Add an option to disable global TOC section
    
    On some sites (like the governance site) the navigation between
    pages is included in the page content itself, making the global
    section of the TOC unnecessary. This adds a new theme option
    (display_global_toc_section) to allow to disable it.
    
    Change-Id: Ib6fb3bd1a6a776be06bc09e2e4183ca909ea7b60
    
  - Make root title customizable
    
    The theme displays "OpenStack Docs:" in the title and "Docs home"
    in the tooltip, which makes it hard to reuse for other websites
    (including the governance website). This patch makes the root title
    ("OpenStack Docs" by default) configurable.
    
    Change-Id: I4140f62a328debf81703cddd17dd6364b5eab479
    
  - Import build-openstack-api-ref
    
    We can add this in-repo, move it over from project-config.
    
    Change-Id: Ib8b535728461516f415af07d4f177ac1662f8b24
    
  - log details of html context
    
    Log some debugging. details as the html context is constructed.
    
    Change-Id: I3c3889e04139dfdc041ea012afba5f7f6377e4ca
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - pass useStoryboard to logABug
    
    The useStoryboard variable is being defined but was not being passed
    to logABug. It may have been working as a global, but it is more clear
    as an argument to the function, so pass it in.
    
    Change-Id: I554b6089c9d3cbfb216108a051de835d3cd449a4
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - ensure repository_name is always set
    
    The repository_name variable wasn't being set in the context, so the
    bug link function was failing with an error due to the undefined
    variable because the JS variable repositoryName was only conditionally
    being created.
    
    Change-Id: I0dccbfe7f02e6fb93ddab4d79cba5d2e9d2d543e
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Merge "Fix project-navigator link"
  - Fix the incorrect storyboard url
    
    Using "repository_name" instead of "bug_project" to combine with the
    "urlBase" string, if set use_storyboard to "True". storyboard URLs are
    in this format:
    "https://storyboard.openstack.org/#!/project/"+"openstack/whereto"
    not:
    "https://storyboard.openstack.org/#!/project/"+"whereto"
    
    Change-Id: Ib553d95f22c7848a5bd537b8929a2d6e6625451b
    
  - Fix project-navigator link
    
    The navigator has moved, update links.
    
    Change-Id: Ia3b676b79f98dc7af8ba1efe987bf6cf0a89abf8
    Related-Bug: #1791447
    
  - Fix use_storyboard
    
    Initialize variable with False and not with empty string - the variable
    is a boolean.
    
    Update example.
    
    Changed this so that
    use_storybard = true
    in doc/source/conf.py will not result in:
    
      The config value `use_storyboard' has type `bool', defaults to `str'.
    
    Change-Id: I2ed164b9b0badade702c50543ac1a5eea4d1867b
    
  - Merge "Handle StoryBoard project groups"
  - Handle StoryBoard project groups
    
    StoryBoard now display the project group in the URL and not anymore a
    number. Allow setting the storyboard project group to the name now.
    This implies setting a new variable to differentiate between Launchpad
    and StoryBoard.
    
    Change-Id: Ie6f8c48fffe04256ad07f22e95935f6f7257ea17
    
  - Do not show badge for master only repos
    
    If a repo has no stable branches, we do not need to show the badge,
    disable it automatically.
    
    Also, disable it for releasenotes, api-guide and api-ref. These
    documents are always published from master and are versionless.
    
    This avoids changing most of the repositories to disable the badge.
    
    Change-Id: I063af45e40bd41e27334638e2cf65ca0c9119e63
    
  - Merge "Fix build jobs"
  - Merge "Use sphinx-build everywhere"
  - Fix build jobs
    
    The buildpdf did not run since the parent job was mistyped, fix parent
    job name and rename to follow conventions on job names.
    
    Cleanup jobs in tox.ini:
    Docs environment is now run by PTI, so only run building the html for
    docs directory.
    
    Change-Id: Ibd0e731d9b090e0c444a8e18caa3ad3153f8aa4a
    
  - Do not display "latest" badge if repo is not versioned
    
    We do now display the badge for version even on repos that do not have
    branches like https://docs.openstack.org/infra/manual . The reason is
    that the test is against series - and we *always* set series, by default
    to 'latest'.
    
    Add a new option to disable showing of the badge called display_badge
    and use it. Repos can set this as part of html options.
    
    Disable showing the badge for api-ref test document.
    
    Change-Id: I985b49412aa1848b915b8f0a2ff9e95867e420ca
    
  - Use sphinx-build everywhere
    
    Using 'python setup.py build_sphinx' is deprecated, use sphinx-build
    everywhere in tox.ini.
    
    Change-Id: Ia1ce85ff2ee75718c79c84d58b496348d5327b7f
    
  - switch documentation job to new PTI
    
    This is a mechanically generated patch to switch the documentation
    jobs to use the new PTI versions of the jobs as part of the
    python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: If1ba75d02009e61c40ea9cbb6d51dd9794cedf13
    Story: #2002586
    Task: #24293
    
  - import zuul job settings from project-config
    
    This is a mechanically generated patch to complete step 1 of moving
    the zuul job settings out of project-config and into each project
    repository.
    
    Because there will be a separate patch on each branch, the branch
    specifiers for branch-specific jobs have been removed.
    
    Because this patch is generated by a script, there may be some
    cosmetic changes to the layout of the YAML file(s) as the contents are
    normalized.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Ie5891998c5e410c92404aa12007a2fd61569a618
    Story: #2002586
    Task: #24293
    
  - Merge "Added deprecation badge"
  - Make bg color for highlighted text less bright
    
    See also: I464fa60a52f176273ce9ffa318c1f192575f24d5
    Closes-Bug: #1785994
    
    Change-Id: Ie6a25574a2fcda85704065277ef0998a28a0414e
    
  - ignore files created during packaging
    
    The build directory is created by setuptools when a package is created.
    
    The file RELEASENOTES.rst used to exist as a manually managed file,
    and is now created when reno is installed and a package is created.
    
    The file releasenotes/notes/reno.cache is created when reno is installed
    and a package is created.
    
    None of these files should be tracked by git, so add them to the
    .gitignore list.
    
    Change-Id: Ia5e24a9d21ed2a0e51dd81b2cd3e44231c885fcc
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Added deprecation badge
    
    included deprecation badge from manuas project
    in order to work, both sites should be hosted on same domain
    ( as it is right now ) or have CORS enabled
    
    depends on https://review.openstack.org/#/c/585516/
    
    Change-Id: Idb992bd6d313270869c28bdacc450eb9c7482d16
    
  - Merge "Make emphasize-lines more highlighted"
  - Make emphasize-lines more highlighted
    
    Change-Id: I464fa60a52f176273ce9ffa318c1f192575f24d5
    
  - Updated Search widget
    
    Migrated from 3rd party search service swiftype to open source SOLR due to cost increase.
    
    Change-Id: I7f07ebb0014a60213e0ab48056183445f3217e4b
    
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Change-Id: I73e9613bf96da80d4dfd53246a568d0de691ae01
    
  - add the series name to the template context
    
    Add a variable "series" to the template context so we can use it for
    building URLs in templates.
    
    Change-Id: I43c73e63b31d3986e1c34524a42113f7f36f34d5
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - always look for the .gitreview file in root of repo
    
    The build may not be happening in the root of the repository, so look
    for that directory explicitly before trying to read the .gitreview
    file.
    
    Change-Id: I75e952c567d8387d3c620a2b005474ad2441f086
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Strip tags from titles in bugTitle and meta
    
    We need to ensure that HTML tags in 'title' are stripped in these places
    or the output will be corrupted. That makes the bug reporting links are
    not working properly.
    
    Change-Id: Iddc041488cb3b0dc4d784fef92920496ce1a747f
    Closes-Bug: #1713054
    
  - Check RST as part of linting
    
    Check our RST files so that uploading to PyPI works fine with a linter
    check.
    
    Change-Id: Id35de317908918d890f152d62221997b484ba4a8
    
  - Merge "Use metadata summary instead name for doc title"
  - Use metadata summary instead name for doc title
    
    hint: ugly name like openstackdocumentationcontributorguide breaks
    the page layout.
    
    depends on the count of words and the length of the name it will use
    name or summary.
    
    Change-Id: Id3488cfab61be5791c34f4f4330087627e7b9719
    
  - Relocate bug_tag in logABug generated URL
    
    The content of field.comment may contain characters that confuse
    Launchpad and block it from recognizing field.tags, so move the
    location of the tags specification to earlier in the URL.
    
    Change-Id: I62ce0a93ca963fe412f17e56aab743ac9c3deb98
    Closes-bug: #1766705