Update git submodules
* Update placement from branch 'master'
  to ff0fc616be702ca56c007a1a3a03af90b147aa30
  - Merge "Use cchardet>=2.2.0a2 for placement-perfload job"
  - Use cchardet>=2.2.0a2 for placement-perfload job
    
    The placement-perfload job is currently failing with the following
    error because the current latest version of cchardet (2.1.7) does not
    have support for Python 3.10, 3.11, and 3.12:
    
    Building wheels for collected packages: cchardet
      Building wheel for cchardet (pyproject.toml): started
      Building wheel for cchardet (pyproject.toml): finished with status 'error'
      error: subprocess-exited-with-error
    
      × Building wheel for cchardet (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          running bdist_wheel
          running build
          running build_py
          creating build/lib.linux-x86_64-cpython-312/cchardet
          copying src/cchardet/__init__.py -> build/lib.linux-x86_64-cpython-312/cchardet
          copying src/cchardet/version.py -> build/lib.linux-x86_64-cpython-312/cchardet
          running build_ext
          building 'cchardet._cchardet' extension
          creating build/temp.linux-x86_64-cpython-312/src/cchardet
          creating build/temp.linux-x86_64-cpython-312/src/ext/uchardet/src
          creating build/temp.linux-x86_64-cpython-312/src/ext/uchardet/src/LangModels
          x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -Isrc/ext/uchardet/src -I/home/zuul/src/opendev.org/openstack/placement/.placeload/include -I/usr/include/python3.12 -c src/cchardet/_cchardet.cpp -o build/temp.linux-x86_64-cpython-312/src/cchardet/_cchardet.o
          src/cchardet/_cchardet.cpp:196:12: fatal error: longintrepr.h: No such file or directory
            196 |   #include "longintrepr.h"
                |            ^~~~~~~~~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
          [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for cchardet
    
    This installs the alpha version which fixes it, for now.
    
    Details in https://github.com/PyYoshi/cChardet/issues/81
    
    Change-Id: I1ecd1bf54ef5aa68935e3f5809aed8de5cc2d79c