Update git submodules
* Update tenks from branch 'master'
  to 66f0066273e6dfc9aab18bd71400d308d8e5b0e2
  - Use Yoga upper constraints to avoid Python version conflict
    
    Requirements upper constraints bumped python-novaclient to version
    18.0.0 [1], which requires Python 3.8 [2]. This results in failures when
    installing python-openstackclient on CentOS and Rocky with Python 3.6.
    
        ERROR: Cannot install python-openstackclient==5.8.0 because these package versions have conflicting dependencies.
    
        The conflict is caused by:
            python-openstackclient 5.8.0 depends on python-novaclient>=17.0.0
            The user requested (constraint) python-novaclient===18.0.0
    
    Work around this issue by using yoga upper constraints until we upgrade
    to CentOS Stream 9 and Rocky Linux 9.
    
    [1] https://review.opendev.org/c/openstack/requirements/+/842808
    [2] https://review.opendev.org/c/openstack/python-novaclient/+/838944
    
    Change-Id: I802b206199b06cfa1983f6f07f195660dd7d86ad