Updated openstack/openstack Project: openstack-dev/devstack  32680fce378630944493fde1ca16601c889befa8 null Added libffi-dev to the needed packages
After pyOpenSSL 0.14 update, Grizzly devstack started failing:
 Downloading/unpacking cryptography>=0.2.1 (from pyOpenSSL->python-glanceclient==0.12.0.61.g8b76817)
   Running setup.py egg_info for package cryptography
     c/_cffi_backend.c:14:17: fatal error: ffi.h: No such file or directory

Change-Id: Ida7001886f17c9413b33312f12f2478a54bd6c90
(cherry picked from commit b6f7ea4fb0bfd4bcc1d1bb35f97d29eb70075b73)