Updated openstack/openstack Project: openstack/zaqar  830c54dc55677853e7d0ab20d3b5a49391770551
Fix cross-transport error handler

zaqar.common.api.utils.raises_conn_error decorator is intended to catch
all of the uncatched exceptions to return 500 error response.

But now it can't return normal error response, because it passes None
instead of Request object to the Response constructor.

Eventually AttributeError is raised:
AttributeError: 'NoneType' object has no attribute 'get_request'

Because of unexpected AttributeError, no response is sent to the client.

This patch makes zaqar.common.api.utils.raises_conn_error pass Request
object to the Response constructor.

Also it renames this decorator to on_exception_sends_500, because that's
what this decorator actually is: it catches exceptions and returns
response with code 500. It doesn't raise connection error exceptions
like these similarly named decorators in the storage drivers:
zaqar.storage.mongodb.utils.raises_conn_error
and
zaqar.storage.redis.utils.raises_conn_error

Closes-Bug: 1538794
Change-Id: I751d46383e8d434f65fea1694bcb8c76923d3aca