Updated openstack/openstack Project: openstack/neutron-fwaas  a0c93fd8dfd9a694970bf4849624fc494872f77b
Fix neutron-fwaas cover tests

The tox.ini command for 'tox -e cover' breaks with error:
error: option --coverage-package-name not recognized

Appears to be same issue as found in neutron-vpnaas and fixed
there under https://review.openstack.org/#/c/217847/

Applying same fix to neutron-fwaas.

Same logic applies to 'tox -e cover-constraints', though
because upstream changed 'upper-constraints.txt' eventlet
to 0.18.3 in middle had to set to local stack value to run:
export UPPER_CONSTRAINTS_FILE=/opt/stack/requirements/
upper-constraints.txt

Closes-Bug: #1546793
Change-Id: I82fde90d1ed17f2495f8560b8e56febc10e3013c