Update git submodules
* Update releases from branch 'master'
  to 0eb23e0bc65d330231265c2e1b8acad42b40fa1b
  - Merge "[tool] Fix branch id fetching in scripts"
  - [tool] Fix branch id fetching in scripts
    
    When refactoring branch name helpers [1] we forgot about the scripts
    in tools directory, that now drops errors [2]. get_stable_branch_id
    needs to be used from openstack_releases.series_status now.
    
    [1] https://review.opendev.org/c/openstack/releases/+/995925
    [2] AttributeError: module 'openstack_releases.gitutils' has no attribute 'get_stable_branch_id'
    
    Change-Id: I9c6e39ee504b3816eaa6062431109b856d2762e2
    Signed-off-by: Elod Illes <elod.illes@est.tech>