Updated openstack/openstack Project: openstack/ironic  78549cd1effe5a9f04fdfd5d1077e23ab11d2a78
Use assertIn and assertNotIn

Tests should use:
  self.assertIn(value, list)
  self.assertNotIn(value, list)

instead of:
  self.assertTrue(value in list)
  self.assertFalse(value in list)

because assertIn and assertNotIn raise more meaningful errors:
  self.assertIn(3, [1, 2]
  >>> MismatchError: 3 not in [1, 2]

  self.assertTrue(3 in [1, 2])
  >>> AssertionError: False is not true

Change-Id: Ic2461afd9872767fe615064610daffb52e743388
Closes-Bug: #1510007