Update git submodules
* Update openstack-helm-infra from branch 'master'
  to e511ba851770e5c6b03957b85e3b889ce578ee50
  - Fix 'tox -e releasenotes'
    
    Running 'tox -e releasenotes' fails with:
    
    ERROR: You must give at least one requirement to install
    
    Added missing doc/requirements.txt dep to tox.ini, similar
    to recent openstack-helm patch.
    
    Trivialfix
    
    Change-Id: I01f82cdd92828ad0c99c343a1261f57562be3041