Update git submodules
* Update oslo.db from branch 'master'
  to dc60623d77bdaa51d20bab4641bd9ae5466a0d16
  - Merge "Fix the wrong module name in import"
  - Fix the wrong module name in import
    
    Fix the wrong import added by 6a207afb3e5be958a5a946c787feba13b4c58f1b
    which is causing the following error.
    
    ```
    AttributeError: module 'debtcollector' has no attribute 'removals'
    ```
    
    Closes-Bug: #2099908
    Change-Id: Iebc9b67e3cdd4dc05ca347237e01f6ba31456cf4