Update git submodules
* Update python-openstackclient from branch 'master'
  - Add py36 env
    
    While running `tox` command in binoic env, we see the following
    message,
    ERROR: InterpreterNotFound: python3.5
    It is because the default py3 version for binoic is py36.
    This patch adds the env in OSC also maintaining consistency
    with setup.cfg
    
    Change-Id: I8e5cf72901cba34ad44f2b356609f85b3b0c431f