Updated openstack/openstack Project: openstack/python-novaclient  37457c3aaa5b025a6252d1d10fb0e376080cf496
Remove _print_volume from volume-update

Since the response of volume-update do not contain a body, just a status
code 202, so when calling _print_volume(volume), there will be an error:
`ERROR (AttributeError): 'NoneType' object has no attribute '_info'`.

Change-Id: I950ae7dca5e847beae7295d72d009f2d07d07c51
Closes-bug: 1321205