Update git submodules
* Update placement from branch 'master'
  to b62cbabc18c295b55c3baccc6a8c5a37542d40cc
  - Merge "db: Replace use of deprecated API"
  - db: Replace use of deprecated API
    
    We were missing a number of users of SQLALchemy APIs that were either
    changed or removed in 2.0. These were yielding the following errors in
    2.0.
    
      TypeError: MetaData.__init__() got an unexpected keyword argument
      'bind'
    
      TypeError: TableClause.insert() got an unexpected keyword argument
      'values'
    
      TypeError: TableClause.update() got an unexpected keyword argument
      'values'
    
      AttributeError: 'Engine' object has no attribute 'execute'
    
    Resolve these issues. We will fix the test class issue in a follow-up.
    
    Change-Id: I8724b0738f097739f55cd8566bb30b7ddbe154d9
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>