Updated openstack/openstack Project: openstack/neutron  39c392ed8e5ce13196959b20bb6f65121b9ab767 null Fix TypeError: <MagicMock name='LinuxBridgeManager().local_ip'
This patch fixes an error that does not result in a test failure but
causes the following error to be logged in the test logs:

TypeError: <MagicMock name='LinuxBridgeManager().local_ip' id='666599248'>
is not JSON serializable

Related-Bug: #1234857

Change-Id: I65cdd997745d8b760031f8f32e3c10682ad2288e
(cherry picked from commit: d26dfed7d47926425bb55893da45f650d6549b9a)