Update git submodules
* Update oslo.service from branch 'master'
  to 12dbe0bcc091eeb1f193f6d7cb8420b9b6a27d71
  - Fix race condition in EventletServerServiceLauncherTest
    
    The below test set the graceful_shutdown_timeout=4 and run_server()
    start process with process_time=5 and the test check if time taken
    by SIGTERM signal exit is more than graceful_shutdown_timeout or not.
    
    But problem is run_server() sleep for extra 1 sec after starting the process
    of proces_time=5 which leave only 4 sec to complete the task which is exactly
    same as graceful_shutdown_timeout and end up in race condition. I faced this
    failure locally and it can happen in gate also.
    
    Setting graceful_shutdown_timeout as 2 to give proper margin for test assert.
    
    EventletServerServiceLauncherTest.test_graceful_stop_with_exceeded_graceful_shutdown_timeout
    
    Captured traceback:
    ~~~~~~~~~~~~~~~~~~~
        Traceback (most recent call last):
    
          File "/opt/stack/oslo.service/oslo_service/tests/test_service.py", line 726, in test_graceful_stop_with_exceeded_graceful_shutdown_timeout
        self.assertTrue(time_after - time_before > graceful_shutdown_timeout)
    
          File "/usr/lib/python3.12/unittest/case.py", line 727, in assertTrue
        raise self.failureException(msg)
    
        AssertionError: False is not true
    
    Change-Id: I63279fc1419fec851cabebc33a2e26e4624859fd
    Signed-off-by: Ghanshyam Maan <gmaan@ghanshyammann.com>