Updated openstack/openstack Project: openstack/oslosphinx  d901a7bd61db6a60e909978ffa9cd0e340519cfc
Subprocess returns bytes in py3

When later used the current code will break in
python3 due to:

TypeError: 'str' does not support the buffer
           interface

Change-Id: I11572dd510ce8255ed66de56d5d9000755f7fee2