Update git submodules
* Update swift from branch 'master'
  to 77530136f13f1fc0d8625d43e1689427d4ee2fad
  - tempurl: Fix PUT upload to temp url on py3
    
    Without this change, the self._response_headers gets a dict_items() type
    on PUT. But the rest of the code assumes that it is a list.
    
    Bug manifestation:
    
        File "swift/common/middleware/catch_errors.py", line 120,
            in handle_request
          self._response_headers.append(('X-Trans-Id', trans_id))
      AttributeError: 'dict_items' object has no attribute 'append'
    
    Closes-Bug: #1929083
    Change-Id: I5c398b6008716b64c668737e4201ba3b6ab3320b