Update git submodules
* Update nova from branch 'master'
  - Merge "Use placement stable version for functional job"
  - Use placement stable version for functional job
    
    nova-tox-functional is py2 job and need placement as required project.
    and started failing for incompatible py version:
    
    ERROR: Package 'openstack-placement' requires a different Python: 2.7.17 not in '>=3.6'
    
    - https://zuul.opendev.org/t/openstack/build/b460a8c59ad64e57b871aa3c00638b01/log/job-output.txt#782
    
    Placement master is now py3 only which mean master version will stop
    working on py2 env:
    - I6f458fb60b5a33b5aa2ce3ab292862ab98eb4670
    
    Current tox env mention the placement master link as deps, where need to use
    the stable version for stable jobs. Making deps with version not the
    fresh git clone like how other test-requirements.txt deps work.
    
    Change-Id: I96bb9fcb55f2a4fc3aefa01db70b45740db166c8