Updated openstack/openstack Project: openstack/oslo.db  f7489fe52cda57e23863d38b3edeee7f6ba12f7f
Fix python3.x scoping issues with removed 'de' variable

In python3.x the 'de' variable will be removed from the
scope after the except block exits (if it ever is entered)
so we need to use a different variable name to ensure that
it will not be deleted so we can use it later.

This avoids errors of the format:

UnboundLocalError: local variable 'de' referenced before
                   assignment

Change-Id: I9ea2bd6b3a8c392f8d27b0130dd6b7683fc44e7c