Updated openstack/openstack Project: openstack-infra/release-tools  70171305fb0bb053818b59bd657200769c464e5f
Use yes/no for pypi flag

In I8e0a2517d2a8c19381d2d57600da92c954775e5e we were processing
for the pypi flag, we just need to use a string instead of
the boolean, otherwise we fail when we try to concatenate

File "/Users/dims/openstack/infra/release-tools/list_deliverable_changes.py", line 121, in main
    print(' '.join(r))
TypeError: sequence item 6: expected string, bool found

Change-Id: I9c3e13320c05c2227584452453fabaf13e78c822