Update git submodules
* Update python-tripleoclient from branch 'master'
  to d690e9fec455f120e99ac1b5184f2c01d816f43b
  - Merge "Fix usage of collections.abc"
  - Fix usage of collections.abc
    
    Current logic to try importing the collections.abc module is broken and
    the collections module is always imported, which results in deprecation
    warning[1].
    
    >>> import collections
    >>> c_abc = collections.abc
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python3.8/collections/__init__.py", line 55, in __getattr__
        raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
    AttributeError: module 'collections' has no attribute 'abc'
    
    [1]
    DeprecationWarning: Using or importing the ABCs from 'collections'
    instead of from 'collections.abc' is deprecated since Python 3.3, and
    in 3.10 it will stop working
    
    Note that because Python 2 is no longer supported the logic to use
    collcations is just removed.
    
    Change-Id: Id0aeb77a68d556993bece14a71cdccc262c5461b