Update git submodules
* Update puppet-murano from branch 'master'
  to b5b3082b18f43a227ce83f4e6cac271f65e8778d
  - Remove usage of deleted manifest_dir
    
    Recent update in rspec-puppet removed some of the config interfaces for
    old puppet versions[1]. This drops usage of these interfaces to resolve
    the following error in unit tests.
    
    ```
    An error occurred while loading ./spec/unit/provider/manila_spec.rb.
    Failure/Error: c.manifest_dir = File.join(fixture_path, 'manifests')
    
    NoMethodError:
      undefined method `manifest_dir='...
    ```
    
    This also removes explicit setting of mock module. The definition is
    no longer required since we bumped puppetlabs_spec_helper to v 5.0.0.
    
    [1] https://github.com/puppetlabs/rspec-puppet/commit/316d95923cdbab4daf980629cbded351dd61354c
    
    Change-Id: Ia6a88e962b0a0b1f47ed4369054d73f7d03e098a