Update git submodules
* Update oslo.utils from branch 'master'
  - Merge "Fix race condition in eventletutils Event"
  - Use template for lower-constraints
    
    Small cleanups:
    
    * Use openstack-lower-constraints-jobs template, remove individual
      jobs.
    * Sort list of templates
    
    Change-Id: I3c1f03ef0cf2ee912db0b81005353e822e7ba4d2
    Needed-By: https://review.openstack.org/623229
    
  - Merge "Don't use monotonic on Python >=3.3"
  - Fix race condition in eventletutils Event
    
    The threading-compatible eventlet Event class has a race condition on
    the wait method. If greenthread A is blocked on the wait, but another
    greenthread B calls clear() and then set(), B calls self._event.send(),
    but A is waiting on a different eventlet Event which is no longer used
    by the oslo.service Event...
    
    To resolve this, when clearing an Event trigger the underlying eventlet
    Event immediately, then have the wait() method resume waiting on the new
    eventlet Event.
    
    Change-Id: I81579e2977bb965a5398a2cb4e3e24f5671e856a
    Co-Authored-By: Victor Stinner <vstinner@redhat.com>
    Co-Authored-By: Hervé Beraud <hberaud@redhat.com>
    Closes-Bug: #1805706
    
  - Don't use monotonic on Python >=3.3
    
    A change to the global-requirements[1] has limited use of the monotonic
    library to Python versions earlier than 3.3 (later versions have
    built-in support for a monotonic clock), so no requirements changes can
    be merged until we similarly limit it in requirements.txt.
    
    [1] https://review.openstack.org/615441
    
    Change-Id: Ib53d89ea820d21114d10280c9f4ab1b0c2c4a4bc
    
  - Update mailinglist from dev to discuss
    
    openstack-dev was decomissioned this night in https://review.openstack.org/621258
    Update openstack-dev to openstack-discuss
    
    Change-Id: I815cf3290b137940cbe9811bb5b5a59739425f01
    
  - Expose eventlet Event wrapper class
    
    We have a need to use the eventlet Event class directly in
    oslo.service. Currently it is copy-pasted from this project, but
    we now have a duplicate bug due to that so let's just expose it so
    one copy can be used in both places.
    
    This should be safe as the class implements a stdlib interface so
    we can't really alter the API, and it's not really private since
    instances of it are returned to users.
    
    Change-Id: If8e7a41f9fe5573a780f9faabdbaf1326631d37a
    Related-Change: https://review.openstack.org/558879
    Related-Bug: 1800879
    
  - Clean up .gitignore references to personal tools
    
    Developers run all sorts of different tools within Git repositories,
    any of which can leave their own special trashfiles all over the
    place. We can't every hope to catalog them all, so better to
    recommend developers simply configure a global core.excludesfile to
    filter the irrelevant files which tend to get created by their
    personal choice of tools.
    
    To this end, remove the long-standing sections for "Mr Developer"
    and "Editors" since their mere existence here sends the signal that
    we welcome (and have time to review) additions for any old tool
    someone ever might happen to try. Also add a comment block
    explaining this, for clarity.
    
    We can, and should of course, continue to list files created by the
    tools recommended by our workflow (test frameworks called from tox,
    documentation and packaging builds, et cetera).
    
    This change is a port of I1b41efac219fca44e2548fc36633724d0ecfc0cb
    from the openstack-dev/oslo-cookiecutter repository.
    
    Change-Id: I09a564e59c4515a67698d5c15df1d1b3d77bbc38
    
  - Fix exception raise at rpdb session
    
    Some components raise unrelated exceptions during rpdb session due to
    unaware attribute handling of file-like objects
    
    Change-Id: I04dd5a7d0f6ec2920671dfa612439427dffefd52
    Closes-bug: #1791104
    
  - Merge "Fix docstring formatting nit in uuidsentinel"
  - Merge "UUID sentinel"
  - Fix docstring formatting nit in uuidsentinel
    
    This doesn't actually appear in the docs because it's a private class,
    but if we ever made it public we want it to format the code block
    correctly.
    
    Change-Id: Ia79b58d6d7847b65f946763c82a25ce8d8e581fb
    
  - UUID sentinel
    
    Add a private _UUIDSentinels() class to oslo_utils.fixture that behaves
    like a mock.sentinel, but returns specifically UUIDs. Expose a
    (singleton) instance of it called uuidsentinel. This is mostly copied
    from [1], with the following differences:
    
    - We don't do the enforced-singleton thing [2]. But importing the
      uuidsentinel global yields the same behavior.
    - We don't do the local import thing [3][4], because we're already in
      the right lib, so no issues with circular imports.
    - Locking is added to make this threadsafe. (See discussion at [5])
    
    Note that there is some question as to whether it is more appropriate
    for this to live here or in oslotest [6]. This has been discussed on the
    dev ML [7] and it was concluded [8] that it should live here.
    
    [1] https://github.com/openstack/nova/blob/722d5b477219f0a2435a9f4ad4d54c61b83219f1/nova/tests/uuidsentinel.py
    [2] https://github.com/openstack/nova/blob/722d5b477219f0a2435a9f4ad4d54c61b83219f1/nova/tests/uuidsentinel.py#L30
    [3] https://github.com/openstack/nova/blob/722d5b477219f0a2435a9f4ad4d54c61b83219f1/nova/tests/uuidsentinel.py#L18-L19
    [4] https://github.com/openstack/nova/blob/722d5b477219f0a2435a9f4ad4d54c61b83219f1/nova/tests/uuidsentinel.py#L26
    [5] http://eavesdrop.openstack.org/irclogs/%23openstack-oslo/%23openstack-oslo.2018-08-20.log.html#t2018-08-20T20:10:33
    [6] https://review.openstack.org/#/c/594068/
    [7] http://lists.openstack.org/pipermail/openstack-dev/2018-August/133670.html
    [8] http://lists.openstack.org/pipermail/openstack-dev/2018-August/133861.html
    
    Change-Id: I214ff21b461fa1ca4b83476e1d0a763efe986217
    
  - Merge "add lib-forward-testing-python3 test job"
  - Merge "add python 3.6 unit test job"
  - Remove moxstubout usage
    
    As of oslotest version 3.5.0 moxstub will be deprecated,
    so remove it where it has been used.
    
    Change-Id: I9f038428cbea07a307f08c2251eafed7ab8bbea1
    Signed-off-by: Chuck Short <chucks@redhat.com>
    
  - Merge "Remove extra copy.deepcopy"
  - add lib-forward-testing-python3 test job
    
    This is a mechanically generated patch to add a functional test job
    running under Python 3 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I3b1472739b25ebcdd8ffbab048c611315b8f108e
    Story: #2002586
    Task: #24322
    
  - add python 3.6 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.6 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: If22b90e0b5b1b289a7657ecd5adb8f2f11401f0a
    Story: #2002586
    Task: #24322
    
  - import zuul job settings from project-config
    
    This is a mechanically generated patch to complete step 1 of moving
    the zuul job settings out of project-config and into each project
    repository.
    
    Because there will be a separate patch on each branch, the branch
    specifiers for branch-specific jobs have been removed.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I96287db07326aed08d1f3557a6c5366277701e67
    Story: #2003250
    
  - Update reno for stable/rocky
    
    Change-Id: I8346274c8dc281f18ae7938334adec6d5dd3780f
    
  - Remove extra copy.deepcopy
    
    This method is called recursively (ie deeply) by default
    so there doesn't seem to be a good reason to deepcopy over
    and over and over at every recusion level especially since
    a new output dictionary is getting created anyway.
    
    Change-Id: I644ef881e487c06dc4db77d60cfe765b0e59b547
    
  - Merge "Handle non-string keys appropriately"
  - Handle non-string keys appropriately
    
    In python dict keys can be anything that is hashable; which
    includes non-strings such as ints. Currently the code is blowing
    up with these types of keys with exceptions like:
    
    TypeError: argument of type 'int' is not iterable
    
    So to fix that handle the case where non-string keys are found.
    
    Change-Id: I4f576a089df6f68e43572bf0eee15e99f2b557fe
    
  - Switch to stestr
    
    According to Openstack summit session [1],
    stestr is maintained project to which all Openstack projects should migrate.
    Let's switch to stestr as other projects have already moved to it.
    
    [1] https://etherpad.openstack.org/p/YVR-python-pti
    
    Change-Id: Ica0262653e8c18681d049acca6d5920ac38f97e6
    
  - Add release notes link to README
    
    Change-Id: Ic64ca857fca154facbbef1e97740af52e2747834
    
  - Merge "Fix exception with secretutils"
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Change-Id: Iba35cef6449b9c40a820114d59c1c45f56946b8d
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Fix exception with secretutils
    
    1. There are some problems about the test method.
     problem 1:
      Unit tests may not cover our function, it depends on the python version
      that performed the test.
     problem 2:
      when using function 'constant_time_compare(first, second)', 'first' and
      'second' params are usually HMAC digest values, it is not appropriate to
      use utf-8 encoded values as mock data.
    
    2. The previous commit `f1d332a` lead into a bug, but due to the problem 1
       and the problem 2, we did not find out the error.
    
    Change-Id: I1c29bfe69f8eda60f3c5caaf3e5447dd5b69b108
    Closes-Bug: #1772851
    
  - Add private_key to the list of sanitized keys
    
    Nova's create keypair operation will currently log the generated
    keypair if debug logs are enabled.
    
    Closes-Bug: #1770683
    Change-Id: I7f889f0bf254fad43b1e26d32fa145f88c668b39
    
  - Remove stale pip-missing-reqs tox test
    
    pip_missing_reqs tool is no longer maintained and has broken with
    release 10 of pip
    
    Refer to:
     http://lists.openstack.org/pipermail/openstack-dev/2018-April/130027.html
    
    Change-Id: I0f9170586dc4c270df282d8f7417910eec109d78
    
  - Capitalize Oslo
    
    It's a proper name.
    
    Mostly this is just to trigger the release notes jobs again after
    they failed on release.
    
    Change-Id: I5ea88dfbad5b9d60d9b404cef4a586e92fb5a957
    
  - Trivial: Update pypi url to new url
    
    Pypi url changed from [1] to [2]
    
    [1] https://pypi.python.org/pypi/<package>
    [2] https://pypi.org/project/<package>
    
    Change-Id: I53bfd078ba2a47a5744c2ebf1354d06ad6438544
    
  - Merge "eventletutils: Fix behavior discrepency when reusing Events"
  - set default python to python3
    
    Set the default python to python3 except for the py27 environment. We
    have to set that explicitly to override the new default.
    
    Change-Id: I931fc5b5c5bd0b746e1600c93897a7551b3f559e
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - eventletutils: Fix behavior discrepency when reusing Events
    
    The threading.Event object allows calling set() multiple times, but
    the eventlet.Event object only permits send() to be called once,
    before a reset() is required to reuse the Event.
    
    Calling eventletutils.Event.set() multiple times triggers an
    AssertionError from eventlet.Event.  This change resets the underlying
    eventlet.Event if the set() method had already been called previously,
    and ensures the eventletutils.Event behaves the same as the
    threading.Event.
    
    Change-Id: If761b237266bbfe7e65c56e152074b5d1ccac74b