Updated openstack/openstack Project: openstack-infra/release-tools  46a97a63850e3ae3135e66a8b7001b81b1ada60c
Do not fail with Tox 2.3.1

Latest tox causes failures:
   File "/usr/local/lib/python2.7/dist-packages/tox/config.py", line
1140, in processcommand
       argv = list(shlexer)
     File "/usr/lib/python2.7/shlex.py", line 269, in next
       token = self.get_token()
     File "/usr/lib/python2.7/shlex.py", line 96, in get_token
       raw = self.read_token()
     File "/usr/lib/python2.7/shlex.py", line 172, in read_token
       raise ValueError, "No closing quotation"
   ValueError: No closing quotation

This is caused by a backwards incompatible change in tox:
https://bitbucket.org/hpk42/tox/issues/181

Change-Id: Iad5f7ab9f933920767fad54dc800946b0530d36c