Update git submodules
* Update tripleo-puppet-elements from branch 'master'
  - Change openstack-dev to openstack-discuss
    
    Mailinglists have been updated. Openstack-discuss replaces openstack-dev.
    
    Change-Id: Ic991ca7c22df3b60f360e6a77fe9d313d63a3bf8
    
  - Merge "Remove MongoDB"
  - Merge "[Configuration] Remove useless py26 environment."
  - Remove MongoDB
    
    It's not used and needed anywhere, let's clean this up.
    
    Change-Id: I57b5ad8c0ec375b8f00e7f3552d9e7d51e3e7707
    
  - [Configuration] Remove useless py26 environment.
    
    This environment is empty and not used.
    
    Change-Id: I0985aae12eb975c76e55c0ba2951700361d637c4
    
  - Drop baremetal job template
    
    https://review.openstack.org/#/c/619337/ switched the jobs to a noop for
    master and since this file is branched we no longer need to keep this
    template definition in this project.
    
    Change-Id: I0bca3d6403f7265458b1420a4136a2bdfed334bf
    
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Change-Id: I71287cf24200f1abb5cde0fd305647e9d31f292d
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Merge "Add python3 heat agent for Fedora"
  - Merge "Port items from instack-undercloud"
  - Add python3 heat agent for Fedora
    
    As we work on python3 support, we need to pull in the python3 heat agent
    package under fedora.
    
    Change-Id: I683c244b98bfdde53cb14960b12901872fe8bd75
    Related-Blueprint: python3-support
    
  - Merge "Remove skydive package install"
  - Port items from instack-undercloud
    
    Currently we leverage the overcloud-full and pip-and-virtualenv-override
    elements from instack-undercloud during image building. In order to
    remove instack-undercloud as a dependency, we need to move these items
    elsewhere.  Since you cannot have overlapping names, the overcloud-full
    element functionality has been moved to overcloud-base and
    overcloud-compute with the file names 50 being replaced with 51.
    The pip-and-virtualenv-override elements has been renamed to
    override-pip-and-virtualenv.  A subsequent set of patches will be posted
    to tripleo-common to remove instack-undercloud from the image building
    path and an update to the elements required when building images.
    
    Change-Id: I1de0b6421ef455ef58c0146da7fe52c35682b395
    Related-Blueprint: remove-instack-undercloud
    
  - Merge "overcloud-base: add podman"
  - Merge "Update reno for stable/rocky"
  - Remove skydive package install
    
    Change-Id: I7785eb22b34d52df6a08925250bddb0562b3c0ad
    Closes-Bug: #1788950
    
  - Update reno for stable/rocky
    
    Change-Id: I1d54ad43c727f241ff6a05411104e59e01b3ce6c
    
  - add python 3.6 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.6 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I3a8ab7bc9e11fd902ff9dcb9e9ebfd34ea4fc6b6
    Story: #2002586
    Task: #24341
    
  - add python 3.6 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.6 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Ice22c0c25404e218089f5d9d8eb0289d96442d28
    Story: #2002586
    Task: #24341
    
  - switch documentation job to new PTI
    
    This is a mechanically generated patch to switch the documentation
    jobs to use the new PTI versions of the jobs as part of the
    python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Ib6f7bbc56acd74aafaf669fb8d314fcff06dfd97
    Story: #2002586
    Task: #24341
    
  - import zuul job settings from project-config
    
    This is a mechanically generated patch to complete step 1 of moving
    the zuul job settings out of project-config and into each project
    repository.
    
    Because there will be a separate patch on each branch, the branch
    specifiers for branch-specific jobs have been removed.
    
    Because this patch is generated by a script, there may be some
    cosmetic changes to the layout of the YAML file(s) as the contents are
    normalized.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I33ad2fb50e204ec44021a78474f6fabf5f754647
    Story: #2002586
    Task: #24341
    
  - overcloud-base: add podman
    
    Add podman rpm in the image so we can start experimenting this container
    backend.
    
    Change-Id: I75e86600a6b9ec553ac3f8f1b4f3645b9eca7060
    
  - Merge "Add release note link in README"
  - Disable os-collect-config by default
    
    With the switch to config-download, os-collect-config no longer needs to
    be enabled on the overcloud nodes by default. It should be disabled to
    avoid confusion as to why it might be running, as well as so that there
    will be no accidental conflicts with config-download.
    
    Change-Id: Ideae13e2bf42f1d62196f431d443bd5e55fdcff8
    
  - Update test-requirements.txt
    
    The py27 job is failing, adding testrepository fixes it.
    
    The pep8 job is failing, updating versions for hacking fixes it.
    
    Change-Id: I59f8015a3609ca362094b63faed5819e27e271c2
    Closes-Bug: #1782005
    
  - Add release note link in README
    
    Change-Id: If37913f0d0c6c833e433670d69de5101f8767a3e
    
  - Add element for openssh and override UseDNS
    
    We need to disable UseDNS in default sshd_config, which is something we
    already do when deploying SSHD service in puppet/services/sshd.yaml but
    the parameter is still enabled before Puppet has run, which causes
    problems when Ansible has to execute remote tasks via ssh, it timeouts.
    
    This patch adds an element that will allow us to override the default
    openssh configuration and it'll disable UseDNS.
    
    Change-Id: I2df6c45936ee88e0eb048998ae23c9334f295fdf
    Related-Bug: #1774557
    
  - Merge "Remove overcloud-cinder-volume element"
  - Merge "Additional OpenStack cleanup"
  - Merge "Remove sensu, fluentd, collectd from the images"
  - Merge "Remove setup-puppet element"
  - Remove overcloud-cinder-volume element
    
    We no longer use this element and services have been converted to
    containers. We no longer support this so let's remove it.
    
    Change-Id: If5d99d4caf8d4bb81053c9105c45e822356991c8
    Related-Blueprint: cleanup-overcloud-images
    
  - Fix readme formatting issues
    
    $ python setup.py check -r -s
    running check
    warning: check: Unexpected indentation. (line 63)
    
    error: Please correct your package
    
    Change-Id: I26057e9e2f86f092e04efd3f56f7d55be937f2de
    Related-Bug: #1774001
    
  - Remove sensu, fluentd, collectd from the images
    
    These are now run under containers and shouldn't need to be installed on
    the overcloud nodes.
    
    Change-Id: Iead31484e53af416bc5ca2c40adfae7b7d4e47aa
    Related-Blueprint: cleanup-overcloud-images
    
  - Remove setup-puppet element
    
    We don't use this so let's remove it.
    
    Change-Id: I2543accce7997f7f40b54a8f7537b1e0007f5e0b
    
  - Additional OpenStack cleanup
    
    We removed Ironic, but left some additional dependencies. This change
    removes them as well as the left over vitrage packages that are no
    longer defined.
    
    Change-Id: I3d18b0770969490d999b70f16d38698651590e5f
    Related-Blueprint: cleanup-overcloud-images
    
  - Add keepalived back
    
    I5ceb329e18024040697ad5eab892d13c51ad276f removed the OpenStack and Ceph
    packages which also removed keepalived from the images. We still need
    keepalived for the controllers so adding it back in as an explicit
    package to install.
    
    Change-Id: I81b5b5bfd945ca74aec7ce8d9036c2680a5a4d1a
    Closes-Bug: #1767135
    
  - Remove Openstack and Ceph packages attempt 2
    
    As we've switched to containers, it's time to start cleaning up the
    packages we install on the overcloud images by default. This change
    removes all the openstack and ceph packages from the
    overcloud-controller, overcloud-ceph-storage and overcloud-compute
    elements.
    
    This reverts commit c69d6dd2c9d1c54d82669525bababc04b5a0688c. The
    previous attempt was reverted due to an invalid json in the overcloud
    pkg-map. This trailing comma has been addressed in this revert.
    
    Change-Id: I5ceb329e18024040697ad5eab892d13c51ad276f
    Related-Blueprint: cleanup-overcloud-images
    
  - Revert "Remove Openstack and Ceph packages"
    
    This reverts commit 9bbd394636b2caf5e3941c2ce873404402a19747.
    
    The pkg-map is broken resulting in bad images. Revert for now.
    
    Change-Id: I9303fffc0c65df50c3dc48afde8fbd3da70b16bc
    
  - Remove Openstack and Ceph packages
    
    As we've switched to containers, it's time to start cleaning up the
    packages we install on the overcloud images by default. This change
    removes all the openstack and ceph packages from the
    overcloud-controller, overcloud-ceph-storage and overcloud-compute
    elements.
    
    Change-Id: If67d59385e62fb5f8938295aae108c5dc8bb2795
    Co-Authored-By: Alex Schultz <aschultz@redhat.com>
    Co-Authored-By: Emilien Macchi <emilien@redhat.com>
    
  - Remove heat-api-cloudwatch from package install
    
    Remove heat-api-cloudwatch from package-installs-overcloud-controller.
    heat-api-cloudwatch has long be deprecated. It should be remove from package-installs.
    
    Change-Id: Ie6e62092d1d874d87ea7e54e5ef48fac77673816
    
  - zuul: add tripleo-buildimage-jobs
    
    Useful to test changes in the image.
    
    Change-Id: Id6f7a004e7bc01dede939fff1489c4e2f2476eb4
    
  - add puppet-vitrage and vitrage rpms into image
    
    Implements: blueprint tripleo-vitrage-integration
    
    Change-Id: I11ed75a3585b3f6d37a4c35ee689cf87aae94ef5
    Signed-off-by: dongwenjuan <dong.wenjuan@zte.com.cn>
    
  - Update reno for stable/queens
    
    Change-Id: I14653e9b33f3d8a2077cd432d028359a770014e8
    
  - Create element to purge resolv.conf
    
    We should be managing the network configuration with os-net-config or
    elsewhere so we should not be providing a nameserver in resolv.conf
    in overcloud images. This element will be used to ensure that the
    resolv.conf of the overcloud-full image should not contain any
    nameservers.
    
    Change-Id: If8c44137d120059b356675a074e3af23ea63a6f8
    Partial-Bug: #1749756