Update git submodules
* Update nova from branch 'master'
  - Merge "Exit 1 when db sync runs before api_db sync"
  - Exit 1 when db sync runs before api_db sync
    
    Since cells v2 was introduced, nova operators must run two commands to
    migrate the database schemas of nova's databases - nova-manage api_db
    sync and nova-manage db sync. It is necessary to run them in this order,
    since the db sync may depend on schema changes made to the api database
    in the api_db sync. Executing the db sync first may fail, for example
    with the following seen in a Queens to Rocky upgrade:
    
    nova-manage db sync
    ERROR: Could not access cell0.
    Has the nova_api database been created?
    Has the nova_cell0 database been created?
    Has "nova-manage api_db sync" been run?
    Has "nova-manage cell_v2 map_cell0" been run?
    Is [api_database]/connection set in nova.conf?
    Is the cell0 database connection URL correct?
    Error: (pymysql.err.InternalError) (1054, u"Unknown column
            'cell_mappings.disabled' in 'field list'") [SQL: u'SELECT
    cell_mappings.created_at AS cell_mappings_created_at,
    cell_mappings.updated_at AS cell_mappings_updated_at,
    cell_mappings.id AS cell_mappings_id, cell_mappings.uuid AS
    cell_mappings_uuid, cell_mappings.name AS cell_mappings_name,
    cell_mappings.transport_url AS cell_mappings_transport_url,
    cell_mappings.database_connection AS
    cell_mappings_database_connection, cell_mappings.disabled AS
    cell_mappings_disabled \nFROM cell_mappings \nWHERE
    cell_mappings.uuid = %(uuid_1)s \n LIMIT %(param_1)s'] [parameters:
    {u'uuid_1': '00000000-0000-0000-0000-000000000000', u'param_1': 1}]
    (Background on this error at: http://sqlalche.me/e/2j85)
    
    Despite this error, the command actually exits zero, so deployment tools
    are likely to continue with the upgrade, leading to issues down the
    line.
    
    This change modifies the command to exit 1 if the cell0 sync fails.
    
    This change also clarifies this ordering in the upgrade and nova-manage
    documentation, and adds information on exit codes for the command.
    
    Change-Id: Iff2a23e09f2c5330b8fc0e9456860b65bd6ac149
    Closes-Bug: #1832860