Update git submodules
* Update puppet-ceph from branch 'master'
  to 82343e1cda01952dbe2ca160dfe41e2a53dd2e12
  - setuptools: Disable auto discovery
    
    The latest release of setuptools 61.0 made a breaking change[1] and
    because of this change 'pip install' fails with the following error.
    
    ~~~
    error: Multiple top-level packages discovered in a flat-layout:
    ['lib', 'spec', 'manifests', 'releasenotes'].
    ~~~
    
    Users that don't set 'packages', 'py_modules', or configuration'
    are still likely to observe the auto-discovery behavior, which may
    halt the build if the project contains multiple directories and/or
    multiple Python files directly under the project root.
    
    To disable auto discovery, one can do below in setup.py
    
    ~~~
    setuptools.setup(..,packages=[],..)
    ~~~
    
    or
    
    ~~~
    setuptools.setup(..,py_modules=[],..)
    ~~~
    
    [1] https://github.com/pypa/setuptools/issues/3197
    
    Note setup.py is not used to install puppet modules. However it is used
    to generate a release note, thus should be fixed.
    
    Change-Id: Ibc71fa7185f7883da51db8e7aa284ddf3fa6cda8
    Co-Authored-By: Jiri Podivin <jpodivin@redhat.com>