Update git submodules
* Update nova from branch 'master'
  - Merge "fix bug with XML matcher handling missing children"
  - fix bug with XML matcher handling missing children
    
    In the XMLMatches matcher used by assertXmlEqual(), it did not
    correctly handle the case where a child element of an element <foo>
    was expected but the actual element <foo> was totally empty.  In this
    scenario, an error like the following would be generated:
    
        nova.tests.unit.test_matchers.TestXMLMatchesOrderedExtraChildren.test_describe_difference
        -----------------------------------------------------------------------------------------
    
        Captured traceback:
        ~~~~~~~~~~~~~~~~~~~
            Traceback (most recent call last):
              File ".../nova/.tox/py27/lib/python2.7/site-packages/testtools/tests/matchers/helpers.py", line 32, in test_describe_difference
                mismatch = matcher.match(matchee)
              File "nova/tests/unit/matchers.py", line 431, in match
                actual.getroot(), state, None)
              File "nova/tests/unit/matchers.py", line 520, in _compare_node
                state, actual_child_idx)
              File "nova/tests/unit/matchers.py", line 520, in _compare_node
                state, actual_child_idx)
              File "nova/tests/unit/matchers.py", line 534, in _compare_node
                actual_child_idx + 1)
            UnboundLocalError: local variable 'actual_child_idx' referenced before assignment
    
    actual_child_idx was being used when constructing the XMLExpectedChild
    XMLMismatch object, in order to indicate that the missing child was
    expected at that position in the list of XML siblings.  However this
    was only being set as a side-effect of the loop
    
        for actual_child_idx in range(...):
            ....
    
    which is brittle in general, but also specifically is guaranteed to
    break when the start and end parameters supplied to range() are equal
    - in this case actual_child_idx will not get set.
    
    While fixing this reference to the uninitialized variable, it became
    apparent that the XMLExpectedChild subclass of XMLMismatch was
    generating a slightly misleading error which claimed that the missing
    child was expected at a certain index even when the matcher was set
    with allow_mixed_nodes=True in order to not require strict ordering of
    siblings.
    
    It also became apparent that the use of a context manager for tracking
    the XMLMatchState was not appropriate, because the state was stored in
    a single object which got mutated as the XML tree was recursed, and
    this did not allow for bubbling XMLMismatch objects up the stack which
    would accurately preserve the details of the mismatch.
    
    Bearing these issues in mind, make the following changes:
    
      - Avoid the use of the potentially uninitialized actual_child_idx
        variable.
    
      - Generate a new XMLMatchState object for each layer of recursion.
    
      - When an XMLExpectedChild or XMLUnexpectedChild mismatch is
        encountered, bubble that all the way up to the caller.
    
      - Allow the idx parameter to XMLExpectedChild to be None, when
        strict ordering is not required.
    
      - Add test cases to cover these scenarios.
    
    Since comparison of XML trees is a generic task, in the future most
    likely it would make sense to remove this code from nova, and use
    an upstream alternative such as xmldiff:
    
        https://xmldiff.readthedocs.io/en/stable/
    
    Change-Id: I2dc912d4e3059ab86d414937223f766a1b893900