Update git submodules
* Update puppet-neutron from branch 'master'
  to 2ef559bd3b8f2e0dc03a0e9f26f4e1d0511a2363
  - Remove usage of deleted manifest_dir
    
    Recent update in rspec-puppet removed some of the config interfaces for
    old puppet versions[1]. This drops usage of these interfaces to resolve
    the following error in unit tests.
    
    ```
    An error occurred while loading ./spec/unit/provider/manila_spec.rb.
    Failure/Error: c.manifest_dir = File.join(fixture_path, 'manifests')
    
    NoMethodError:
      undefined method `manifest_dir='...
    ```
    
    This also removes explicit setting of mock module. The definition is
    no longer required since we bumped puppetlabs_spec_helper to v 5.0.0.
    
    [1] https://github.com/puppetlabs/rspec-puppet/commit/316d95923cdbab4daf980629cbded351dd61354c
    
    Change-Id: I46ed647264e19a463d2c0924c40da369a26f1b09