Updated openstack/openstack Project: openstack-infra/jenkins-job-builder  7169e95b0d40f5839f3d0998fd96b1f7325a189c
Fix delete-all command on python 3

raw_input was renamed to input[1] in python 3 which breaks the
'delete-all' command in python 3

failed with error:

 File "/jenkins-job-builder/jenkins_jobs/cmd.py",
    line 53, in confirm
      answer = raw_input('%s (Y/N): ' % question).upper().strip()
 NameError: name 'raw_input' is not defined

Use six to make it compatible for both python 2 and python 3.

[1] https://www.python.org/dev/peps/pep-3111/

Change-Id: I0022bc0dffc2167d11ba717b9c4ffd0c5b23db20