Update git submodules
* Update tripleo-quickstart-extras from branch 'master'
  - Bump tox minversion to 3.9 due to inline comments
    
    Current minimal required version of tox (3.4.0),
    as per tox.ini, is not compatible with inline comments.
    
    Support for inline comments in deps was added in 3.9 according to:
    - https://tox.readthedocs.io/en/latest/config.html#conf-deps
    - https://tox.readthedocs.io/en/latest/changelog.html#v3-9-0-2019-04-17
    
    E.g. there are inline comments at deps lines:
    
      [testenv:molecule]
      deps =
          ansible
          ansi2html  # GPL (soft-dependency of pytest-html)
    
    which then fails like:
    
      ERROR: Invalid requirement: 'ansi2html  # GPL (soft-dependency of pytest-html)'
    
    Change-Id: Ic1a3457a8164097b73dd906744c49171aa4cb833