Updated openstack/openstack Project: openstack/horizon  51c1f34966c36bedd1036f6a5a3ffa3e0a8cd66e
Fix unicode error when assertMessageCount() fails

When assertMessageCount() fails, we display the list of messages that
were included in the response. However because the messages are lazily
translated by default, this would fail and show the following error
instead:

 TypeError: sequence item 0: expected string, __proxy__ found

Change-Id: I1d2ed97b66428e0ee1aac783c8370ab3ea665b29
Closes-Bug: #1315031