Updated openstack/openstack Project: openstack/sahara-dashboard  55512fcc5e8d2db09896bcc55352912f8e650b08
Unbreak "setup.py install"

python setup.py install fails with:
error: can't copy 'sahara_dashboard/content/data_processing/locale':
doesn't exist or not a regular file

The symbolic link does not work with setuptools, this needs to be
handled differently. Remove for now to get requirements gate working
again as this blocks *all* changes for the requirements repository.

Change-Id: I33eb60788a8bbef40ea47b22b11dee24f198effc