Updated openstack/openstack Project: openstack/python-troveclient  b18d4ebf46725066aa5929c17cf6fb740d3301a5
Fix module-list failing with AccessInfoV2 error

Due to recent changes (not sure what) the trove module-list command
now fails while trying to determine if the client is being run as
an admin user.

The error looks like the following:

 DEBUG (shell:752) 'AccessInfoV2' object has no attribute '__getitem__'
 Traceback (most recent call last):
   File "/opt/python-troveclient/python-troveclient/troveclient/shell.py",
     line 747, in main sys.argv[1:]))
   File "/opt/python-troveclient/python-troveclient/troveclient/shell.py",
     line 562, in main args.func(self.cs, args)
   File "/opt/python-troveclient/python-troveclient/troveclient/v1/shell.py",
     line 1552, in do_module_list
        roles = cs.client.auth.auth_ref['user']['roles']
   TypeError: 'AccessInfoV2' object has no attribute '__getitem__'
   ERROR: 'AccessInfoV2' object has no attribute '__getitem__'

The code was changed so that it doesn't fail even if the structure
of the access object changes.

Change-Id: Ib0a7de0b8df359c9ad5a582bbe7afcff56d332f8
Closes-Bug: #1607428