Updated openstack/openstack Project: openstack/keystone  23825691beec824d8c6ab83c761850db22061f0b null Pin Sphinx to <1.2
1.2 was just released and has a bug that causes builds to fail with
the error:

    error: 'source_dir' must be a directory name (got `...doc/source`)

    See: http://bugs.python.org/issue19570
    and: https://bitbucket.org/birkenfeld/sphinx/pull-request/193/builddoc-shouldnt-fail-on-unicode-paths/diff

Change-Id: I0487b4eca8f2755b882689289e3cdf429729b1fb
Ref: https://review.openstack.org/#/c/61164