Updated openstack/openstack Project: openstack/cinder  dca29e9ab3cdde210d3777e7c6b4a6849447058a
Windows SMBFS: fix volume extend

The Windows SMBFS driver inherits the Linux SMBFS driver,
overriding Windows specific methods.

This commit Ic89cffc93940b7b119cfcde3362f304c9f2875df added the
volume name as an extra argument to the _do_extend_volume in order
to check if differencing images are pointing to backing files other
than the according volume disks.

Although this is not required on Windows, this method should accept
this extra argument in order to have the same signature as the
method it overrides. At the moment, this raises the following
exception:

TypeError: _do_extend_volume() takes exactly 3 arguments (4 given)

Change-Id: I868d7de4a2c68f3fc520ba476a5660a84f440bb1
Closes-Bug: #1437290