Update git submodules
* Update gear from branch 'master'
  - Merge "add missing str to bytes conversion for Python3"
  - OpenDev Migration Patch
    
    This commit was bulk generated and pushed by the OpenDev sysadmins
    as a part of the Git hosting and code review systems migration
    detailed in these mailing list posts:
    
    http://lists.openstack.org/pipermail/openstack-discuss/2019-March/003603.html
    http://lists.openstack.org/pipermail/openstack-discuss/2019-April/004920.html
    
    Attempts have been made to correct repository namespaces and
    hostnames based on simple pattern matching, but it's possible some
    were updated incorrectly or missed entirely. Please reach out to us
    via the contact information listed at https://opendev.org/ with any
    questions you may have.
    
  - add missing str to bytes conversion for Python3
    
    Using Python3, Gearman unexpectedly closed the socket with a client when typing the 'workers' command.
    
    gearman-debug.log:
        File "/usr/local/lib/python3.5/dist-packages/gear/__init__.py", line 3250, in handleWorkers
          (fd, ip, client_id.decode('utf8'),
      AttributeError: 'str' object has no attribute 'decode'
    
    Change-Id: I610bd44c76a0e52f8d4e8f24c82c636d4ebef0ae