Update git submodules
* Update openstack-ansible-os_neutron from branch 'master'
  to 5baba403377d4fa44f19d273c993651ca1492798
  - Merge "Avoid ovs restart during package upgrade"
  - Avoid ovs restart during package upgrade
    
    When installing/upgrading packages (like ovs) a race-condition may occur
    when neutron-ovs-agent tries to restore mesh while ovs is being spawning
    down. This results in errors in neutron-ovs-agent like:
    ovsdb-client: tcp:127.0.0.1:6640: Open_vSwitch database was removed
    ovsdbapp.exceptions.TimeoutException: TXN queue is full
    
    In order to prevent that we disable ablity to restart services on
    package installation/upgrade, but do that with handler after
    neutron-ovs-agent get stopped.
    
    Change-Id: I4bd717c35e030aa1ede21d9a01460037d1ab070c