Updated openstack/openstack Project: openstack/os-cloud-config  91376b7b4a17cf0c0a0e241bf7b9abc9a8f92539
use 'id' instead of 'name' for locating default domain

A fresh Keystone install creates a domain with id == 'default' and name
== 'Default'. This was causing `_grant_admin_user_roles` to fail because
it was looking for:

    default_domain = keystone_v3.domains.list(name='default')[0]

This would cause init-keystone to fail with:

    IndexError: list index out of range

This modifies the function to use the `id` attribute instead.

Change-Id: Ia6372e561a0bc8308f5f14d8c820f696b95041a4
Closes-bug: #1427760