Updated openstack/openstack Project: openstack/nova  d966d33227acfca5329beac39f86059ae1ac69ad
do not log error for missing _save_tags

The instance.save always logs the below error message if instance.tags
are lazy loaded before the save.

AttributeError: 'Instance' object has no attribute '_save_tags'

The tags should never be saved through the instance object so adding an
empty _save_tags function is better than logging an error every time.

Change-Id: Id41b06e7a294d803bd580d38ef04cc0ffb32a3bf