Updated openstack/openstack Project: openstack/neutron-fwaas  143c18d3cabe2e752af241f0689d309b15cee731
Add testresources to neutron-fwaas test requirements.

Due to https://review.openstack.org/#/c/217347/, the testresources
and testscenario are no longer part of oslo.db by default.

So when used like 'tox -e functional' the tests will fail with
  File "/opt/stack/neutron-fwaas/.tox/functional/local/lib/python2.7/
site-packages/oslo_db/sqlalchemy/test_base.py", line 17, in <module>
    import testresources
ImportError: No module named testresources
Non-zero exit code (2) from test listing.

Solution is to add to test requirements like neutron did in
https://review.openstack.org/#/c/231794/

Change-Id: Ie5fb2f83abfb0e55966da33e4755438c8e202b37