Updated openstack/openstack Project: openstack/tripleo-heat-templates  b0ba9e8e09d70cb5871a6f343a698e3b481ac297
Install mongodb client package

This resolves an error which can occur when trying to
create an overcloud without pre-built images. Specifically
mongodb replset creations fails because there is no 'mongo'
binary present:

Error: Could not prefetch mongodb_replset provider 'mongo': Could not
evalute MongoDB shell command: printjson(rs.conf())

Simply including the mongodb::client puppet class should resolve
this issue.

Change-Id: If66d3b900c61be51771f4cd0c9ea06eea62431a4
Closes-bug: #1544072