Updated openstack/openstack Project: openstack/tempest  a106c29ded8a727553af0a13a82f8d059fd9b322
Unbreak test_created_router_interface (heat)

The test become broken after 49c0fe5630d0eb8dbc95b2df8f147fa3a33830ca.
This change adds the missing variable.

The test failed with:
AttributeError: 'NeutronResourcesTestJSON' object has no attribute
'ports_client'

Change-Id: Ib5b8391ee86ce0797f2935e75c2a7e92200ee3d1