Updated openstack/openstack Project: openstack-infra/project-config  ba7325a805801fa7c49ee8122b2efc95c7333102
Fixes python 3 syntax issues with missing parentheses in call to 'print'

Original file causes jenkins-project to fail in python 3 with the
following error at L158 and L172:

   SyntaxError: missing parenthesis in call to 'print'

This patch fixes those syntax errors so jenkins-project will not fail
in python 3

Change-Id: I04ad04ac7f418effe01971253c4ea2368fcc4188