Updated openstack/openstack Project: openstack/oslo.vmware  5fef3c8cdbf76c1389cf2d74be383bbeace36ee9
Fix TypeError:six.StringIO(resp.content) must be str or None, not bytes.

in py2, using requests, type(response.conten)=unicode,
six.StringIO(resp.content) is fine. But in py3,
type(response.conten)=byte, six.StringIO(resp.content) will raise
TypeError: initial_value must be str or None, not bytes.

This patch fix it by using six.BytesIO instead of six.StringIO, which is
actually the same as six.StringIO in py2.

Change-Id: If1b910104f36b583946f62b5a4a3c4fd7e16f6c2
Closes-Bug: 1610125