Updated openstack/openstack Project: openstack/heat-specs  9f03a063ee7edb42dae25cc5e285321bd247b1d3
Updates designate spec Domain properties

Update the designate resource plugin spec to make
email property as required one and ttl property
as optional one.

designate CLI error:
 CLI : designate domain-create --name test.org
 Error: domain-create: error: argument --email is required

blueprint heat-designate-resource

Change-Id: Icaeef5afdcd7bacd2e54cb076bb5433e76f9d478