Update git submodules
* Update sahara-tests from branch 'master'
  - Revert "Revert "Temporarily disable ceilometer (currently broken)""
    
    Ceilometer integration is broken again:
    
    gnocchi.cli.manage: Upgrading indexer SQLAlchemyIndexer: mysql+pymysql://***:***@127.0.0.1/gnocchi?charset=utf8
    [...]
    pymysql.err.OperationalError: (3822, "Duplicate check constraint name 'ck_started_before_ended'.")
    
    This reverts commit afa2701268c4686245023d13df08edf293805bed.
    
    Change-Id: I3472faf2f3c2a1ab8f921bcb8a802e1461911f2d