Updated openstack/openstack Project: openstack/requirements  5c1dcc21174c8fdc5e4e0fbde37ae9fb96dcdeb6
Require iso8601>=0.1.11

python-openstacksdk uses "iso8601.UTC" which does not work in
iso8601 version 0.1.9. Running python-openstacksdk tests with 0.1.9
on python 2.7 fails with:

AttributeError: 'module' object has no attribute 'UTC'

Change-Id: I0282763a6c563277d9b176920e0dec2e07512100