Update git submodules
* Update requirements from branch 'master'
  to f78826ad9e9599ac5f17dc4a66794ee19d89d59b
  - Merge "Add 'types-paramiko' for paramiko type hints"
  - Add 'types-paramiko' for paramiko type hints
    
    This is the split out type hints for paramiko from typeshed [1]. It's
    necessary for nova to avoid the following issue:
    
      error: Library stubs not installed for "paramiko" (or incompatible with Python 3.9)
      note: Hint: "python3 -m pip install types-paramiko"
      note: (or run "mypy --install-types" to install all missing stub packages)
      note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
    
    This can be resolved by installing the hints package, as the error
    suggests.
    
    * Is the library actively maintained?
      Yes. It's part of typeshed [1].
    
    * Is the library good code?
      Yes.
    
    * Is the library python 3 compatible?
      Yes.
    
    * Is the library license compatible?
      Yes - Apache 2.0.
    
    * Is the library already packaged in the distros we target?
      No.
    
    * Is the function of this library already covered by other libraries
      in global-requirements.txt?
      No.
    
    * Is the library required for OpenStack project or related dev or
      infrastructure setup?
      Yes. It's required by nova, which uses paramiko and type hints.
    
    [1] https://github.com/python/typeshed
    
    Change-Id: I9437e48ad382c6e04a37bfe2448ad1299e72d1af
    Signed-off-by: Stephen Finucane <sfinucan@redhat.com>