Update git submodules
* Update oslo.context from branch 'master'
  to 2ce0f8fdb95d14fad31c1211b84c425e3b6740ce
  - Fix outdated argument in doc examples
    
    Currently, the example code in documentation does not run successfuly.
    - For "tenant" argument, we got:
        TypeError: __init__() got an unexpected keyword argument 'tenant'
    - For "user" argument, we got:
        DeprecationWarning: Using the 'user' argument is deprecated in
        version '2.18' and will be removed in version '3.0', please use the
        'user_id' argument instead
    
    The "tenant" argument has been removed[1] from Yoga version and the
    "user" argument is deprecated.
    
    Replaced outdated parameters in the documentation examples with
    "project_id" and "user_id" to ensure the example code runs successfully.
    
    [1] https://review.opendev.org/c/openstack/oslo.context/+/815938
    
    Change-Id: I821ec6471ae2e7b1ce9109e4d32daf6e2221a469