Update git submodules
* Update tripleo-upgrade from branch 'master'
  - fix releasenotes testenv.
    
    The release of 4.0.0 failed due to:
    
     $ tox -re releasenotes
     releasenotes create: /home/tony/projects/OSF/openstack/tripleo-upgrade/.tox/releasenotes
     releasenotes installdeps: -r/home/tony/projects/OSF/openstack/tripleo-upgrade/test-requirements.txt
     releasenotes develop-inst: /home/tony/projects/OSF/openstack/tripleo-upgrade
     releasenotes installed: aspy.yaml==1.3.0,Babel==2.6.0,bashate==0.6.0,cached-property==1.5.1,cfgv==1.6.0,flake8==2.5.5,hacking==0.12.0,identify==1.4.3,importlib-metadata==0.13,mccabe==0.2.1,nodeenv==1.3.3,pbr==5.2.
     0,pep8==1.5.7,pre-commit==1.13.0,pyflakes==0.8.1,pytz==2019.1,PyYAML==5.1,six==1.12.0,toml==0.10.0,-e git+https://opendev.org/openstack/tripleo-upgrade@39d4b47821829edbd0ad7d393262b60324f815a4#egg=tripleo_upgrade,
     virtualenv==16.6.0,zipp==0.5.1
     releasenotes run-test-pre: PYTHONHASHSEED='2527801070'
     releasenotes runtests: commands[0] | bash -c ci-scripts/releasenotes_tox.sh
     Running Sphinx v1.7.6
    
     Extension error:
     Could not import extension openstackdocstheme (exception: No module named 'openstackdocstheme')
     ERROR: InvocationError for command '/usr/bin/bash -c ci-scripts/releasenotes_tox.sh' (exited with code 2)
    
    Fix that my adding openstackdocstheme, sphinx and reno to
    test-requirements.
    
    Another solution would be to follow the PTI and have a specific
    doc/requirements.txt but that's a bigger change and probably not
    justified currently
    
    Change-Id: I96bfe4f141a587eec1d55b37a60f6b58a6009265
    
  - OpenDev Migration Patch
    
    This commit was bulk generated and pushed by the OpenDev sysadmins
    as a part of the Git hosting and code review systems migration
    detailed in these mailing list posts:
    
    http://lists.openstack.org/pipermail/openstack-discuss/2019-March/003603.html
    http://lists.openstack.org/pipermail/openstack-discuss/2019-April/004920.html
    
    Attempts have been made to correct repository namespaces and
    hostnames based on simple pattern matching, but it's possible some
    were updated incorrectly or missed entirely. Please reach out to us
    via the contact information listed at https://opendev.org/ with any
    questions you may have.