Update git submodules
* Update tripleo-heat-templates from branch 'master'
  to fc1c186310b062beea8ee8f382914dfe11d48c17
  - Merge "Do not error out when a network is ipv6 only"
  - Do not error out when a network is ipv6 only
    
    Currently with the following network definition in network-data:
    
    - name: InternalApi
      name_lower: internal_api
      mtu: 1500
      vip: true
      ipv6: true
      subnets:
        internal_api_subnet:
          ipv6_subnet: fd00:fd00:fd00:1000::/64
          ipv6_allocation_pools:
            - start: fd00:fd00:fd00:1000::50
                end: fd00:fd00:fd00:1000::90
    
    We fail as follows:
     Error rendering template /home/stack/overcloud-deploy/overcloud/tripleo-heat-templates/network/internal_api.yaml : 'dict object' has no attribute 'ip_subnet'
     Traceback (most recent call last):
       File "/usr/share/openstack-tripleo-heat-templates/tools/process-templates.py", line 97, in _j2_render_to_file
         r_template = template.render(**j2_data)
       File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
         self.environment.handle_exception()
       File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
         raise rewrite_traceback_stack(source=source)
       File "<template>", line 1, in top-level template code
       File "/home/stack/overcloud-deploy/overcloud/tripleo-heat-templates/network/network.j2", line 98, in top-level template code
         {%-     if ":" in network.subnets[subnet]['ip_subnet'] or network.ipv6|default(false) or ipv6_override %}
    
    We need to put the """if ":" in network.subnets[subnet]['ip_subnet']"""
    check after the ipv6 test. After applying this patch I was able to
    correctly deploy the overcloud.
    
    Closes-Bug: #1948834
    Change-Id: I7872f3ef926cdfd59ff19c9744052f3cc0157a1e