Update git submodules
* Update devstack from branch 'master'
  - Make PyYAML overridable on Red Hat family distros
    
    This patch fixes an early stack issue where the following error message
    would be presented:
    
    ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project
    and thus we cannot accurately determine which files belong to it which
    would lead to only a partial uninstall.
    
    We also drop references to removal of Python 2 library egg infos now
    that Python 2 is EOL.
    
    Closes-Bug: #1892363
    Change-Id: I2876ee58ab6b73682869d6b4e684e10ac5e56ad9