Update git submodules
* Update ceilometer from branch 'master'
  to 2688793b45cc5fa0db675db0377db7ad431cdfc3
  - Merge "Fix CA file for Swift pollster"
  - Fix CA file for Swift pollster
    
    Most OpenStack API communication uses the cafile option in the
    service_credentials config. For swift the client is created differently,
    and does not get this option. When TLS is used, we may get an error like
    the following:
    
    exceptions.SSLError: HTTPSConnectionPool(host='1.2.3.4', port=443): Max
    retries exceeded with url: /swift/v1/AUTH_XXXX (Caused by
    SSLError(SSLError("bad handshake: Error([('SSL routines',
    'tls_process_server_certificate', 'certificate verify failed')],)",),))
    
    This change fixes the issue by creating an HTTP connection for the Swift
    client that uses the configured CA file.
    
    Closes-Bug: #1940660
    Change-Id: I38f9ff2bec0a2a3cb9dfc5c362284e33c12f3127