Update git submodules
* Update tooz from branch 'master'
  - Fixed UnicodeEncodeError for Python2 unicode objects
    
    On python2 in case of unicode objects, str() was causing UnicodeEncodeError.
    Also utf8 encoding as a default (mostly for Python2)
    
    Change-Id: I64373133f65c5b11daa3462b7c21a55d06738c09
    
  - Merge "Change openstack-dev to openstack-discuss"
  - Unblock tooz gate
    
    We have a couple of issues blocking tooz test jobs right now. This
    is a combination of two commits that fix the problem.
    
    Cap grpcio<1.16.0
    
    1.16.0 introduces a bug that is causing our etcd3 tests to fail on
    a consistent basis. Until that is resolved we can't use any higher
    versions of grpcio.
    
    1.0.0 is used as the lower bound on the assumption that any version
    of the current major release will work. Since we weren't setting a
    bound before that seems relatively safe.
    
    Partial-Bug: 1808046
    
    Fix requirements
    
    The requirements check job is failing on a couple of the entries in
    this project. enum34 needs a lower bound, and futurist has an
    exclusion that isn't in global-requirements.
    
    enum34 is given the same lower bound as oslo.upgradecheck, and
    futurist's lower bound is increased to the last global lower bound
    (before lower bounds were removed), which eliminates the need for
    the exclusion.
    
    Change-Id: I1b279e138325b596f5ec2c61717029d2f7bdd075
    Depends-On: https://review.openstack.org/#/c/624759/
    
  - Change openstack-dev to openstack-discuss
    
    Mailinglists have been updated. Openstack-discuss replaces openstack-dev.
    
    Change-Id: I136c931dce4927c500e29205b8cddf04533f8d83
    
  - Merge "coordination: do not retry the whole heartbeat on fail"
  - Merge "Ensure consistent encoding of strings for ID"
  - coordination: do not retry the whole heartbeat on fail
    
    The current code tries to re-execute the whole _beat_forever_until_stopped
    method when it fails, whereas what it wants is only retry the driver code.
    
    The current behavior triggers an issue on interpreter shutdown:
    
      https://github.com/gnocchixyz/gnocchi/issues/979
    
    Exception in thread Thread-1 (most likely raised during interpreter shutdown):
    Exception in thread Thread-2 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
    Traceback (most recent call last):
    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    File "/usr/lib64/python2.7/threading.py", line 765, in run
    File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 250, in wrapper
    File "/usr/lib/python2.7/site-packages/tooz/coordination.py", line 186, in _beat_forever_until_stopped
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'StopWatch'
    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    File "/usr/lib64/python2.7/threading.py", line 765, in run
    File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 250, in wrapper
    File "/usr/lib/python2.7/site-packages/tooz/coordination.py", line 186, in _beat_forever_until_stopped
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'StopWatch'
    
    Change-Id: I558b89558e29c97e6d2d8036f068a593dd7540ab
    
  - Merge "Use templates for cover"
  - Use templates for cover
    
    Use openstack-tox-cover template, this runs the cover job
    in the check queue only.
    
    Remove jobs that are part of the templates.
    
    Sort list of templates and place templates as first element of project
    stanza to follow common practice.
    
    Remove all branch conditions, those are implizit.
    
    Change-Id: I458cb125bea7840b1a3931fa74929816d9ba4bd2
    
  - Migrate to stestr
    
    Change-Id: Id717f076d13f10697a7528139950a0b70d95c1c3
    
  - Fix coverage tests
    
    This project needs some special setup before running its tests, and
    that wasn't happening in the cover tox env. This switches cover to
    use the same methods for running tests as the regular test envs.
    
    Change-Id: Ie4a6543286caa11dc15173679455b2aa2020dc97
    
  - Switch to autodoc_default_options
    
    autodoc_default_flags was deprecated and is now triggering a warning
    that breaks our builds. Switch to the equivalent autodoc_default_options
    configuration, which essentially turns the flags into dict keys that
    map to None[1]: 'Setting None is equivalent to giving the option name
    in the list format (i.e. it means “yes/true/on”).'
    
    Change-Id: I573f19a054e535a90db8bb16a02b2c7f28d8e6d1
    1: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_options
    
  - Ensure consistent encoding of strings for ID
    
    Ensure that ID's are correctly binary encoded when strings are
    provided, resolving compatibility issues with Python 3.
    
    Change-Id: Ia417920a7600aacd43f17b95ecd6a34b5faa226b
    Related-Bug: 1530888
    
  - Merge "add lib-forward-testing-python3 test job"
  - Merge "add python 3.6 unit test job"
  - Merge "import zuul job settings from project-config"
  - add lib-forward-testing-python3 test job
    
    This is a mechanically generated patch to add a functional test job
    running under Python 3 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I7d517cdb8d338e4969d8cc5db69f3238b8ffd503
    Story: #2002586
    Task: #24322
    
  - add python 3.6 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.6 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Ie201d037721c6f8fac778e1234b0cfe0c27af760
    Story: #2002586
    Task: #24322
    
  - import zuul job settings from project-config
    
    This is a mechanically generated patch to complete step 1 of moving
    the zuul job settings out of project-config and into each project
    repository.
    
    Because there will be a separate patch on each branch, the branch
    specifiers for branch-specific jobs have been removed.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Depends-On: I8247a51c26dea4e8b2834b9655ffbb37b36a6af4
    Change-Id: I7e9a3124a824d00623fdbb44ece9456b0901788a
    Story: #2003250
    
  - Update reno for stable/rocky
    
    Change-Id: I2bd0a2be48eb68ecb95da210cc3b393ff6c8d31e
    
  - Add release note link in README
    
    Change-Id: I5a2a9cbc1060b847bb7459365c33d06ba8951b1a
    
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Decode the output of subprocess in doc/source/conf.py so that we always
    have a string.
    
    Change-Id: I17601d56b6e6d9d300bb07d8982a7bbde637822e
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Merge "Implement group support for etcd3gw"
  - Trivial: Update pypi url to new url
    
    Pypi url changed from [1] to [2]
    
    [1] https://pypi.python.org/pypi/<package>
    [2] https://pypi.org/project/<package>
    
    Change-Id: I8c515aa5662e020c76672a45555dfa6572267604
    
  - set default python to python3
    
    Set the default python to python3 except for the py27 environment. We
    have to set that explicitly to override the new default.
    
    Change-Id: Ib90566414f0967b2c7c7633950e3dc2fa8634982
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Implement group support for etcd3gw
    
    This adds the various methods to support groups operations on the etc3gw
    driver.
    
    Change-Id: I8acb2f617f6044449fb3a91a9c3de73ef0061d36