Update git submodules
* Update magnum from branch 'master'
  - Merge "bug: cluster creation without docker_volume_size"
  - bug: cluster creation without docker_volume_size
    
    Allows cluster to be created without docker_volume_size where we were
    previously seeing this error:
    
        TypeError: int() argument must be a string,
        a bytes-like object or a number, not 'NoneType'
    
    Regression introduced in https://review.opendev.org/#/c/695239/.
    
    Change-Id: I6e10a7fd760102040415875164d267a729c24878
    Story: 2005386
    Task: 37565