Update git submodules
* Update project-config from branch 'master'
  - Merge "Revert "Remove diskimages section from nodepool-launchers""
  - Revert "Remove diskimages section from nodepool-launchers"
    
    We seem to be having exceptions now:
    
    2018-01-18 21:15:29,955 ERROR nodepool.NodePool: Exception in main loop:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/nodepool/launcher.py", line 893, in run
        while not self._stopped:
      File "/usr/local/lib/python3.5/dist-packages/nodepool/launcher.py", line 758, in updateConfig
      File "/usr/local/lib/python3.5/dist-packages/nodepool/launcher.py", line 721, in loadConfig
      File "/usr/local/lib/python3.5/dist-packages/nodepool/config.py", line 148, in loadConfig
        p.load(newconfig)
      File "/usr/local/lib/python3.5/dist-packages/nodepool/driver/openstack/config.py", line 127, in load
        diskimage = config.diskimages[i.name]
    KeyError: 'centos-7'
    
    This reverts commit 7885d734e6de9ae0e69de75b7eaa2b4110808899.
    
    Change-Id: I43e73abac15828af1c0be514dcff3d370765f2ec