Updated openstack/openstack Project: openstack-infra/release-tools  913bd181140c606f831f7662d36bc125b072c716
Fix ImportError: No module named simplejson

Looks like launchpadlib/lazr is not installing simplejson,
so we should do this explicitly

Traceback:
  File "/Users/dims/openstack/infra/release-tools/releasetools/cmds/milestone_ensure.py", line 25, in <module>
    from launchpadlib.launchpad import Launchpad
  File "/Users/dims/openstack/infra/release-tools/.tox/venv/lib/python2.7/site-packages/launchpadlib/launchpad.py", line 33, in <module>
    from lazr.restfulclient.resource import (
  File "/Users/dims/openstack/infra/release-tools/.tox/venv/lib/python2.7/site-packages/lazr/restfulclient/resource.py", line 36, in <module>
    import simplejson
ImportError: No module named simplejson

Change-Id: Ie6486d2efcbc1853c8f7413457479509361dfeab