Update git submodules
* Update ceilometer from branch 'master'
  - Merge "Fix logging libvirt error on python 3"
  - Fix logging libvirt error on python 3
    
    This patch fixes error caused by absence of "message"
    attribute in libvirtError when running on python 3.
    ceilometer-agent-compute service fails to fetch
    domain metadata and tries to log libvirt error,
    during logging the following exception is raised and
    service fails:
    AttributeError: 'libvirtError' object has no attribute
    'message'
    
    Change-Id: I56e74d1cb30310db104c850e74b2d422d3aeb966