Update git submodules
* Update tripleo-heat-templates from branch 'master'
  - Merge "Fix haproxy firewall rules"
  - Fix haproxy firewall rules
    
    The problem we want to selve is that the change
    https://review.opendev.org/#/c/631486/ (moving iptables creation to the
    host) never really worked.
    
    The reason it never worked and we never noticed is two-fold:
    A) It ran: -e include ::tripleo::profile::base::haproxy
    the problem is that without quoting puppet basically does a noop
    
    B) Once the quoting is fixed it breaks because 'export FACTER_step'
    exports a custom fact but does not export a hiera key per-se (so calls
    to hiera('step') would fail
    
    So we add proper quoting only on the variables that are arguments to a
    parameter so that there is no risk of ansible doing the wrong thing and
    puppet gets the correct arguments.
    
    We also explicitely set the step for hiera in the deploy_steps_tasks.
    The reason we need it is because in non-HA the iptables rules would
    be created at step 1. But since the deploy_steps_tasks run before the
    actual tasks that set the step hieradata.we would get the following
    error:
    Error: Function lookup() did not find a value for the name 'step'
    
    We can just write out the step hiera key during the deploy_steps_tasks,
    it will be enforced again shortly afterwards once the
    common/deploy-steps-tasks.yaml gets invoked.
    
    We also switch back to puppet_execute: ::tripleo::profile::base::haproxy
    even for the pacemaker profile. This was broken by the flattening of the
    haproxy service (Id55ae44a7b1b5f08b40170f7406e14973fa93639)
    
    Co-Authored-By: Luca Miccini <lmiccini@redhat.com>
    
    Change-Id: Iab310207ca17a6c596470dda30a39e029c4fe09c
    Closes-Bug: #1828250