Update git submodules
* Update neutron from branch 'master'
  - PSExtDriverTestCase: initialize variable in case of exception
    
    Avoid the following when test_create_net_port_security_default
    hits an exception before variable network is set:
    
    UnboundLocalError: local variable 'network' referenced before assignment
    
    Related changes:
     - https://review.opendev.org/#/c/188209/
     - https://review.opendev.org/#/c/679399/
    
    Change-Id: I494916567a4df2bef410e8dc54505c289bd55a61