Update git submodules
* Update swift from branch 'master'
  - Merge "wsgi: Ensure _response_headers is a list"
  - wsgi: Ensure _response_headers is a list
    
    It's reasonably common that apps or middlewares may send back headers
    via dict.items(), but WSGIContext users often expect the headers to be
    a list.  Convert it for them, to avoid errors like
    
        AttributeError: 'dict_items' object has no attribute 'append'
    
    Change-Id: I4d061fad4da370c1cbb77ab78a55133319ea2dd7