Update git submodules
* Update placement from branch 'master'
  to 7e0f288dd4dab3e06f892f34839ba90600e5d360
  - Merge "Add 'cryptography' package to test-requirements.txt"
  - Add 'cryptography' package to test-requirements.txt
    
    When running the functional tests locally:
    
      tox -efunctional
    
    the following error is raised from 6 tests in the
    placement.tests.functional.db.test_migrations module:
    
      RuntimeError: 'cryptography' package is required for sha256_password
      or caching_sha2_password auth methods
    
    This adds the 'cryptography' package to the list of required packages
    for tests.
    
    Story: 2008832
    Task: 42317
    
    Change-Id: I78fbdd723be089364b8ee61432eeb74ed6f24094