Updated openstack/openstack Project: openstack/swift  61f9380225978dc51ec5a886391d06ec4f7f745e null Move test.unit.locale out of gettext's way
When I run unittests on my laptop I get an ImportError from gettext who tries
to "from locale import normalize" and says "ImportError: cannot import name
normalize".  Whit this patch unittests works, not sure why this problem
doesn't show up in my other dev environments.

Also this seems like good form since 'locale' is already a stdlib module.

Change-Id: If0fcd66ce391665b4e4127c610de3246db409a68