Updated openstack/openstack Project: openstack/nova  fe7065fa54c4be939f8e6a4fe97e7cf6db21fb76
Fix unit test failure due to tests sharing mocks

A recent refactor made test_get_port_vnic_info 2 and 3 share code
in a private method _test_get_port_vnic_info(). A mock on this method
is shared between the tests and can cause the following failure:

AssertionError: Expected to be called once. Called 2 times.

This is changed so that the two test methods create separate mocks and
pass to the shared method.

Change-Id: I3902b7b7cf4b4b3fdc2885bf2611a712d008c617
Closes-Bug: #1381414