Updated openstack/openstack Project: openstack/cinder  a3a71f99c04541fcf506b4f5611cc26d2a1b9db9
Raise NotImplementedError instead of NotImplemented

NotImplementedError is the name of the exception
(https://docs.python.org/2/library/exceptions.html).
NotImplemented is the name of a constant
(https://docs.python.org/2/library/constants.html).
>>> raise NotImplemented()
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
>>> raise NotImplementedError()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    raise NotImplementedError()
NotImplementedError

This patch fix it.

Change-Id: I6cc2123f58ca41c2bd5b23312f167867d8b0bf9d
Closes-Bug: #1339855