Updated openstack/openstack Project: openstack/keystone  e18d04b121be09a29fe9d664b8aa84ea3e87694b
Fix logging in federation/idp.py

The existing code would raise a TypeError exception:

  TypeError: Message objects do not support addition.

This is because oslo.i18n Message objects do not support the +
operator and instead require substitution to be used.

Closes-Bug: 1484735
Change-Id: I65e093808b243d8eff5b3cefdf6d64c3d7216801