Update git submodules
* Update tempest from branch 'master'
  to 12a6e1dcd3aa1b25d0d72db9a121b2e8ddcdfedd
  - Merge "Fix test_verify_tempest_config unit tests"
  - Fix test_verify_tempest_config unit tests
    
    The patch fixes:
    AttributeError: 'Manager' object has no attribute 'compute'
    thrown by the test_verify_tempest_config unit tests.
    The patch edits the failing unit tests so that they use
    a mocked Manager instead of the real one.
    
    Closes-Bug: #1918407
    Change-Id: I1fcce1ebba61ba33b1e948a80cb572f8ae17c548