Update git submodules
* Update nova from branch 'master'
  to d25de45a4b577816634612342b8fa063a08ba139
  - Merge "Reproducer for bug 2098892"
  - Reproducer for bug 2098892
    
    Change I60d6f04d374e9ede5895a43b7a75e955b0fea3c5 added tpool.Proxy
    wrapping to the listDevices() and listAllDevices() methods but
    introduced a regression for listDevices() that led to an error in
    update_available_resource():
    
      TypeError: virNodeDeviceLookupByName() argument 2 must be str or
        None, not Proxy
    
    The error was not caught by unit or functional testing because those
    test environments intentionally do not import the libvirt Python
    module -- so mocked code in the LibvirtFixture runs instead. Also, the
    update_available_resource() method has a 'except Exception:' at the end
    which logs an error but does not re-raise. So it would not cause a
    functional test to fail.
    
    This adds a functional test to reproduce the bug and adds a keyword arg
    to the test _run_periodics() method to specify whether it should raise
    an exception if an error is logged.
    
    Related-Bug: #2098892
    
    Change-Id: I3a3dda57f2181b24bd6589ac7bb8160014ab2396