Updated openstack/openstack Project: openstack/nova  54cde408413932b36518eb575c06f2a69b05d5ab
Fix bug in "nova/tests/unit/virt/test_virt_drivers.py" for os-vif

Commit 735f710 moved the os_vif.initialize() code. This lead to an
error in "test_virt_drivers.LibvirtConnTestCase.test_set_admin_password":

  AttributeError: 'module' object has no attribute 'vif

This change initializes os_vif in "test_virt_driver" as it was done
for "libvirt.test_driver" in commit 735f710.

Change-Id: Idf2fcb1df92dd4aa1761d955ea149090263d42d8
Closes-Bug: #1632987