Update git submodules
* Update tripleo-ci from branch 'master'
  - Restrict pytest-molecule to < 1.3.1
    
    With pytest-molecule==1.3.1, openstack-tox-molecule
    tests fail with:
    ImportError: cannot import name 'ansible_version'
    
    Locking the pytest-molecule until the version bug is
    addressed.
    
    Add ansible for test-requirements.tx and install
    molecule>=3.0,<3.1 so that all work toegther.
    
    Closes-Bug: #1900033
    
    Change-Id: I0eaf402066f1bb0257ea404926db6bc98ad268b9
    Signed-off-by: Chandan Kumar (raukadah) <chkumar@redhat.com>