Update git submodules
* Update os-brick from branch 'master'
  to a9a53f9b504b21d41cb0ca8c9f8739bc9444e07f
  - LUKS: Support extending host attached volumes
    
    Patch fixing bug #1861071 resolved the issue of extending LUKS v1
    volumes when nova connects them via libvirt instead of through os-brick,
    but nova side still fails to extend LUKSv2 in-use volumes when they
    don't go through libvirt.
    
    The logs will show a very similar error, but the user won't know that
    this has happened and Cinder will show the new size:
    
     libvirt.libvirtError: internal error: unable to execute QEMU command
     'block_resize': Cannot grow device files
    
    There are 2 parts to this problem:
    
    - The device mapper device is not automatically extended.
    - Nova tries to use the encrypted block device size as the size of the
      decrypted device.
    
    This patch adds new functionality to the encryptors so that they can
    extend decrypted volumes to match the size of the encrypted device.
    
    New method added to encryptors is called "extend_volume", and should be
    called after the homonymous method in the connector has been called, and
    the value returned by the encryptor's extend_volume method is the real
    size of the decrypted volume (encrypted volume - headers).
    
    The patch only adds functionality for LUKS and LUKSv2 volumes, not to
    cryptsetup volumes.
    
    Related-Bug: #1967157
    Change-Id: I351f1a7769c9f915e4cd280f05a8b8b87f40df84