Update git submodules
* Update heat from branch 'master'
  to a8fce1d09da9d241372b183206c5bb8b0411786c
  - Merge "Followup to I7736373d03c23884158e4a1d41defafb4e2b8a4c"
  - Followup to I7736373d03c23884158e4a1d41defafb4e2b8a4c
    
    that patch erroneously replaced dict.values() with dict.items(),
    and now ExtraRouteSet can not be created due to AttributeError
    ('tuple' has no attribute 'has_interface').
    
    Story: 2010142
    Task: 45778
    Change-Id: I2643b319f3a91f98097b96639f7298b25724aa62