Update git submodules
* Update python-openstackclient from branch 'master'
  to 52d56b3fd94fa66edb2a24250f3a937831cb108f
  - identity: in `service set` command, don't pass the enable option when it is None
    
    Currently, it is passing None value which is not accepted by keystone
    parameters validation:
    
    BadRequestException: 400: Client Error for url: ... Invalid input for field 'enabled': None is not of type 'boolean'
    
    Failed validating 'type' in schema['properties']['enabled']:
        {'enum': [True, False, None], 'type': 'boolean'}
    
    On instance['enabled']:
        None
    
    Closes-Bug: #2083021
    Change-Id: Ia8772560deb54e71672102157659d4eb22e6ad59