Update git submodules
* Update kayobe from branch 'master'
  to d2e0d64eb00d4cea8a4f8ff6a963b1ec0c3660ac
  - Use yoga upper constraints to avoid Python version conflict
    
    Requirements upper constraints bumped python-novaclient to version
    18.0.0 [1], which requires Python 3.8 [2]. This results in failures when
    installing python-openstackclient on CentOS and Rocky with Python 3.6.
    
        ERROR: Cannot install python-openstackclient==5.8.0 because these package versions have conflicting dependencies.
    
        The conflict is caused by:
            python-openstackclient 5.8.0 depends on python-novaclient>=17.0.0
            The user requested (constraint) python-novaclient===18.0.0
    
    Work around this issue by using yoga upper constraints until we upgrade
    to CentOS Stream 9 and Rocky Linux 9.
    
    This also fixes another issue seen on Ubuntu where image uploads to
    Glance through Ansible fail with a 400 Bad Request error. This is caused
    by the bump of openstacksdk to version 0.99.0 and will be fixed by a new
    release of ansible-collections-openstack.
    
    [1] https://review.opendev.org/c/openstack/requirements/+/842808
    [2] https://review.opendev.org/c/openstack/python-novaclient/+/838944
    
    Change-Id: I40c6b898963c2218d41d37bd73d40ce8dcf22b87