Update git submodules
* Update loci from branch 'master'
  - Merge "Remove python-qpid-proton 0.14.0 build"
  - Remove python-qpid-proton 0.14.0 build
    
    At least one distro (ubuntu xenial)
    does not have the necessary packages in its default repositories
    for building python-qpid-proton 0.14.0 (libqpid-proton2-dev doesn't provide
    the necessary qpid-proton required in the wheel build).
    
    When building the wheel, the bundling of qpid-proton fails
    due to apache mirrors having removed this old version.
    
    This prevents the newton branch to build.
    
    Example pip wheel log:
    ```
    Collecting python-qpid-proton===0.14.0 (from -r requirements.txt (line 1))
      Using cached https://files.pythonhosted.org/packages/4e/af/d39f0e805f8d76f9683d2832e456b9adffde3f56dda8ebc0eae03d2647f6/python-qpid-proton-0.14.0.tar.gz
    Building wheels for collected packages: python-qpid-proton
      Running setup.py bdist_wheel for python-qpid-proton ... error
      Complete output from command /usr/bin/python -u -c (redacted)
      running bdist_wheel
      running build
      running build_ext
      running configure
      Did not find libqpid-proton via pkg-config:
      Bundling qpid-proton into the extension
      fetching http://www.apache.org/dist/qpid/proton/0.14.0/qpid-proton-0.14.0.tar.gz into build/bundled
      error: HTTP Error 404: Not Found
    ```
    
    Change-Id: I1b3708da4cefa7e15ec5f5623e182a3258508fc7