Updated openstack/openstack Project: openstack/nova  b36eb99524e4a4f5ff83e0273b5db1b930decaa1
Fix unit test after the replace of key manager

Recently we have a new change landed to replace the key manager with
Castellan (https://review.openstack.org/#/c/309614/). This change breaks
the python unit test. If you try to run a single test without using
tox you get an error:

oslo_config.cfg.NoSuchOptError: no such option in group key_manager:
api_class

What is missing is the correct import of the keymgr module in the
conf_fixture.py file.
Please note that this error is not visible if we run the tests via tox,
probably because some test load the keymgr module making the
api_class option available for all the other tests.

To reproduce the issue try to run a single test, e.g.:
python -m testtools.run
nova.tests.unit.db.test_db_api.VirtualInterfaceTestCase.\
test_virtual_interface_create_with_duplicate_address

Change-Id: Ib735ff599b9d24be10e5f66ff3ed7711e12826f8