Updated openstack/openstack Project: openstack-infra/zuul  ded635c15a0d584c19cfb7f15d2172b39f0d26de
Merge duplicate jobs with different children

Currently this configuration:
    post:
      - searchlight-tarball
      - searchlight-tarball:
          - searchlight-pypi-both-upload

Produces this error:
       File "/home/jenkins/workspace/gate-project-config-layout/.test/zuul/zuul/scheduler.py", line 448, in add_jobs
         job_tree.addJob(layout.getJob(job))
    AttributeError: 'NoneType' object has no attribute 'addJob'

In general, duplicate jobs are silently merged, so to correct the
discrepancy, merge children of job trees into existing jobs.  With
this change, the resulting configuration will be:

    openstack/searchlight
      <Job searchlight-tarball>
        <Job searchlight-pypi-both-upload>

Change-Id: Ie731f89f12471c8268e6c2d92eaddcae9d8e125f