Update git submodules
* Update devstack-gate from branch 'master'
  - Merge "Avoid failure to install zuul when venv exists"
  - Include openstack/placement in PROJECTS starting in Stein
    
    The openstack/placement repo is required for devstack/grenade
    runs starting in Stein so this adds a conditional based on the
    branch to include the openstack/placement repo in the default
    PROJECTS list.
    
    Needed by https://review.openstack.org/604454/
    
    Depends-On: https://review.openstack.org/608266/
    
    Change-Id: I71cffffc88c329052c4067d6a9406f42856c69c6
    
  - Merge "Update grenade settings for stable/rocky"
  - Update grenade settings for stable/rocky
    
    Depends-On: https://review.openstack.org/600196/
    
    Change-Id: I940a705d4b8269fbf3bec9f107f179e9191b5a42
    
  - Bump ansible to latest 2.5 version
    
    This is the same version run by zuul.
    
    Update devstack callback for ansible 2.5.
    
    Change-Id: Ic0d2559346570e60025838166b9bd0081eee331a
    Signed-off-by: Paul Belanger <pabelanger@redhat.com>
    
  - Merge "Add gate job for stable/rocky"
  - Import legacy-dg-hooks-dsvm job
    
    This job is used only by devstack-gate, import it.
    
    Rename it to devstack-gate-hooks following our naming policy.
    
    Change-Id: Id01d7cda5cb28b6371bdcf8b85208135caa9e9b1
    
  - Add gate job for stable/rocky
    
    Now we have stable/rocky branch ready for devstack
    and so does for all service projects.
    
    This commit adds the stable/rocky job running for
    d-g gate.
    Depends-On: https://review.openstack.org/#/c/596279/
    
    Change-Id: I7ab1b7042808cce0d89cb2bcfc87c718543718b4
    
  - Merge "Remove support for devstack exercises"
  - Avoid failure to install zuul when venv exists
    
    Fixes case where a succesfull creation of the
    virtualenv but failure to install zuul would
    make the function useless as it would always
    miss installing zull.
    
    Change-Id: Ie5ef82765120094e8147b05443626e2012273fba
    
  - add rocky branch to features.yaml
    
    This patch adds the rocky branch to features.yaml so that rocky branch
    patches can land, for example [1] that currently fails with:
    ERROR: branch not allowed by features matrix: rocky
    
    [1] https://review.openstack.org/#/c/584078/
    
    Change-Id: I235c6c3ad81dff916a65cf8b97152621812fa102
    
  - Remove support for devstack exercises
    
    These seem to be not run for quite some time and they don't
    succeed anymore - drop the code to avoid somebody accidentally
    running it and wondering. A good example of "if it isn't tested
    its broken".
    
    Needed-By: https://review.openstack.org/#/c/581377/
    
    Change-Id: I68d7099e6f5be502f8a578818b5e2e4c82889c15
    
  - Dynamically determine overlay MTU
    
    Some clouds we run on no longer have MTUs of 1500 on their interfaces
    and are smaller. We dynamically determine the MTU we should use on the
    overlay networks. List all "real" interfaces with a permament mac addr
    then use the smallest MTU less 50 bytes for vxlan overhead.
    
    We only consider "real" interfaces so that we can run this multiple
    times for separate overlays without perpetually decreasing the MTU due
    to finding the lower MTU we just configured.
    
    Change-Id: If163bf211570e690e255cc3ef6888d9e0cba19b5
    
  - Cap cmd2 to < 0.9.0
    
    cmd2>=0.9.0 now require python3.4 or greater. We install ansible under
    python2 (for now) so we need to cap the cmd2 install to make the ansible
    installation function.
    
    Upstream bug at https://github.com/python-cmd2/cmd2/issues/421
    
    Change-Id: I5ec830e092646a3626cacea264de9ad81fcdd124
    
  - Merge "Grant tempest user access to virt-filesystems"
  - Remove retired tripleo-incubator from PROJECTS list
    
    tripleo-incubator has been retired so we don't cache it on our images
    but if it is in the PROJECTS list we will attempt to rsync it. Just
    remove it as it is no longer used.
    
    Change-Id: I3ad57d247a02881ba8a6757f2a058d03884eaf35
    
  - Merge "Remove setting of ETCD_DOWNLOAD_URL"
  - Remove setting of ETCD_DOWNLOAD_URL
    
    Adding ETC binaries was a stop gap measure until packages were
    available.  With the impending release of bionic that'll be soon :)
    
    Also using the mirror on tarballs.o.o was unreliable so these binaries
    are cached in the nodepool images as described in[1].  Having this
    setting in d-g makes more work than is needed in the near term.
    Removing it does introduce a new failure mode if an etcd version is
    used in devstack but not yet cacched in the image.
    
    [1] http://lists.openstack.org/pipermail/openstack-infra/2018-March/005871.html
    
    Change-Id: I2a6649ae3094ca65aa31798ee9bddf2fcdd49260
    
  - Fix bashate "local hides exit status" warnings
    
    Promote "local hides exit status" (E042) to error and fix issues found
    (this is inline with what we do in devstack).
    
    Change-Id: Idd784af066db80bb67792da3dd0aa0ae4c8475db
    
  - Merge "Revert "Work around cffi install error""
  - Merge "Add stable/pike Tempest bitrot job"
  - Add stable/pike Tempest bitrot job
    
    Replace the legacy stable/pike tempest bitrot job with the new
    zuulv3 one. The removal part will be done in a separate patch
    since it's in a different project.
    
    Change-Id: I180cd65e934c15b33975e65a9ece1d1f48fd851c
    
  - Add neutron-tempest-plugin-api job
    
    The old tempest tests have been removed from the neutron repo, so
    legacy-neutron-dsvm-api doesn't run anything at all anymore. Use the new
    api job from the neutron-tempest-plugin repo instead.
    
    Change-Id: I2d1854109474cee1923b9bffd75c3224a6f2b4bf
    
  - Merge "Handle stestr execution for stackviz"
  - Merge "Handle a stestr results directory"
  - Merge "Add stable/queens integration checks"
  - Return a proper boolean True instead of a 'True' string
    
    The type here is important, returning anything other than a boolean
    has unintended consequences such as breaking Ansible callbacks because
    they are expecting the "changed" field to be nothing other than a bool
    by contract.
    
    Change-Id: Ia9b4a749f64adae8969fd9ad66304d013013e056
    
  - Add stable/queens integration checks
    
    New jobs for d-g can be defined in the local .zuul.yaml as opposed
    to project-config. These jobs prevent ensure changes to d-g to not
    break stable/queens.
    
    Depends-on: https://review.openstack.org/521888/
    Change-Id: I547591607a7726bdef3c3953df9e0bd1c67f3423
    
  - Merge "Update grenade settings for stable/queens"
  - Update grenade settings for stable/queens
    
    Change-Id: I2709f5527552fd4fc406f870ef35c4b6e4b9dae9
    
  - Check for virtualenv binary
    
    The current check looks for a virtualenv package; but this isn't
    portable to other platforms.  In the gate we also have installed from
    upstream (to ensure latest) and the package might be on hold, etc
    which might mess up the detection.
    
    I think the KISS thing to do is to check for virtualenv and fail with
    a useful message.
    
    Change-Id: Icf15ddd18ca52885f5c4a89a7d83622a70c811d5
    
  - Zuul: Remove project name
    
    Zuul no longer requires the project-name for in-repo configuration.
    Omitting it makes forking or renaming projects easier.
    
    Change-Id: Ifd621431bfb925e8a6f0df013ddbe7cd7ed5c1e7
    
  - Remove tempest-lib
    
    tempest-lib was reintegrated into tempest in 2016, there's no need to
    check it out anymore. Remove it from PROJECTS list.
    
    See also
    https://specs.openstack.org/openstack/qa-specs/specs/tempest/implemented/reintegrate-tempest-lib.html
    
    Change-Id: I3ed33ad9cf4097bc48ab71a666c2ce95b26c3329
    
  - Set up stable/queens
    
    Change-Id: I505bb7f7d226845e96a815a34a548ceacee65517
    
  - Merge "Remove run-tests and py3-run-tests"
  - Merge "Fix setup_project checking out eol with branch name"
  - Handle stestr execution for stackviz
    
    This commit makes to handle a stestr execution for stackviz process.
    Tempest is now in the process of switching the tempest run command to
    use stestr internally instead of testrepository. This means that results
    will be stored in .stestr instead of .testrepository. So, this commit
    makes to handle a stestr or testrepository execution with checking which
    directory exists before attempting to process the subunit results.
    
    Change-Id: Ib19d3779deb89142e95762794dd1ce3fe3236b55
    
  - Handle a stestr results directory
    
    Tempest is in the process of switching the tempest run command to use
    stestr internally instead of testrepository. This means that results
    will be stored in .stestr instead of .testrepository now. This commit
    updates the post-processing function to check which directory exists
    before attempting to copy the subunit results.
    
    Change-Id: I3855aad5ce129ec8ccb87c05f7aa709b74070efe
    
  - Remove run-tests and py3-run-tests
    
    We have standard jobs for doing unittests under python2 and python3 -
    namely, the builtin tox environments py27 and py35. Just use those and
    remove the locally defined jobs.
    
    Depends-On: I6d7a96adf5cfb075f5a2ffbd089ccbb883a1c1b4
    Change-Id: I0cc0c07daafba331a64861c134029e443ba2aa8d
    
  - Move commands to the base testenv
    
    This should allow py27 and py35 to both work in parallel while we remove
    the run-tests versions.
    
    Add the new jobs here, even though the next patch will remove them,
    since we can't verify the new jobs work with depends-on to
    project-config.
    
    Change-Id: I78cfadf5a3b9822ce32f5a1d9b76321d573618ab
    
  - Import tox jobs
    
    Import the tox jobs and convert them to Zuul v3.
    
    Change-Id: Idcdc8d4508fa8d7746b3ba094d0bd96410007ef1
    Needed-By: I6d7a96adf5cfb075f5a2ffbd089ccbb883a1c1b4
    
  - Create a test matrix role
    
    Modify test-matrix.py so that is can be used as an ansible module.
    Add a role in d-g that runs test matrix for the given branch,
    role and features file.
    
    Change-Id: Ie36ba0cd7cfcd450b75000a76a64d856f2a83eba
    
  - Fix setup_project checking out eol with branch name
    
    A recent change to devstack-gate to enable falling back to EOL tags for
    zuulv2 has a bug in it where it will try to checkout the stable/branch
    instead of the converted eol tag. This patch addresses that issue.
    
    Change-Id: I23330884da09befc3bca10973cbfd2ea9b666430
    
  - Merge "Use = for string comparisons"
  - Add fallback to -eol tag if stable branch doesn't exists
    
    In order to support continued testing against EOL version of projects,
    the setup_project function needs to be able to understand checking out
    to an eol tag.
    
    Change-Id: I1b2d030df8cb2a850bf9248595171d96a813d381
    
  - Use stackviz tarball from cache directly
    
    The stackviz tarball used to be copied along with other devstack
    files in devstack space, but it's not anymore since
    1a49f65dd9509d27fcddfa7f9526d12c4889e68c.
    
    There's actually no point in moving that tarball around, so just
    use it from its original cache location directly.
    
    Change-Id: I602507648e17a7d8d06d8f541ba0918b3b972723
    
  - Checkout from -eol tag if stable branch does not exist
    
    Since several projects stable/newton branches have been end of life'd,
    we can't install base devstack on stable/newton.
    
    This modifies the setup_workspace function to check, as a last resort,
    if the base_branch is a stable branch and if there is a corresponding
    -eol tag, to use that for the checkout rather than the stable branch.
    
    This is needed in the cases that projects are end of life'd out of order,
    as is the case with keystone, cinder and neutron being end of life before
    nova for stable/newton.
    
    Co-Authored-By: Eric Fried <efried@us.ibm.com>
    
    Change-Id: I344d8fdded9b7d5385fcb41b699f1352acb4cda7
    
  - Revert "Work around cffi install error"
    
    This reverts commit e473fdec13445191d1acf1c77d19c87bbda512c8.
    
    Change-Id: Iff8d3c4b8f514bd66649cc7c4f788302af32cbc4
    
  - Don't set CEILOMETER_BACKEND in localrc
    
    mysql backend is not supported anymore. default is
    gnocchi.
    
    Change-Id: I2d1e31e386a2576b3a44ec5b8e15dc49d2a474d3
    
  - Remove v3 devstack job
    
    In preparation for moving to the devstack repo.
    
    Change-Id: Ie2119f24360d56690ffd772b95a9ea6b98dd4a39
    
  - Stop it with the moving then copying of cache files
    
    Originally, for snapshot images and in early dib days, files were
    cached into ~/cache/files (~ being jenkins).  Thus the original
    copying of files from ~/cache/files to $DEST/cache/files, introduced
    with 25ba5c9bce825106b25cf4d8a64f76a1e604a92c, was to move these files
    from here into the devstack checkouts.
    
    However, when we were converting away from puppet for image builds, we
    found that we do this caching very early; before the jenkins user is
    created even -- so having the homedir populated was causing issues
    creating the user.  Thus we moved the devstack cache to
    /opt/cache/files (Ibca6867f29b257a5110cb5522a5cca3a97fa9377)
    
    This copy probably should have been removed at this point.  However,
    since we also added back the ~/cache/files symlink this continued to
    work.
    
    Thus this removes the unnecessary copy out of ~/cache/files and links
    the files into the devstack checkouts directly from /opt/cache/files
    
    Change-Id: I35f76c59d894b00d9544b82a2d8cdcd7f526f243
    
  - Use = for string comparisons
    
    Change I384e4c376076051e7a4a8b2d704107cbe3ac08ad introduced
    comparisons of $DEVSTACK_PROJECT_FROM_GIT against a couple of
    hardcoded string values in a bash [[ ]] expression, but incorrectly
    used the -eq integer comparison operator. This seems to work under
    normal circumstances, but actually breaks if the string value of the
    variable contains a "." since the equivalence test tries to fail
    early if it detects what it thinks is a float value (because it's
    intended only for integers). Instead of -eq use = for string
    comparisons here, because that's what the POSIX test(1) utility
    mandates.
    
    Change-Id: If33d7aea9142e650b57c0f58c14e2a4434e30bf0
    
  - Work around cffi install error
    
    cffi-1.11.1 was released without wheels so we cannot install it because
    of missing libraries. Install 1.11.0 as a workaround.
    
    Change-Id: I6e0eab8e6ea126eec4c2c0767229cb915338e486
    
  - Check for branches in zuulv3 git repos properly
    
    Zuulv3 git repos do not have remotes. git_has_branch checks if the
    branch exists in the origin remote which does not exist so all branch
    specific checkouts were falling back to master which caused job
    failures.
    
    Instead just check if the base branch name exists in the repo as that
    existing in a zuulv3 repo is sufficient to know we are up to date.
    
    Depends-On: I110879bac5d8a671d73fab906ffbcf8156b1135d
    Change-Id: Ifcae3ff217259926a8950f6da83212ee311002b2
    
  - Remove manually added legacy-tempest-dsvm-neutron-full
    
    Change-Id: I72687a56285a3d733a9adeaf3dc037a1ac95efd3
    
  - Merge "Don't double-quote the rsync options"
  - Merge "Remove devstack-legacy base job"
  - Merge "Zuul v3: export devstack journal"
  - Merge "Zuul v3: Save devstack log"
  - Don't double-quote the rsync options
    
    We need to quote for yaml. If we do, it works.
    
    Change-Id: I7d208d3799205402254c0e023104a3a69adb2b46
    
  - Remove devstack-legacy base job
    
    We added it to openstack-zuul-jobs so we can use it as a base job in
    the migration.
    
    Use the results of the migrated
    gate-tempest-dsvm-neutron-full-ubuntu-xenial to test that the base job
    will work for migration purposes.
    
    Depends-On: I3ff2b486702fed9342097cdcd30ffa0c043bdecc
    Change-Id: I34514c2c38d2121c6b6fbca7e83bd273f2ec49f0
    
  - Zuul v3: export devstack journal
    
    Change-Id: I2d9b25f12de09a99f140cdb7cb7ec3f23fef0a34
    
  - Zuul v3: Save devstack log
    
    Change-Id: I2ec4d620e34303e26a231ed000b1e5e7b8141ff8
    
  - Create stack home folder
    
    The create stack user role creates the home for the stack user,
    which works as long as the containing folder already exists.
    Since this may not always be the case, create the folder first.
    
    Change-Id: Ibe3539a738340d6e4d95e3661bca5e2067e3e959
    
  - Grant tempest user access to virt-filesystems
    
    Access to /usr/bin/virt-filesystems is required by ironic tests
    to check that partitioning table was removed from VM after cleaning.
    
    Related-Bug: #1523640
    Change-Id: I7335638e513f066069672772ba0d9171b66ec710