Update git submodules
* Update puppet-reviewday from branch 'master'
  - Replace openstack.org git:// URLs with https://
    
    This is a mechanically generated change to replace openstack.org
    git:// URLs with https:// equivalents.
    
    This is in aid of a planned future move of the git hosting
    infrastructure to a self-hosted instance of gitea (https://gitea.io),
    which does not support the git wire protocol at this stage.
    
    This update should result in no functional change.
    
    For more information see the thread at
    
     http://lists.openstack.org/pipermail/openstack-discuss/2019-March/003825.html
    
    Change-Id: Iae9cb7f3fdd8fb5c0bcb1112aa4eca9f3430193f
    
  - Merge "Don't create reviewday subdirectory"
  - Merge "Add beaker tests"
  - Merge "Fix exec idempotency"
  - Don't create reviewday subdirectory
    
    Perhaps because of the new resource ordering algorithm, on puppet 4 the
    /var/lib/reviewday/reviewday file resource blocks the
    /var/lib/reviewday/reviewday vcsrepo resource and results in failures
    like:
    
     Error: /Stage[main]/Main/Reviewday::Site[reviewday]/Vcsrepo[/var/lib/reviewday/reviewday]/ensure: change from absent to latest failed: Could not create repository (non-repository at path)
    
    On both puppet 3 and puppet 4 the vcsrepo resource will create the
    directory on its own, and it can also manage the directory's owner and
    group itself, so there is no need for it to be managed independently.
    
    Change-Id: Ic64d39a9f257d623ca13e9d38708eaa1e32e8c18
    
  - Add beaker tests
    
    Add basic tests to ensure the manifests can be applied cleanly and the
    site comes up.
    
    Change-Id: Id477b53849f6efd9715f89ca54eaa899fe08c90f
    
  - Update Gemfile for Zuulv3
    
    The logic in the Gemfile was relying on Zuulv2 variables to find out
    whether the spec helper gem was already available on disk, and since
    Zuulv3 has changed things it was failing to find it and downloading the
    master version instead. This patch ensures the Gemfile looks for the gem
    in the right place when running in CI.
    
    Change-Id: Ib85eddeda99d5fc2422a8b7b994cb79e835d1f4a
    
  - Fix exec idempotency
    
    The install-reviewday-dependencies exec doesn't need to be executed on
    every puppet run, only when the source repo is updated, so add a
    refreshonly => true to ensure it only reacts to changes in the source
    repository.
    
    Change-Id: Id3a747e49416398e3fdde9aeb843370890dbe572