Update git submodules
* Update openstack-helm from branch 'master'
  to b64e92afd05a34103cd3debd19d18270effeb5b3
  - Merge "Fix 'tox -e releasenotes'"
  - Fix 'tox -e releasenotes'
    
    Running 'tox -e releasenotes' fails with:
    
    ERROR: You must give at least one requirement to install
    
    Added missing doc/requirements.txt dep to tox.ini
    
    Trivialfix
    
    Change-Id: I174460a0c1f4616cbdcb78bb8682adfe894f4206