Updated openstack/openstack Project: openstack/neutron-fwaas  8a86782c229537ab430cac87b5df63a9ddd5424c
Fix tempest gate issue on FirewallNotFound exception

In case of failed tests the following error appears in
logs/screen-q-svc.txt.gz

  File "/opt/stack/new/neutron-fwaas/neutron_fwaas/db/firewall/v2/firewall_db_v2.py", line 805, in delete_firewall_group
    raise fw_ext.FirewallNotFound(firewall_id=id)
AttributeError: 'module' object has no attribute 'FirewallNotFound'

This exception doesn't exists anymore.
It has been replaced by FirewallGroupNotFound exception.

Closes-Bug: #1649703
Closes-Bug: #1657299
Change-Id: If97ae00f66479177f50be15361bce9e8c89afc3c