Updated openstack/openstack Project: openstack/horizon  b11d2ae32ffb1301adf2500da2002dfede45f9df
Fix row updates for tables without quicksearch filtering.

Some tables do not have quicksearch filtering enabled (such as
Admin:Images). For these tables, row updates fail because of an
undefined reference to quicksearch.

This patch fixes this issue so that row update can continue to occur by
checking that quicksearch exists before invoking the cache method.

Change-Id: I4afc429ec6009840d1e793cb427a86b88dce53b6
Closes-bug: #1309268