Update git submodules
* Update kolla-ansible from branch 'master'
  - Merge "Fix kolla-docker possible undefined variable"
  - Fix kolla-docker possible undefined variable
    
    It is possible to reference undefined variable in kolla-docker module if
    DockerWorker object initialization fail, so the current behaviour will
    crash the playbook with the unwanted error message :
    
    UnboundLocalError: local variable 'dw' referenced before assignment
    
    Change-Id: Ic8d26b11f93255220888b5406f8ab4a6f81736c2
    Closes-Bug: #1819361