Updated openstack/openstack Project: openstack/openstack-doc-tools  e115fee6a3e30e897db6ab667c016f96c470dd2c
safe get deprecated_reason

when run ./autohelp-wrapper rst aodh, it failed with:
AttributeError: 'BoolOpt' object has no attribute 'deprecated_reason'

we need to check the value before we use it

Change-Id: I362606ba186d1582f850bfa4d602503d6ea5079a
Closes-Bug: #1573953