Update git submodules
* Update jenkins-job-builder from branch 'master'
  - Merge "Give an explicit error message when unsupported view type used"
  - Give an explicit error message when unsupported view type used
    
    When specifying a view type that isn't supported by any modules (such as
    "list-view" instead of "list"), this ensures that the user is guided
    towards something correct.
    
    This changes the error message in this case from:
    
    AttributeError: 'NoneType' object has no attribute 'name'
    
    to:
    
    jenkins_jobs.errors.JenkinsJobsException: Unrecognized view type: list-view (supported types are: list, pipeline)
    
    Change-Id: I0ee800db1c9c8aeecffcf11f1e86c03ba0590da8