Update git submodules
* Update puppet-qdr from branch 'master'
  to 2f71846a72f28a267f82abd347f4a46d982a4d9b
  - Remove usage of deleted manifest_dir
    
    Recent update in rspec-puppet removed some of the config interfaces for
    old puppet versions[1]. This drops usage of these interfaces to resolve
    the following error in unit tests.
    
    ```
    An error occurred while loading ./spec/unit/provider/manila_spec.rb.
    Failure/Error: c.manifest_dir = File.join(fixture_path, 'manifests')
    
    NoMethodError:
      undefined method `manifest_dir='...
    ```
    
    [1] https://github.com/puppetlabs/rspec-puppet/commit/316d95923cdbab4daf980629cbded351dd61354c
    
    Change-Id: Ia27615c204ce4c2004f4cfe7bea8ffa6b5ca325c