Update git submodules
* Update nova from branch 'master'
  to df8e0335fa978b952b580f37c301c0867f797508
  - Merge "Handle "no RAM info was set" migration case"
  - Handle "no RAM info was set" migration case
    
    This handles the case where the live migration monitoring thread may
    race and call jobStats() after the migration has completed resulting in
    the following error:
    
        libvirt.libvirtError: internal error: migration was active, but no
        RAM info was set
    
    Closes-Bug: #1982284
    Change-Id: I77fdfa9cffbd44b2889f49f266b2582bcc6a4267