Update git submodules
* Update charm-trilio-data-mover from branch 'master'
  - Fix ceph-relation-changed error
    
    TypeError: 'str' object is not callable
    After recent interface change
    
    Func-Test-Pr: https://github.com/openstack-charmers/zaza-openstack-tests/pull/400
    Change-Id: I7a45b1ffe7d71bd44201a72510d6b56a1e1a4824
    Closes-Bug: #1893445