Update git submodules
* Update oslo.policy from branch 'master'
  to 9673a74b600cd387aa3d13a6ff923c06c304c55a
  - Only pass exclude-deprecated when True
    
    The '--exclude-deprecated' parameter should only be passed to
    oslo.config to parse when it is True.
    The final generated sphinx syntax is[1] where [--exclude-deprecated]
    doesn't require True/False value and only should be passed when True.
    
    The change introducing this[2] causes parsing issue in oslo.config[3]
    while checking <bool>.startswith (we pass True/False value) and even
    after that while calling argparse[4] with following error[5].
    
    [1] usage: sphinx-build [-h] [--config-dir DIR] [--config-file PATH] [--exclude-deprecated] [--format FORMAT] [--namespace NAMESPACE]
                            [--noexclude-deprecated] [--output-file OUTPUT_FILE]
    [2] https://review.opendev.org/c/openstack/oslo.policy/+/830514
    [3] https://opendev.org/openstack/oslo.config/src/branch/master/oslo_config/cfg.py#L2937
    [4] https://opendev.org/openstack/oslo.config/src/branch/master/oslo_config/cfg.py#L2960
    [5] > /usr/lib/python3.8/argparse.py(1781)parse_args()
    -> if argv:
    (Pdb)
    > /usr/lib/python3.8/argparse.py(1782)parse_args()
    -> msg = _('unrecognized arguments: %s')
    (Pdb)
    > /usr/lib/python3.8/argparse.py(1783)parse_args()
    -> self.error(msg % ' '.join(argv))
    (Pdb)
    TypeError: sequence item 0: expected str instance, bool found
    > /usr/lib/python3.8/argparse.py(1783)parse_args()
    -> self.error(msg % ' '.join(argv))
    Handler <function generate_sample at 0x7fc0d6697d30> for event 'builder-inited' threw an exception (exception: sequence item 0: expected str instance, bool found)
    
    Closes-Bug: #1970725
    Change-Id: I95745b8d1cbdb6a7cf442d431a998b7e3ff600e4