Update git submodules
* Update cinder from branch 'master'
  to a8b60a32cc0aca249a6e4cd74c2fd89ec8a4996c
  - Merge "Add correct mock for rados.Error"
  - Add correct mock for rados.Error
    
    This only impacts the ceph backup driver when running unit tests. Python
    complains if an exception is raised that doesn't inherit from the
    BaseException class.  This patch adds the proper mocks so we don't see
    errors like the following:
    
        File "..backup/drivers/ceph.py", line 348, in _connect_to_rados
            except self.rados.Error:
        TypeError: catching classes that do not inherit from BaseException is not allowed
    
    Change-Id: I051977f48c1ebd39f0d42801ca5ffcbb333cdd9f
    Signed-off-by: Jon Bernard <jobernar@redhat.com>