Updated openstack/openstack Project: openstack/heat  3b5eea65be27b9184e2d16131e236d1cb1fb7209
Use EntityNotFound instead of ImageNotFound

There are too many **NotFound exception classes defined
in exception.py. This patch will define a general notfound
exception: EntityNotFound. And will use it instead of
ImageNotFound exception.

Change-Id: I2a09637be97905548b29673273e8579c69d42d52
Closes-Bug: #1461343