Updated openstack/openstack Project: openstack/oslo.messaging  f2cd28e503b4cd8648627493fce1736e01fa86c1
rabbit/qpid: remove the args/kwargs from ensure()

Having an *args list following the retry kwargs just screams:

  SyntaxError: non-keyword arg after keyword arg

but we don't actually pass any args to methods invoked via ensure() so
these are just unused and can be removed. If we did want them in future
we could just use functools.partial().

Change-Id: Idef12bbc94d39c84ee06ddd6d743f3d2f705a8d1