Update git submodules
* Update oslo.log from branch 'master'
  - Clarify some config options
    
    current help message to log-config-append is a bit misleading:
    if the extra logging config is using oslo_log's ContextFormatter
    as formatter for some handler, the logging_context_format_string
    option and the like do in fact still apply.
    
    Instead, give the `log-date-format` as example option that does apply
    when log-config-append is enabled and clarify that some options
    are used with ContextFormatter only.
    
    Change-Id: I917cdf8799ac0fb5b49873d5c7bccd957a42f347
    
  - Use template for lower-constraints
    
    Small cleanups:
    
    * Use openstack-lower-constraints-jobs template, remove individual
      jobs.
    * Sort list of templates
    
    Change-Id: I8270e6d25a19320bc3c854dfcf56379c52aeec53
    Needed-By: https://review.openstack.org/623229
    
  - Merge "Fix handling of exc_info in OSJournalHandler"
  - Default oslo.policy logging to INFO
    
    As of change https://review.openstack.org/619260/ to oslo.policy
    a lot of information is logged at debug for every policy check,
    which gets to be a lot of information in something like the
    nova-api logs which does a policy check per API request. So this
    change makes the default log level INFO for oslo.policy.
    
    Change-Id: Ie4a114219a69390efd148b705fad05fd8b9a42de
    Related-Bug: #1807747
    
  - Merge "Advancing the protocal of the website to HTTPS in usage.rst."
  - Merge "Fix up nits in log rotation change"
  - Update mailinglist from dev to discuss
    
    openstack-dev was decomissioned this night in https://review.openstack.org/621258
    Update openstack-dev to openstack-discuss
    
    Change-Id: Ia42def2fb8ccb5dc91ca0403511e2e30fc9081ab
    
  - Fix handling of exc_info in OSJournalHandler
    
    exc_info is exception tuple not intended to be printed. It's using to
    generate output by logging.Formatter().formatException() instead.
    exc_text used to cache this output. So we use handler formatter to get
    string from exc_info and send it as EXCEPTION_INFO. EXCEPTION_TEXT is
    kept for backward compatibility.
    
    Also adds type validation for journal.send fields to unit tests. Known
    types could be gotten from journal.DEFAULT_CONVERTERS. The rest payload
    must be either a string or bytes.
    
    Change-Id: Idc0b9edc61b4ec39dc9df0ea8282cc104e4d83c0
    Closes-Bug: 1802142
    
  - Fix up nits in log rotation change
    
    Just a couple of doc things that became out of date due to some
    code changes during the review process.
    
    Change-Id: I5820f7940d8d32546174da132db5be5a209a2200
    
  - Add config options for log rotation
    
    On Windows, in-use files cannot be moved or deleted. For this reason,
    we need the service itself to take care of rotating logs.
    
    For convenience reasons, we're exposing the built-in rotating log
    handlers through a set of config options.
    
    More specifically, we're adding the following new config options:
    - log_rotate_interval
    - log_rotate_interval_type
    - max_logfile_count
    - max_logfile_size_mb
    
    Change-Id: I01db4efc08e2cb64db9cbf793f3a159f54859fe7
    Closes-Bug: #1802262
    
  - Advancing the protocal of the website to HTTPS in usage.rst.
    
    Change-Id: Ibca48daefc917daed3f3f2a83c6d3c4973087289
    
  - Merge "Add Windows Event Log handler"
  - Add Windows Event Log handler
    
    The Python built-in logging module already provides a Windows Event
    Log handler. This change ensures that oslo.log exposes it.
    
    Change-Id: I287260b5046c88c433dfa66064da14faf15610e0
    Implements: blueprint windows-event-log
    
  - Clean up .gitignore references to personal tools
    
    Developers run all sorts of different tools within Git repositories,
    any of which can leave their own special trashfiles all over the
    place. We can't every hope to catalog them all, so better to
    recommend developers simply configure a global core.excludesfile to
    filter the irrelevant files which tend to get created by their
    personal choice of tools.
    
    To this end, remove the long-standing sections for "Mr Developer"
    and "Editors" since their mere existence here sends the signal that
    we welcome (and have time to review) additions for any old tool
    someone ever might happen to try. Also add a comment block
    explaining this, for clarity.
    
    We can, and should of course, continue to list files created by the
    tools recommended by our workflow (test frameworks called from tox,
    documentation and packaging builds, et cetera).
    
    This change is a port of I1b41efac219fca44e2548fc36633724d0ecfc0cb
    from the openstack-dev/oslo-cookiecutter repository.
    
    Change-Id: Ib2c9185265cfe7d2af5afc939f770cf5d5efb6ea
    
  - Always build universal wheels
    
    All of our projects are pure python, so we can build
    universal wheels by default.
    
    Change-Id: I173a1d5b4f204fcda2e92fd751228dbc79009b8c
    
  - Merge "Add devstack job with JSONFormatter configured"
  - Add devstack job with JSONFormatter configured
    
    We've run into issues in the past where a service passed something
    to the logger that broke JSONFormatter. To try to catch those sooner,
    add a job that configures the services to use JSONFormatter. This
    should provide a more realistic test of the formatter than we can
    hope to accomplish in unit tests.
    
    Change-Id: Icfb399cfe3dce89dfd5fb5079295a4947828417a
    
  - Filter args dict in JSONFormatter
    
    In most formatters, any unused keys in the args dict will just be
    discarded.  Because JSONFormatter logged the entire dict in addition
    to the message, some values were included in the output that may
    not have been intended.  This could include sensitive data, so we
    should stop that.
    
    In the interest of maintaining compatibility with any tools that are
    reading the args dict, we leave the dict but filter out any unused
    keys.
    
    Change-Id: Ib64837c1ae93a27bef3d30a776320a373f18dd1c
    Closes-Bug: 1571714
    Closes-Bug: 1787214
    
  - Merge "add lib-forward-testing-python3 test job"
  - Merge "add python 3.6 unit test job"
  - Merge "rewrite tests to not rely on implementation details of logging module"
  - Merge "import zuul job settings from project-config"
  - Merge "Follow the new PTI for document build"
  - Merge "Migrate to stestr"
  - Merge "Fix lower-constraints job"
  - add lib-forward-testing-python3 test job
    
    This is a mechanically generated patch to add a functional test job
    running under Python 3 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Ie968d6b5906ff0503b7cff6e2ed4c94b5cfcfa16
    Story: #2002586
    Task: #24322
    
  - add python 3.6 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.6 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Id487fff8eaee94f2f3d27e91e97de3f92842c88d
    Story: #2002586
    Task: #24322
    
  - rewrite tests to not rely on implementation details of logging module
    
    The tests for ensuring the results of the adapter are passed to the
    logger correctly rely more on the implementation details of the
    logging library than on the adapter supposedly being tested. As the
    underlying implementation changes in various ways, this causes the
    tests to fail (most recently when we try to run the tests under python
    3.6. Rather than adding yet another case to the conditional for this
    specific version of python, rewrite the tests so they do not rely on
    the underlying implementation details.
    
    Change-Id: Id4d416852553b8d11ad27e25edcf9cceab3eb1b6
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
    fix
    
    Change-Id: I1f5140b0a9499c94e13fa3cd0f7151dc6c952621
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - import zuul job settings from project-config
    
    This is a mechanically generated patch to complete step 1 of moving
    the zuul job settings out of project-config and into each project
    repository.
    
    Because there will be a separate patch on each branch, the branch
    specifiers for branch-specific jobs have been removed.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I380e361d5687dcc7f79cada43c6c97e4ce5c9e98
    Story: #2003250
    
  - Follow the new PTI for document build
    
    For compliance with the Project Testing Interface as described in:
    
    https://governance.openstack.org/tc/reference/project-testing-interface.html
    
    For more detials information, please refer to:
    
    http://lists.openstack.org/pipermail/openstack-dev/2017-December/125710.html
    
    Change-Id: I10537cf02d83f127b6932fa3f427043fb267d8b1
    Co-Authored-By: Stephen Finucane <sfinucan@redhat.com>
    
  - Migrate to stestr
    
    This should both keep mtreinish happy and get rid of annoying 'db type
    could not be determined' messages in one fell swoop.
    
    Change-Id: I0db004a8c8d75359e7d08c73b82f98c62a7e5f7d
    Signed-off-by: Stephen Finucane <sfinucan@redhat.com>
    
  - Fix lower-constraints job
    
    Resolve the following warning:
    
      Package 'systemd-python' is used in systemd but not in
      lower-constraints.txt
    
    Also fix the lower bounds to match the lower-constraints.txt list.
    
    Change-Id: I84bf8ec53cd80f19598d1139d21d18b4f0cadddc
    Signed-off-by: Stephen Finucane <sfinucan@redhat.com>
    
  - Imported Translations from Zanata
    
    For more information about this automatic import see:
    https://docs.openstack.org/i18n/latest/reviewing-translation-import.html
    
    Change-Id: Ic6649fb0d258b704f6171ef83e6444c1ce239936
    
  - Update reno for stable/rocky
    
    Change-Id: If22461f4717164f9f2969e0ebb7d51e8196318e7
    
  - Merge "Automatically append reset_color to log lines"
  - Add release notes link to README
    
    Change-Id: If7a344080dc4f87573de4f638c08fd5fc9733f15
    
  - Merge "tox: Group targets and tool configuration together"
  - Merge "tox: Don't set basepython in testenv"
  - Merge "Provide reset_color key on log record"
  - Automatically append reset_color to log lines
    
    It's confusing that log colors can persist across multiple log lines
    if they are not explicitly reset at the end of each line.  This
    change automatically appends the reset escape sequence to the end of
    each log record passed through the ColorHandler so the behavior is
    more what most people would expect.
    
    Change-Id: I5fefdbdd7dd2ca437863bf2117b5a93b527e9776
    
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Change-Id: I5f2ebf16d2768811f55939a55bedf59b808e0b9e
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Provide reset_color key on log record
    
    When logging with color, it is necessary to reset the color at the
    end of each line to avoid the color bleeding into subsequent log
    lines.  This change adds a new key to the record called 'reset_color'
    that serves as a shortcut to the escape sequence to reset the color.
    It also provides documentation for the ColorHandler class that
    explains how to use it.
    
    Change-Id: I68f1c716cbed241f79fa65dae1affe810b8e6e30
    Closes-Bug: 1731477
    
  - tox: Group targets and tool configuration together
    
    Easy readability win.
    
    Change-Id: Ic93c57cf2ffd73d75a88bc1efc8d67ee163a6c1f
    Signed-off-by: Stephen Finucane <sfinucan@redhat.com>
    
  - tox: Don't set basepython in testenv
    
    Turns out doing this overrides the basepython for every 'py{version}'
    implicit target, meaning py35, py36 etc. will use the same Python 3.x
    version. We don't want that so set basepython manually.
    
    This will hopefully be a non-issue when the gate bumps to Bionic.
    
    Change-Id: I8d47f9ede4e9d1d221f6643135407ad2d5cea282
    Signed-off-by: Stephen Finucane <sfinucan@redhat.com>
    
  - Fix Formatter subclasses for Python 3.2+
    
    Python 3.2 added the 'style' parameter to 'logging.Formatter.__init__'.
    This is provided by 'logging.config.fileConfig' meaning this currently
    raises a 'TypeError' similar to the below when the incompatible
    formatters, JSONFormatter and FluentFormatter, are used with Python 3.2
    or greater.
    
      TypeError: __init__() got an unexpected keyword argument 'style'
    
    Resolve this by simply adding the parameter to the list. There is more
    work we can do here (like actually supporting this parameter) but that's
    a job for another patch.
    
    Note that we can't actually test this as doing so would involve invoking
    'logging.config.fileConfig', which in turn would modify the global state
    of the 'logging' module. You can thank the singleton pattern for that.
    
    Change-Id: I9b339163ddfe440bc6782ced33595a0dcf60f658
    Closes-Bug: 1739743
    Co-Authored-By: Stephen Finucane <stephenfin@redhat.com>
    
  - Fix file permissions
    
    Change-Id: Iee0fbda6a167e5931d4778277a78da48debc84dd
    Signed-off-by: Stephen Finucane <sfinucan@redhat.com>
    
  - Merge "Trivial: Update pypi url to new url"
  - Remove stale pip-missing-reqs tox test
    
    pip_missing_reqs tool is no longer maintained and has broken with
    release 10 of pip
    
    Refer to:
     http://lists.openstack.org/pipermail/openstack-dev/2018-April/130027.html
    
    Change-Id: Iad38f39390fbdd33fc9c64bba44d72613d4f58d9
    
  - Trivial: Update pypi url to new url
    
    Pypi url changed from [1] to [2]
    
    [1] https://pypi.python.org/pypi/<package>
    [2] https://pypi.org/project/<package>
    
    Change-Id: Ia29e0eaeab7b250ce1d0bd91a3f12642b6bd551c
    
  - Fix sphinx-docs job
    
    build-openstack-sphinx-docs jobs fail on all branches due to the new
    pip version 10 introduces some previously Warning as Error: in case of
    calling "pip install" without any package name, the command fails.
    tox_install.sh is called during docs job without any package passed to pip.
    
    Change-Id: I400d4acf93ab634683cd9c4b05db7c79a51810be
    
  - set default python to python3
    
    Set the default python to python3 except for the py27 environment. We
    have to set that explicitly to override the new default.
    
    Change-Id: Ibaf75b2da94c8ba4e0c1f4b3e60992c1a3f41001
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>