Updated openstack/openstack Project: openstack/cinder  4dea7c751674181c8e6d7ef053ba1502a2c14f31
Doc: qos-specs is always and only "Administrators only"

Because of the underlying SQLAlchemy qos-specs functionality, which is
the only in-tree DB implementation, requiring context.is_admin to be
True, it's not technically correct to say "Administrators only,
depending on policy settings."  Even if the associated
volume_extension:qos_specs_manage policy doesn't require an
"administrator", the @requires_admin_context decorator on the
underlying functionality definitely will.

    ERROR: User does not have admin privileges (HTTP 403)

Change-Id: I0bc6a59c612b6c4ff7dcaff36dad712d8e3e03c2
Partial-Bug: #1621715