Updated openstack/openstack Project: openstack/cinder  73d0545b05d9559e4ad5ef1bec2b01eaa4554de3
Don't puke when exiting driver list

When you run the generate_driver_list.py file from inside the
tools dir, it pukes out an AttributeError for NoneType object
has no attribute 'close'.  This patch makes sure that exiting
doesn't cause a puke.

Change-Id: Ib6c4f451096cd07d0423941cab52ffa8cd8dc471