Updated openstack/openstack Project: openstack/horizon  d3d89c94216772fc48c71754e9d81ab2c5a7cadc
Fake deprecated nova client properties

Mox doesn't like the new nova client python properties that
were recently added to handle deprecations; just fake them out.

- UnknownMethodCallError: Method called is not a member of the object:
projectid

Change-Id: Iea69ee5c4a8f40eadc15391938443b04116cb3c3