Updated openstack/openstack Project: openstack/tempest  14e67909e33d3963da7987a4ad3c796d969a719f null Cleanup exceptions
There are some invalid usages about exceptions. They put some invalid
error messages to the log like this.
  --------------------------
  BuildErrorException: Server %(server_id)s failed to build and is in
  ERROR status)
  --------------------------
This commit fixes them.

NOTE: 'RateLimitExceeded' is only used in tempest/common/rest_client.py.
 This was refactored in I6c38c343618f92e0e79843aaa662a3d24026702b . But
 the class was not. And the last usage of 'SQLException' was removed in
 I0fac7b030c51985f9d6d93129bf9bab75c18cd11 . But the class was not.

Change-Id: I1477e093a56210c0c9a65fa32900c2c0b876d9a4