Update git submodules
* Update bifrost from branch 'master'
  to 33d0dc805d3a243eeb9cf1a78a7cdcff611501a1
  - libvirt: pin edk2-ovmf for CentOS Stream
    
    edk2-ovmf introduced a bug [1] and results in libvirt/qemu errors:
    
        libvirt.libvirtError: internal error: unknown feature amd-sev-es
    
    It's going to be fixed in the next rebase to libvirt 7.4.0 - but let's
    pin for now.
    
    This affects CI and test environments using the
    bifrost-create-vm-nodes role.
    
    [1]: https://bugzilla.redhat.com/show_bug.cgi?id=1961558#c10
    
    Depends-On: https://review.opendev.org/c/openstack/bifrost/+/793349
    
    Change-Id: I40f018715b3a6c061039f6cd29f6acb254182685