Updated openstack/openstack Project: openstack/diskimage-builder  b312c06dbbf25651c1547996203e6525be2d5c8b
Decode string to bytes in dracut-regenerate

In python3, the standard out data returned by
subprocess.Popen.communicate() will in most cases be bytes rather than a
string and must therefore be decoded.

Without this fix we hit the following error:

TypeError: a bytes-like object is required, not 'str'

Change-Id: I6d75f867ebfdb925970c3397175214b9050d7632
Closes-Bug: #1694463