Update git submodules
* Update nova from branch 'master'
  to 7dc4b1ea627d864a0ee2745cc9de4336fc0ba7b5
  - Merge "add functional repoducer for bug 2065927"
  - add functional repoducer for bug 2065927
    
    Today if the write sys call to offline a cpu when
    deleting an instnace fails due to an OSERROR or ValueERROR
    the instance delete fails and the instance goes to error.
    
    as reported in bug: #2065927 this can happen as a result of
    OSError: [Errno 16] Device or resource busy if the vm is
    deleted shortly after its started.
    
    Related-Bug: #2065927
    Change-Id: I1352a3a1e28cfe14ec8f32042ed35cb25e70338e