Update git submodules
* Update ironic-specs from branch 'master'
  to c564dc3d378ae68266d5772de47c81644ca9aedd
  - Fix Multiple top-level packages discovered in flat-layout
    
    The linters and docs jobs are failing due to:
    ```
    error: Multiple top-level packages discovered in a
    flat-layout: ['specs', 'priorities'].
    ```
    This commit ensure we add the dirs in setup.cfg to
    avoid the problem
    
    Change-Id: I7ed2ac860b48a71d8f11fedd6072ef4e49f4ba22