Updated openstack/openstack Project: openstack/neutron-fwaas  7308b372babc42e9d92db90d85327f3e5d39208c
FWaaS Disable nonstandard-exception due to neutron_lib shims

The current FWaaS will fail pylint:
pylint runtests: commands[0] | pylint --rcfile=.pylintrc
--output-format=colorized neutron_fwaas
************* Module neutron_fwaas.db.firewall.firewall_db
W:621,12: Exception doesn't inherit from standard "Exception"
class (nonstandard-exception)
ERROR: InvocationError:
'/opt/stack/neutron-fwaas/.tox/pylint/bin/pylint
--rcfile=.pylintrc --output-format=colorized neutron_fwaas'

Looks like due to recent change
"FWaaS: make use of neutron_lib exceptions."
The culprit code:
   raise l3.RouterInUse(router_id=router['id'])
imports into fwaas from base Neutron as a neutron.common.exception,
not a neutron_lib.exceptions.

Quick investigation shows the neutron added following to .pylintrc:
neutron_lib shims
 nonstandard-exception,

Adding same to neutron_fwaas, complete with the TODO so will
remember to remove when neutron_lib shims are cleaned up.

Change-Id: I9bf2001e8c12038e152422051e2fb2a10214575c