Update git submodules
* Update nova from branch 'master'
  to 4611973c99b42db8b2a515de55a2232e8d85ed14
  - Merge "libvirt: Fix regression of listDevices() return type"
  - libvirt: Fix regression of listDevices() return type
    
    This a partial revert of change
    I60d6f04d374e9ede5895a43b7a75e955b0fea3c5 which added tpool.Proxy
    wrapping to the listDevices() and listAllDevices() methods.
    
    The regression was caught during downstream testing with vGPUs and the
    update_available_resource() periodic task was failing with:
    
      TypeError: virNodeDeviceLookupByName() argument 2 must be str or
        None, not Proxy
    
    It turns out that while the listAllDevices() method returns a list of
    virNodeDevice objects [1], the listDevices() method returns a list of
    string names [2] and is generated from the corresponding function in C
    [3].
    
    The error was not caught by unit or functional testing because those
    test environments intentionally do not import the libvirt Python
    module -- so mocked code in the LibvirtFixture runs instead. Also, the
    update_available_resource() method has a 'except Exception:' at the end
    which logs an error but does not re-raise. So it would not cause a
    functional test to fail.
    
    This reverts the change that caused the regression, updates potentially
    confusing docstrings, adds type annotations to the methods that use
    listDevices(), and moves the nodeDeviceLookupByName type checking into
    the LibvirtFixture.
    
    Closes-Bug: #2098892
    
    [1] https://github.com/libvirt/libvirt-python/blob/408815a/libvirt-override-virConnect.py#L520-L524
    [2] https://github.com/libvirt/libvirt-python/blob/408815a/libvirt-override-api.xml#L448-L453
    [3] https://libvirt.org/html/libvirt-libvirt-nodedev.html#virNodeListDevices
    
    Change-Id: Ib5befdd3c13367daa208ff969f66cba693ae2c76