Updated openstack/openstack Project: openstack-infra/project-config  dfb9362e32bc809b6dda0ef0db621b96bfdc8f5c
Revert "Enable clean-floating-ips for OVH and BlueBox"

This reverts commit 48b8f7a2c426cc5836e974b4f52a329e8dfe72cb.

Shade is currently broken:

2016-05-18 22:51:04,129 ERROR nodepool.NodePool: Exception cleaning up leaked nodes
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nodepool/nodepool.py", line 2032, in periodicCleanup
    self.cleanupLeakedInstances()
  File "/usr/local/lib/python2.7/dist-packages/nodepool/nodepool.py", line 2087, in cleanupLeakedInstances
    manager.cleanupLeakedFloaters()
  File "/usr/local/lib/python2.7/dist-packages/nodepool/provider_manager.py", line 347, in cleanupLeakedFloaters
    self._client.delete_unattached_floating_ips()
  File "/usr/local/lib/python2.7/dist-packages/shade/openstackcloud.py", line 3524, in delete_unattached_floating_ips
    id=ip['id'], wait=wait, timeout=timeout))
TypeError: delete_floating_ip() got an unexpected keyword argument 'id'

Change-Id: I9586e68eadeaf1cacd4faf46c30411bf09c788d9
Signed-off-by: Paul Belanger <pabelanger@redhat.com>