Updated openstack/openstack Project: openstack-infra/zuul  661d8f855e52d3f93d053f4bb9fc34613a27fbfb
Fix typo with ansible-playbook process

Because we skipped setting our ansible_job_process to None, it was
possible for our abortRunningProc to error:

  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/zuul/launcher/ansiblelaunchserver.py", line 671, in abortRunningProc
      pgid = os.getpgid(proc.pid)
  OSError: [Errno 3] No such process

Change-Id: Ie6da0614a75281782fb0f29f6c8046a02e1681b9
Signed-off-by: Paul Belanger <pabelanger@redhat.com>