Update git submodules
* Update tenks from branch 'master'
  to c9515e0ca829db821ed66d7df3ca3d61220f516c
  - CI: Fix ansible-lint failure
    
    Currently ansible-lint is failing with:
    
        KeyError: 'hostvars'
    
    This change fixes the issue by making the hostvars key optional. This
    should not affect real usage, since an error is raised in this case.
    
    Change-Id: I6dd482e95fa4f5508452d83bb64613d55eb1985f