Updated openstack/openstack Project: openstack/trove  d84be640de5da184760fd3376215eb898df28a95
tempest/test_flavors: vcpus is in db

When Tempest list Trove flavors, the returned flavor contains name, ram
and vcpus.

An example of test run without this patch:

testtools.matchers._impl.MismatchError: {u'name': u'm1.nano', u'ram':
128, u'id': 42, u'links': [{u'href':
u'https://[::1]:8779/v1.0/04f8954d605644088e9f87cc3383dfef/flavors/42',
u'rel': u'self'}, {u'href': u'https://[::1]:8779/flavors/42', u'rel':
u'bookmark'}], u'str_id': u'42', u'vcpus': 1} matches Contains('vcpus')

We can see 'vcpus' is part of the flavor properties and need to be
checked in the validation.

Change-Id: I9bb18dc539e98bfe1e0d0b4dd1fe6263f95b6499
Closes-Bug: #1612398