Update git submodules
* Update glance from branch 'master'
  to c08c17501641206fb8b74a07cd19c6d960699845
  - Merge "Remove legacy update tests"
  - Remove legacy update tests
    
    These tests were introduced in Feb, 2021[1] to test upgrade
    path from single store to multistore for glance cinder backend.
    Overtime there have been a series of updates[2][3][4][5][6][7][8]
    to keep the tests compatible with updates done in the glance cinder
    store, last one being done in Jan, 2023.
    Ovetime, we have been enforcing deployments to use multi stores
    instead of single store and hence we can assume that most, if
    not all, deployments have moved to multi stores given the
    5 year time period.
    A lot of the methods are mocked in the functional tests, even
    internal ones, causing failures when updating internal
    methods in the glance cinder store.
    Recent example of such a failure is visible on change[9].
    
    TypeError: TestLegacyUpdateCinderStore._mock_wait_volume_status() takes 4 positional arguments but 5 were given
    
    Overall, the effort required to keep these tests up to date outweighs the
    coverage they provide, hence it's logical to remove them and ease developer
    efforts while making changes in glance cinder backend.
    
    [1] https://github.com/openstack/glance/commit/09b924c9bcdfd4d750f285f60cfd02f5504908fb
    [2] https://github.com/openstack/glance/commit/09b924c9bcdfd4d750f285f60cfd02f5504908fb
    [3] https://github.com/openstack/glance/commit/0e2043d51ebe90acd0e6f284774c5411cb1c886b
    [4] https://github.com/openstack/glance/commit/01b5bf5ece9a6904c1c5df4ad557967c927b8683
    [5] https://github.com/openstack/glance/commit/de8c8502694f1156e2a4240efb44d5c19e04a486
    [6] https://github.com/openstack/glance/commit/acc6f624cdb1b2e4a3900e7d226bbc5156e8fa17
    [7] https://github.com/openstack/glance/commit/f40ac40c2c40d57637312959b680121a9c89949a
    [8] https://github.com/openstack/glance/commit/0e70f66165f47f0f5890d8774a566014a23d9dea
    [9] https://review.opendev.org/c/openstack/glance_store/+/962398
    
    Change-Id: I4d24fc267c093e4b8845973b739cd22e686b2312
    Signed-off-by: Rajat Dhasmana <rajatdhasmana@gmail.com>