Updated openstack/openstack Project: openstack/neutron  c20c7e6da855d85f3532190960a832f83a4df472 null Fix TypeError: <MagicMock name='LinuxBridgeManager().local_ip'
This patch fixes an error that does not result in a test failure but
causes the following error to be logged in the test logs:

TypeError: <MagicMock name='LinuxBridgeManager().local_ip' id='666599248'>
is not JSON serializable

Related-Bug: #1234857

Change-Id: I65cdd997745d8b760031f8f32e3c10682ad2288e