Updated openstack/openstack Project: openstack/nova  6d486ffe464898d040e662c13067cb8ee23fe6bf
Fix nova-manage cell_v2 discover_hosts RequestContext

In the nova-manage cell_v2 discover_hosts command, the nova.context
module is erroneously being passed to a database API function instead
of a RequestContext object, causing the error on the command line:

  error: 'module' object has no attribute 'session'

This corrects the argument and adds a test assertion for the
RequestContext.

Closes-Bug: #1650694

Change-Id: I7b5468218e79ffc77adf15d2f00c063095d62af3