Updated openstack/openstack Project: openstack/openstack-doc-tools  9263ac8c5a4be82d799032958c382f6a778608dc
Add missing requirement PyYAML

os_doc_tools/commands.py requires PyYAML. PyYAML is not included in the
requirements.txt file at the moment.

os_doc_tools/commands.py", line 19, in <module>
    import yaml
ImportError: No module named yaml

Change-Id: I7a5b6c5b2c74b2fa23fa74b6bf47a1b0d8c58b01