Update git submodules
* Update python-tackerclient from branch 'master'
  to 4978e7db517937c9a642bff24978d377b75f2a77
  - Fix unit test error caused by cliff upgrade
    
    This patch fixes the following issue of unit test that caused by
    upgraded version of cliff library to v4.4.0.
    
    -----
    AttributeError: 'FakeStdout' object has no attribute 'isatty'
    -----
    
    Change-Id: I77438314f8cf98e62155b1e43da3484cd5f1f514