Updated openstack/openstack Project: openstack/python-swiftclient  c9f79e641c6906e95095f3e0e505f9bd3f715bc2
Mention --segment-size option after 413 response

Previously, it would only output something like

  ClientException: Object PUT failed <url> 413 Request Entity Too Large
  Your request is too large.

... which is misleading as it implies that Swift simply can't handle
large objects.

Change-Id: Icec9e76b2671490c3a2249ec08992950107c6828