Update git submodules
* Update tripleo-heat-templates from branch 'master'
  to b0c107825ad3a2fe4c459a4182ec04cd996cdec4
  - Merge "Comment out parameter_defaults in barbican simple crypto template"
  - Comment out parameter_defaults in barbican simple crypto template
    
    Including this template in a deploy but not including anything in
    `parameter_defaults` is going to fail when heat attempts to parse that
    environment file because `parameter_defaults` is empty:
    
      ValueError: environment has empty section "parameter_defaults"
    
    This commit attempts to fix that by commenting out the section since
    there doesn't seem to be a reasonable default to use.
    
    Change-Id: I06a5e13d768c65a8d5cf0b635620c33523b374f4