Update git submodules
* Update oslo.metrics from branch 'master'
  to 48e02abf4195573d6e6b9088fd0efc3267df1e73
  - Fix mypy errors
    
    These are now detected as errors since recent typing support by
    oslo.log .
    
    oslo_metrics/message_router.py:16: error: Unused "type: ignore" comment
    [unused-ignore]
    oslo_metrics/__main__.py:28: error: Unused "type: ignore" comment
    [unused-ignore]
    
    Change-Id: Icd411989a30ac7807e59fbb29b343efd381ad911
    Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>