Update git submodules
* Update openstacksdk from branch 'master'
  to 7040c81d1a485cc089b10cab52c9ca7b3dd2f54a
  - Use mypy syntax compatible with older pythons.
    
    Change I1cb1efbf1f243cca0c5bb6e1058d25b2ad863355 introduced mypy
    syntax which breaks Python releases before 3.10. Unfortunately, for
    2024.2 we commit to supporting Python back to 3.9.
    
    Specifically, you receive this error message if you run pep8 on Rocky 9:
    
    pep8 mypy.....................................................................Failed
    pep8 - hook id: mypy
    pep8 - exit code: 1
    pep8
    pep8 openstack/dns/v2/_base.py: note: In member "list" of class "Resource":
    pep8 openstack/dns/v2/_base.py:83:27: error: X | Y syntax for unions requires Python 3.10  [syntax]
    pep8 Found 1 error in 1 file (checked 414 source files)
    
    So instead, let's use typing syntax compatible with other pythons.
    
    Change-Id: Ifcf68075e572ccfc910dbef449cd58986c2a1bf5