Updated openstack/openstack Project: openstack/requirements  0d42548f92d4cade177c17cb0b8815516ca1086d
Updated from generate-constraints

restricted update of iso8601
AttributeError: module 'iso8601.iso8601' has no attribute 'Utc'
restricted update of pika
Requirement.parse('pika<0.11,>=0.9'), set(['pika-pool']))

restricted update of sqlalchemy (based on past updates)
restricted update of kubernetes (based on past updates)

Change-Id: Ie9782d231de63a624d16e87087c6b2a3d999ff25