Updated openstack/openstack Project: openstack/neutron  548f323f594d6b3e43ad0e16deced9fc491e1e60
Fix TypeError caused by delete_agent_gateway_port()

A recent change used a keyword argument when it didn't need to,
correct it to fix the multinode DVR job.

End of typical traceback:

File "/opt/stack/new/neutron/neutron/api/rpc/handlers/l3_rpc.py",
in delete_agent_gateway_port(admin_ctx, network_id, host_id=host)

TypeError: delete_floatingip_agent_gateway_port() got multiple
values for keyword argument 'host_id'

Introduced in commit 639f1893dde0d393a97b29ca5309dba716831a7

Related-bug: #1495147

Change-Id: Id2522bc843bc7b089b7783d3f765900a50a0033f