Updated openstack/openstack Project: openstack/designate  6f91346dd9c57d338e4dbd8b1ad516f8bad5b4c9
Fixed rootwrap file installation

The previous patch [1] that introduced installation of configuration
files had a wrong order of arguments. That resulted in setuptools
installation failure as follows:

error: can't copy 'etc/designate/rootwrap/bind9.filters': doesn't exist
or not a regular file

The proper order is dest-dir = src-path, not vice versa.

[1]: Ib04ce7ca8e16ca1a07a39526c540802764a7c547

Change-Id: Ie7924439eb33145339e0ada4433374ba54b9cd16