Updated openstack/openstack Project: openstack/swift  fcf318c421ada44e9b6b6dc31031fddf6c3f5578
Make test assertion more holistic

Previously, introducing an error would yield an accurate failure, but
without much context, like

Traceback (most recent call last):
  File "/vagrant/swift/test/unit/proxy/controllers/test_base.py", line 635, in test_headers_to_account_info_storage_policies
    resp['storage_policies'][0]['bytes'], 1002)
KeyError: 'bytes'

Now, we'll have a much larger picture of what's going on:

Traceback (most recent call last):
  File "/vagrant/swift/test/unit/proxy/controllers/test_base.py", line 636, in test_headers_to_account_info_storage_policies
    'bytes': 0},
AssertionError: {0: {'object_count': 13, 'container_count': 120}, 1:
{'object_count': 10, 'conta [truncated]... != {0: {'object_count': 13,
'container_count': 120, 'bytes': 1002}, 1: {'object_cou [truncated]...
- {0: {'container_count': 120, 'object_count': 13},
+ {0: {'bytes': 1002, 'container_count': 120, 'object_count': 13},
?      +++++++++++++++

-  1: {'container_count': 20, 'object_count': 10}}
+  1: {'bytes': 0, 'container_count': 20, 'object_count': 10}}
?      ++++++++++++

Related-Change: I800266d15aabcc7b6e0234de3c9b965b5c15a623
Change-Id: I9a4e5d62674c467bca4bc70d5150d918d48aac42