Update git submodules
* Update nova from branch 'master'
  to a980cd3dbc5de3bf75cfd892c0db8aff87a8d032
  - Merge "Avoid stacktrace at CLI exit"
  - Avoid stacktrace at CLI exit
    
    Eventlet mode in our CLIS with py314 or newer cases a stack trace
    printed at the end of each CLI execution.
    
    Exception ignored on calling weakref callback <function _removeHandlerRef at 0x7c7c7eea1fe0>:
    Traceback (most recent call last):
      File "/usr/lib/python3.14/logging/__init__.py", line 893, in _removeHandlerRef
      File "/usr/lib/python3.14/threading.py", line 208, in acquire
      File "/opt/stack/data/venv/lib/python3.14/site-packages/eventlet/green/thread.py", line 39, in get_ident
    RuntimeError: greenlet is being finalized
    
    This is due to threading being monkey patched and during interpreter
    exit some logging cleanup code tries to grab a monkey patched lock after
    the greenlet module is already finalized. This patch avoids the stack
    trace by nuking the logging module cleanup handlers at exit.
    
    Closes-Bug:#2155245
    
    Change-Id: I81502677edda2b344960e85d4cf09fac8f7ade91
    Signed-off-by: Balazs Gibizer <gibi@redhat.com>