Update git submodules
* Update puppet-openstack-integration from branch 'master'
  to c25cf054312b85482e73c5886370d7db0cf08df7
  - RabbitMQ: Override hostname to ensure correct IP version
    
    Change fe83b5488d33b75be6a9bba97faa8ddd69210973 enforced usage of IPv6
    in case the scenario requires IPv6, but this causes the following
    failure during rabbitmq startup, because hostname is sometimes resolved
    to IPv4 address in CI.
    
    ```
    ERROR: epmd error for host np0033504771: badarg (unknown POSIX error)
    ```
    
    This makes sure that hostname env is set according to IP address
    version.
    
    Change-Id: I4d876200f0fd8b2b84d893f243fe5615352ef11d