Update git submodules
* Update swift from branch 'master'
  to e9cf2a31aad877e14df428d360a67e00be4019d0
  - Merge "tests: Clear txn id on init for all debug loggers"
  - tests: Clear txn id on init for all debug loggers
    
    Since we fake out all the greenthread stuff to run in the main thread,
    we can (sometimes?) find that a transaction ID has already been set,
    leading to failures in test_bad_request_app_logging like
    
        AssertionError: b'X-Trans-Id: test-trans-id' not found
        in b'X-Trans-Id: tx...'
    
    By resetting the logger's txn_id, we're assured that our mock will be
    run and the expected transaction ID will be used.
    
    Change-Id: I465eed5372a2a5e591f80a09676f4b7f091cd444