Update git submodules
* Update tripleo-image-elements from branch 'master'
  - Merge "Optimizing the safety of the http link site in HACKING.rst"
  - Drop baremetal job template
    
    https://review.openstack.org/#/c/619337/ switched the jobs to a noop for
    master and since this file is branched we no longer need to keep this
    template definition in this project.
    
    Change-Id: Id69b553319146d3199684a59f9cfe4cc72d65f90
    
  - Merge "fix tox python3 overrides"
  - Optimizing the safety of the http link site in HACKING.rst
    
    Change-Id: I4267b0c4fc6200ccd3ac1966fafb1738a507f591
    
  - Increase size for security hardened images
    
    With the move to containers there has been an increase of
    demand on the /var volume. Increase the global size, as well
    as give more percentage to /var and reduce /root.
    
    Also fix fsck-passno setting, that was incorrectly set.
    
    Change-Id: I8d820f668ffffe5993d5fef38e0c1e8c5f5862ec
    Depends-On: Ib806bac815077c2508060719469b5d0f1acc0f99
    
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Change-Id: I7ac34fa0215114f3d7345abd183c84159a30440e
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - add python 3.6 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.6 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Ibf92e87e90f111d283460f59f782dec8b5229158
    Story: #2002586
    Task: #24341
    
  - add python 3.5 unit test job
    
    This is a mechanically generated patch to add a unit test job running
    under Python 3.5 as part of the python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Iab2a0626bfbf551aac0aa30c07a2e5bee3513575
    Story: #2002586
    Task: #24341
    
  - Merge "Fix unit tests in python3"
  - Merge "switch documentation job to new PTI"
  - Merge "Update reno for stable/rocky"
  - Fix unit tests in python3
    
    Fix the check_output in unit tests, the result was being
    intrepid as a byte string which caused unit tests to fail.
    This patch makes it a utf-8 string.
    
    Change-Id: Iba5c50762846ef5266eddd397aca44b01d411354
    Signed-off-by: Chuck Short <chucks@redhat.com>
    
  - Update reno for stable/rocky
    
    Change-Id: I6135338e20a384d095e34e6f630d4578f829bca6
    
  - switch documentation job to new PTI
    
    This is a mechanically generated patch to switch the documentation
    jobs to use the new PTI versions of the jobs as part of the
    python3-first goal.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: I77f5ae1fc8bad0d994c7e226c99ab076add6555c
    Story: #2002586
    Task: #24341
    
  - import zuul job settings from project-config
    
    This is a mechanically generated patch to complete step 1 of moving
    the zuul job settings out of project-config and into each project
    repository.
    
    Because there will be a separate patch on each branch, the branch
    specifiers for branch-specific jobs have been removed.
    
    Because this patch is generated by a script, there may be some
    cosmetic changes to the layout of the YAML file(s) as the contents are
    normalized.
    
    See the python3-first goal document for details:
    https://governance.openstack.org/tc/goals/stein/python3-first.html
    
    Change-Id: Icb65dad5452802e123cc8b7d9df75f8fdbc6c007
    Story: #2002586
    Task: #24341
    
  - Merge "Add release note link in README"
  - Merge "Add overcloud-secure-uefi element"
  - Add release note link in README
    
    Change-Id: I70702e45c2e6f229ec0067972a0456b4977ff767
    
  - Add overcloud-secure-uefi element
    
    This is the equivalent of the overcloud-secure element,
    but is defined to generate images that are capable to boot
    from UEFI.
    
    Change-Id: If9e0504438632f1a22b45b7c95e7bfb8cb6f41d3
    Depends-On: I47c96450e10f34b91bcc32888532bd7ab87cf316
    Depends-On: Id3dee735e6f8fb221d199c4aba648f3e9a6e4206
    
  - Update links in README
    
     Change the outdated links to the latest links in README
    
    Change-Id: Idd2c27998b0711a30916cd200ea76a1563b06432
    
  - Fix readme formating issues
    
    $ python setup.py check -r -s
    running check
    warning: check: Unexpected indentation. (line 65)
    
    error: Please correct your package.
    
    Change-Id: I0ff83476918c00f59c5cf292944a3213e8ee41a9
    Related-Bug: #1774001
    
  - Add python jobs to tripleo-image-elements
    
    This change also fixes the python tests to properly mock the path so our
    stubs work if the command already exists on the system path.
    
    Change-Id: I7c54b1d99e7cf6c4e3f4ded8c518bf447b2ba1de
    
  - Merge "Add a 60 seconds timeout to ping_metadata_ip()"
  - Add a 60 seconds timeout to ping_metadata_ip()
    
    Closes-Bug: #1735849
    
    Change-Id: I1004c2d764339c30653e2f4a3c7aee1343a20b4e
    
  - remove os-cloud-config element
    
    It's not being used anymore.
    
    Change-Id: I429c0013802af3bcb80f9a623b8fce0a2e52bb64
    
  - Add a dependency on block-device-mbr element
    
    When specifying the layout for the hardened image, we need
    also to specify the device type, that in our case will be
    mbr. So add this as a dependency of overcloud-secure to
    properly set the type.
    
    Change-Id: Ic0ad151cc12723e437a1123f90c6663198b9564d
    
  - Increase the image size to 23G
    
    The recent tests showed that we need more space for the /var
    partition, and that we need to increase the final size of the
    image to 23G to fit the needs. And we need to rebalance the
    percentage used by volumes to have similar sizes.
    
    Change-Id: Icf25fc15bd71a50e68038012683e3e56aaa72443
    Depends-On: I3885a5c359b56c515dbb9286ded1dee062cdcffc
    
  - Merge "Add another path for service files"
  - Update reno for stable/queens
    
    Change-Id: I1acc7810c18183a521f32e51b5409adffc057a65
    
  - Add another path for service files
    
    In opensuse the service files are located in /usr/lib rather than /lib. This change adds this path
    as an option.
    
    Change-Id: I99c2db557a2290c3860bb41233d7efc35d03be0b