Updated openstack/openstack Project: openstack/trove  7b05198eeff46b507fa3ca76f9cae9eba5655437
Fix tempest base: add missing imports

Tempest fails with the error::

    Traceback (most recent call last):
      ...
      File "trove/tests/tempest/tests/api/base.py", line 37, in setup_clients
	cls.database_flavors_client = flavors_client.DatabaseFlavorsClient(
    NameError: global name 'flavors_client' is not defined

Change-Id: I2ed107e8f631b51830487805e87a2d730391c632