Update git submodules
* Update subunit2sql from branch 'master'
  - Fix gate error "mysqladmin: command not found" and etc
    
    mysqladmin package is required in tools/test-setup.sh
    so adding bindep.txt file for this binary dependencies. And postgresql
    packages are also required as well.
    
    - http://lists.openstack.org/pipermail/openstack-discuss/2019-June/007272.html
    
    This commit also updated sphinx versions in test-requirements.txt to
    avoid this error.
    
      ERROR: Sphinx requires Python '>=3.5' but the running Python is 2.7.15
    
    And also, this commit fixes a sqlalchemy error. This probably caused by
    sqlalchemy version updates. It might be better to fix the code rather
    than the sqlalchemy version cap.
    
      sqlalchemy.exc.ArgumentError: Textual SQL expression
        "tests.id='fake_null_test_..." should be explicitly declared as
        text("tests.id='fake_null_test_...")
    
    Change-Id: Iff79081403fbc26442165ff5feb300bc317b0dfc
    
  - OpenDev Migration Patch
    
    This commit was bulk generated and pushed by the OpenDev sysadmins
    as a part of the Git hosting and code review systems migration
    detailed in these mailing list posts:
    
    http://lists.openstack.org/pipermail/openstack-discuss/2019-March/003603.html
    http://lists.openstack.org/pipermail/openstack-discuss/2019-April/004920.html
    
    Attempts have been made to correct repository namespaces and
    hostnames based on simple pattern matching, but it's possible some
    were updated incorrectly or missed entirely. Please reach out to us
    via the contact information listed at https://opendev.org/ with any
    questions you may have.