Update git submodules
* Update storyboard from branch 'master'
  - Pin oauthlib<3 for now
    
    The recent oauthlib 3.0.0 release seems to have regressed
    authentication, raising "InvalidRedirectURIError: (invalid_request)
    Invalid redirect URI." in
    oauthlib.oauth2.rfc6749.grant_types.base._handle_redirects() on
    returning from the OpenID provider. This is an emergency pin to <3
    until we're able to suss out whether this is a bug in storyboard's
    authentication client implementation or a legitimate regression in
    oauthlib.
    
    Change-Id: Iad4e035d88a0cd335c6ef68263bf7e044a192513
    
  - Change openstack-dev to openstack-discuss
    
    Mailinglists have been updated. Openstack-discuss replaces openstack-dev.
    
    Change-Id: I3427af2d850de96661f6d49629eece0500f08d49
    
  - Merge "Fix up a few requirements"
  - Merge "Revert "skip some alembic migrations for sqlite""
  - Revert "skip some alembic migrations for sqlite"
    
    This reverts commit e23eba1ba81cd04473cf4d2c9d3b93f396cb5b73.
    
    TypeError: Error when calling the metaclass bases
    build_fulltext() takes exactly 2 arguments (1 given)
    
    Change-Id: Ic8859b2b5668a03d3e2ef6f479c5f8c0ec36effd
    
  - Merge "skip some alembic migrations for sqlite"
  - Fix up a few requirements
    
    The upper cap on oslo.db and sqlalchemy cause very old versions of both
    to be installed. The oslo.db one is particularly bad as it includes a
    'def async' which does not work with python3 (fascinated how the tox
    py35 tests are working)
    
    eventlet and sqlalchemy-migrate were added a while ago to solve
    build-time dependency issues in transitive deps. They are no longer
    needed.
    
    Change-Id: I964d87408573008c7b7cca6ce0110a910429b9b8
    
  - accept tag values in the body as well as URL
    
    The JS client passes arguments to the PUT call in the URL so we need
    the tags argument to the put() method. The python client passes
    arguments encoded in the body of the request, so we need the body
    argument. Merge the two sets of values so that inside the function we
    only have to process one list.
    
    Change-Id: I21a82321fabbe4f0d0a5db5a9db5dda8f65f21bb
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - skip some alembic migrations for sqlite
    
    SQLite does not support many of the DDL instructions to modify
    tables. We only use it for development and unit tests, so we don't
    need to support it fully in the alembic migrations.
    
    This patch updates the tests to use sqlalchemy's create_all() function
    to initialize the sqlite database, and then skips the migrations or
    portions of migrations that would not work for sqlite.
    
    This has 2 benefits: creating the database in the unit tests is faster
    and it should simplify any work we need to do to remove constraints
    from tables or otherwise change the database schema, since those
    changes will only need to be run for mysql tests and not the sqlite
    tests.
    
    Change-Id: I6658596ca3687595596d09428f97f9a82f9062ac
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Update coverage environment
    
    Fix coverage environment to default stestr setup.
    Update timeout for tox-cover.
    
    Change-Id: I8f7b19743aa3d4b51316c9941bb751ff622fb354
    
  - Merge "Support getting project groups by name"
  - Support getting project groups by name
    
    Change-Id: I21eb2e5249c73c79d2ba1831ccef61e05645d66c
    
  - Merge "Add a test openid server"
  - Make email public field
    
    This will be used wherever sb users are searching for other users
    as a way to differentiate people with the same name.
    
    Change-Id: Id618f79f6556f958959f87f1057d75fc298ccc98
    Story:2000132
    Task: 24372
    
  - Merge "Add to & Reorganize StoryBoard GUI Docs"
  - Merge "Validating task status in the API"
  - Merge "fix tox python3 overrides"
  - Merge "change default python 3 env in tox to 3.5"
  - Validating task status in the API
    
    Adding enum for task statuses validation in API
    
    Story: 2001432
    Task: 22469
    
    Change-Id: I39e9227b7dcc39be1fbea131918a3874b1631017
    
  - Replace broken links and http links in the doc
    
    Some typos were fixed too.
    
    Change-Id: I05f621c2daa1142006ab8e04164c75a031edea4f
    
  - Merge "add an index for the story_storytags table"
  - Add to & Reorganize StoryBoard GUI Docs
    
    This patch does a little reorganization of the gui docs.
    It adds a section solely focused on the creation and
    functions of boards. It also adds a section on best
    practices as we get a lot of questions about how things
    should be done.
    
    Change-Id: Id208d2edb754030a75ba2c1884fd8ef0b620a6af
    
  - add an index for the story_storytags table
    
    Queries that look for stories with tags take significant amount of
    time without this change. One trivial query for active stories with
    one tag dropped from 7m19s to 2.7s.
    
    Story: #2001939
    Task: #15055
    Change-Id: Id1783a3cf355f11b2037f4e0ada9514993820bca
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Merge "mark FilterCriterion title as a mandatory field"
  - Merge "mark worklist filter_criteria as a required field"
  - Merge "use required enums to validate 'type' args"
  - Support quoted project names in GET requests by name
    
    Currently the webclient quotes the project name before sending the
    request, which causes a 404 if there is a / in the project name since
    the API doesn't unquote the name before searching for it.
    
    This commit makes the API less opinionated by unquoting provided project
    names before searching for them, which should make it less frustrating
    to use.
    
    Change-Id: I9a0158231f54809b90198875712ac0cbd543a254
    
  - change default python 3 env in tox to 3.5
    
    Change-Id: Icbc062d281cb1d48da45bf550d8514e37be4b9c9
    
  - Revert "Make notification driver configurable"
    
    This reverts commit c7e0e458fff4a317789fea192fb5cf5f2fb0fe5c because
    it causes a regression. The noted symptom is that OpenID logins
    consistently failed and/or timed out with "Lock wait timeout
    exceeded; try restarting transaction" in the logs raised by the
    "UPDATE users SET updated_at=%(updated_at)s,
    last_login=%(last_login)s WHERE users.id = %(users_id)s" query.
    Diagnosis revealed no persistently open tables where in_use>0 and no
    unexpected processes reported in the MySQL show processlist output.
    Restarts of apache2 and storyboard-workers services yielded no
    change in behavior either, nor did restarting the VM providing
    MySQL. Ultimately, bisecting the storyboard codebase revealed that
    with this change applied the symptom was reliably manifest but the
    regression disappeared on the commit before it merged.
    
    Change-Id: I3d40abe04f53e9086020ec88e8610423197c3e9f
    
  - Revert "Add MQTT notification publisher"
    
    This reverts commit d84e80ec99863f6a0c1bc66f7558bd80d083a66f because
    it depends on change I5235ae4368f8bff13c767b87ced83173d52b5155 which
    is being reverted.
    
    Change-Id: Icfda239538ff9d1ef663e32e6bc9695bb99b2dcb
    
  - Revert "Add configurable notification subscriber and mqtt driver"
    
    This reverts commit c55d63a16c0ec58d73da9f186c7a09c4120de8f0 because
    it depends on change Ie82e625fcce7d5b5b794a46f6456ccff1dc5ec3e which
    is being reverted.
    
    Change-Id: I6a3b33f81668072093ebff56991543169e91d226
    
  - fix tox python3 overrides
    
    We want to default to running all tox environments under python 3, so
    set the basepython value in each environment.
    
    We do not want to specify a minor version number, because we do not
    want to have to update the file every time we upgrade python.
    
    We do not want to set the override once in testenv, because that
    breaks the more specific versions used in default environments like
    py35 and py36.
    
    Change-Id: If74556d3489092ea33d82224d1c1695c182b6bea
    
  - mark FilterCriterion title as a mandatory field
    
    Change-Id: I0cefda369556817303e976d539c3187679792d73
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - mark worklist filter_criteria as a required field
    
    Change-Id: I7fd4c3251bc07ccab5ff94da9673b144266f8cbf
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - use required enums to validate 'type' args
    
    Change-Id: Id7c6a4eed2b6a3a55502b8bbd8d8fbfad16abb45
    Signed-off-by: Doug Hellmann <doug@doughellmann.com>
    
  - Merge "Document some usage instructions for a freshly deployed dev instance"
  - Merge "Make it impossible to create a userless private story"
  - Merge "Add configurable notification subscriber and mqtt driver"
  - Merge "Add MQTT notification publisher"
  - Merge "Make notification driver configurable"
  - Add articles to email template
    
    This Englishes better.
    
    Change-Id: I3de4bdc57bdb517aaa893a05b288ac8026b8a0c7
    
  - Gate fix: Cap hacking to avoid gate failure
    
    hacking is not capped in g-r and it is in
    blacklist for requirement as hacking new version
    can break the gate jobs.
    
    Hacking can break gate jobs because of various
    reasons:
    - There might be new rule addition in hacking
    - Some rules becomes default from non-default
    - Updates in pycodestyle etc
    
    That was the main reason it was not added in g-r
    auto sync also. Most of the project maintained the
    compatible and cap the hacking version in
    test-requirements.txt and update to new version when
    project is ready. Bumping new version might need code
    fix also on project side depends on what new in that
    version.
    
    If project does not have cap the hacking version then,
    there is possibility of gate failure whenever new hacking
    version is released by QA team.
    
    Example of such failure in recent release of hacking 1.1.0
    - http://lists.openstack.org/pipermail/openstack-dev/2018-May/130282.html
    
    Change-Id: I50448c8cd470fbb5266a728a9b5ed2e46e1448a2
    
  - Document some usage instructions for a freshly deployed dev instance
    
    Change-Id: I3b12c574274daefb8386bb81b3b7aeeea7be8bd7
    
  - Add configurable notification subscriber and mqtt driver
    
    The previous commits adds support for a configurable notification driver
    and an mqtt publisher implementation. The subscriber interface was left
    hard coded to the pika implementation and respecting the configurable
    driver config setting was left as a future item. This commit addresses
    this and adds the missing subscriber interface for the configurable
    notification drivers with an mqtt implementation.
    
    Change-Id: I97aafc5fd94ac1a8c126fa1f463e33e772bf87f0
    
  - Add MQTT notification publisher
    
    This commit adds an alternate notification publisher driver for mqtt.
    The intent here is to use this driver with firehose.openstack.org, which
    is infra's unified event bus. [1] To use this driver you first need to
    set it as the notification driver with the driver option in the
    notifications config group. Then set the required config options in the
    mqtt_notifications section.
    
    [1] https://docs.openstack.org/infra/system-config/firehose.html
    
    Change-Id: Ie82e625fcce7d5b5b794a46f6456ccff1dc5ec3e
    
  - Make notification driver configurable
    
    This commit makes the notification driver configurable. Currently there
    is only one notification backend available, rabbit/pika, but to support
    emitting notifications to firehose.openstack.org in the future a MQTT
    backend will be added. This commit lays to groundwork for doing this.
    Note this only effects the notification publisher, the subscriber calls
    will be updated in the future. (there is only one use of the subscriber
    currently so that is updated manually to directly use the new path)
    
    The external api for registering a pecan notification hook remains the
    same, but the underlying publish call being made is set by the
    configuration option. This enables a different publish() method to be
    called depending on configuration.
    
    To facilitate this change the current pika notification options are
    deprecated in the 'notifications' group and are instead added to the
    'pika-notifications' configuration group. This will be removed in the
    future. A new 'driver' option is added to the ntofications group to
    specify which driver to use which defaults to the current pika driver.
    
    Change-Id: I5235ae4368f8bff13c767b87ced83173d52b5155
    
  - Make it impossible to create a userless private story
    
    This patch prevents people from creating private stories which no users
    can access. If no users are specified, it will automatically add the
    current user to the list of users for the story.
    
    Change-Id: Ibaedd23193297a0a9d697e9d97474b4a2c4db1c5
    
  - Add a test openid server
    
    This can be useful for local development.  It always authenticates
    successfully as the user/identity provided on the command line.
    
    Change-Id: I1282b7fd98972b24d98f46680d8e2d335687667c