Updated openstack/openstack Project: openstack/oslo.config  78b9c029c718889a1080a416c5775413f7c1b5a6
Fix bad exception for StrOpt with invalid choice value

If there's a StrOpt with name foo and say choices ['bar', 'baz'] and the
config file has a bad value for foo (say 'boo'), then the end user
will see:
NoSuchOptError: no such option: foo

Which gives the wrong impression that somehow the foo was never registered
which is wrong!

They should see this instead:
oslo_config.cfg.ConfigFileValueError: Value for option foo is not
valid: Valid values are [bar, baz], but found 'boo'

Closes-Bug: #1499074
Change-Id: I694d8aa99c861c7b47bae77ef12f435b7c3712ab