Update git submodules
* Update diskimage-builder from branch 'master'
  - Make sure DIB_DEBUG_TRACE has a default value
    
    After the introduction of 'Add output for mis-configured element
    scripts' we started seeing CI failures in tripleo where
    instack-undercloud is being used (rocky/queens):
    
      /usr/lib/python2.7/site-packages/diskimage_builder/lib/dib-run-parts: line 108: DIB_DEBUG_TRACE: unbound variable
      INFO: 2019-12-02 16:24:33,423 -- ############### End stdout/stderr logging ###############
      ERROR: 2019-12-02 16:24:33,423 -- Hook FAILED.
    
    Let's make sure that by default the env variable is set
    to 0.
    
    Change-Id: I38c76c0edee436f1e7dd0c9a868cea1e6ee3271d
    Closes-Bug: #1854904