Update git submodules
* Update zuul from branch 'master'
  - Merge "Fix missing min_avail_mem in memory governor"
  - Fix missing min_avail_mem in memory governor
    
    Somehow the memory governor made it into without the needed
    min_avail_mem variable. Add that to prevent repeated crashing of the
    governor thread [1].
    
    [1] Trace:
    2018-02-01 14:42:15,533 ERROR zuul.ExecutorServer: Exception in governor thread:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1959, in run_governor
        self.manageLoad()
      File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1975, in manageLoad
        elif avail_mem_pct < self.min_avail_mem:
    AttributeError: 'ExecutorServer' object has no attribute 'min_avail_mem'
    
    Change-Id: I9af5ba3ef3200f1a8d1bdb41906a1b77ef4e7f55