Updated openstack/openstack Project: openstack/nova  ec2ffec62d86bae09f1f9af2db65948bf9c43b9e
libvirt: check for interface when detach_interface fails

When using Neutron and deleting an instance, we race against
deleting the domain and Neutron sending a vif-deleted event
which triggers a call to detach_interface. If the network
device is not found when we go to detach it from the config,
libvirt raises an error like:

libvirtError: operation failed: no matching network device was found

Unfortunately libvirt does not have a unique error code for this
and the error message is translatable, so we can't key off of it
to check if the failure is just due to the device not being found.

This change adds a method to the guest object to lookup the interface
device config by MAC address and if not found, we simply log a warning
rather than tracing an error for a case that we can expect when using
Neutron.

Closes-Bug: #1536671

Change-Id: I8ae352ff3eeb760c97d1a6fa9d7a59e881d7aea1