Update git submodules
* Update osc-lib from branch 'master'
  to 2b7a679a4296c45fbc2fea152e3b51029a201143
  - Fix lower-constraints job
    
    pip 20.3 finally includes a proper dependency resolver. Its use is
    causing the following error messages on the lower-constraints job:
    
      ERROR: Could not find a version that satisfies the requirement
      hacking<3.1.0,>=3.0.1
      ERROR: No matching distribution found for hacking<3.1.0,>=3.0.1
    
    Resolve this by moving the 'hacking' and 'flake8-import-order'
    dependencies from 'test-requirements.txt' to 'tox.ini' since we don't
    need to use our constraints machinery for linters.
    
    While we're here, also drop 'bandit' from 'test-requirements.txt'. This
    was introduced in change I691829c1224557d1d239c9f665ac539d0f13c4d3 but
    commit f78173f0e1daabccbbe0230fe93df98ac971afbc (there's no change ID)
    removed the 'bandit' testenv from 'tox.ini' meaning we no longer use
    this anywhere.
    
    Change-Id: I744efd75c4cbf8c630c5f95dc254acff581be959
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>