Update git submodules
* Update cinder from branch 'master'
  - Merge "Google backup support client 1.8.2"
  - Google backup support client 1.8.2
    
    Version 1.8.0 of the google-api-python-client package included the
    classic __version__ attribute that allowed us to know what version the
    client was running, but that's no longer the case on version 1.8.2.
    
    Which results in the following error when we use that library:
    
     AttributeError: module 'googleapiclient' has no attribute '__version__'
    
    Since we still need to know the version of the client we are running to
    determine the library to use for credentials we change how we get the
    version of the package.
    
    Now we use pkg_resources to get the version, which works even when
    there's no __version__ attribute.
    
    Change-Id: I24b1cf52c994a5fa0117fc2780d415981c596583