Update git submodules
* Update openstack-helm from branch 'master'
  to afd94b8425d17d4d19516b1414c9572b37067efc
  - Merge "Fix transport_url"
  - Fix transport_url
    
    We have observed that omitting statefulset
    on the olso_messaging values can cause octavia
    workers to ocasionally fail with:
    
    AMQP server on rabbitmq.openstack.svc.cluster.local:5672 is unreachable:
    [Errno 104] Connection reset by peer. Trying again in 1 seconds.:
    ConnectionResetError: [Errno 104] Connection reset by peer
    
    This patch aims to keep the pattern used on the other serivces
    to setup the transport_url that includes all pods in the statefulset.
    
    Change-Id: I1905dc8f443929a03786fd01d6cf4e50ff5d3cb2