Update git submodules
* Update blazar from branch 'master'
  to b1841dc4b90d9127884379d4fe1cccf99c7a579c
  - Fix use of legacy Alembic API
    
    The `name` keyword argument for Operations.alter_column() has been
    deprecated since version 0.8. It was finally removed in Alembic 1.5.0,
    causing the following error during installation of Blazar:
    
    TypeError: alter_column() got multiple values for keyword argument 'name'
    
    Change-Id: I05541da4d87575f65d8e78f0fc54bd415328b9f2
    Closes-Bug: #1912502