Update git submodules
* Update python-swiftclient from branch 'master'
  to 00f5b892273a0f88c368b71404006c53bb6ac749
  - CI: Drop swiftclient-swift-functional-py2 job
    
    It got busted somewhere between 2022-01-15 and 2022-02-11; looks like
    needing to override devstack to install on bionic finally caught up with
    us. ;-)
    
    FWIW, it fails down in stack.sh while trying to pip install grpcio:
    
       commands.CommandError: We expect a missing `_needs_stub` attribute
       from older versions of setuptools. Consider upgrading setuptools.
    
    Change-Id: Iff9094e9dd7a3d0bcdb0dee3b08fa5b61c9186d0