Update git submodules
* Update python-cyborgclient from branch 'master'
  to 2a674e6576e35746c86d914b4fe1891e8a726125
  - bug fix: tox wrongly install client from repo path.
    
    This will cause version conflict:
    
    Obtaining file:///opt/stack/python-cyborgclient
    ERROR: Could not satisfy constraints for 'python-cyborgclient': installation from path or url cannot be constrained to a version
    
    or
    
    ERROR: Could not find a version that satisfies the requirement python-cyborgclient 1.3.1.dev1
    ERROR: No matching distribution found for python-cyborgclient 1.3.1.dev1
    
    Change-Id: I521f880606fa1aab25cd85875153275c5dd2e125