Update git submodules
* Update tenks from branch 'master'
  - Fix ansible lint and ubuntu deployment
    
    This patch combines two different fixes, since both are required to get
    CI tests passing.
    
    1. Fix ansible lint 301 with ip link set dev <device> up
    
    This resolves:
    
    [301] Commands should not change things if nothing needs doing
    /home/will/code/tenks/ansible/roles/veth-pair/tasks/present.yml:13
    Task/Handler: Bring each end of veth up
    
    ip link set dev <device> up is idempotent:
    
    https://github.com/shemminger/iproute2/blob/707f612c00a91fe3c17d7af5319e423545a496c5/ip/iplink.c#L264
    https://github.com/torvalds/linux/blob/63bdf4284c38a48af21745ceb148a087b190cd21/net/core/rtnetlink.c#L2485
    https://github.com/torvalds/linux/blob/63bdf4284c38a48af21745ceb148a087b190cd21/net/core/dev.c#L7632
    https://github.com/torvalds/linux/blob/63bdf4284c38a48af21745ceb148a087b190cd21/net/core/dev.c#L7563
    
    2. Add pkg-config as an explicit dependency
    
    This is to fix the following error:
    
    Exception: pkg-config binary is required to compile libvirt-python
    
    TrivialFix
    
    Change-Id: I9a2db7b5f2cbdcb64227bd4f1de245bcb7f71f5b