Updated openstack/openstack Project: openstack/python-glanceclient  3338ed91d4b9a0a33885d48969d71de0d30bed7e
Downloading image with --progress fails for python3

Downloading image with --progress fails for python3 with,
TypeError: 'IterableWithLength' object is not an iterator. This
is because IterableWithLength class does not implemented python3
compatible __next__ method.

Added __next__ method for python3 compatibility.

Change-Id: Ic2114180fac26e9a60678f06612be733e8671bdb
Closes-Bug: #1671365