Update git submodules
* Update kolla from branch 'master'
  to b6e057d694d90d50ea278411d0edf20afe427e13
  - Use distro provided GRUB efi
    
    Use distro provided GRUB efi instead of creating it like ironic GRUB
    setup doc[1]. This avoids below ubuntu ironic-python-agent images PXE
    booting failure.
    ----------
    error: invalid magic number.
    error: you need to load the kernel first.
    
    Press any key to continue...
    ----------
    
    This also fixes x86_64 uefi pxe booting issue by setting up GRUB efi
    for x86_64.
    
    Besides, GRUB setup only needs to do once at bootstrap stage.
    
    [1]:
    https://docs.openstack.org/ironic/train/install/configure-pxe.html#uefi-pxe-GRUB-setup
    
    Closes-Bug: #1879265
    Change-Id: I8be5bdf5f1a62751aefe6bd0959e8f558fcfe591