Updated openstack/openstack Project: openstack/heat  d364e36c9014aff31431557e2fc4ff42f354af3f
Use assertIn and assertNotIn

Tests should use:
  self.assertIn(value, list)
  self.assertNotIn(value, list)

instead of:
  self.assertTrue(value in list)
  self.assertFalse(value in list)

because assertIn and assertNotIn raise more meaningful errors:
  self.assertIn(3, [1, 2]
  >>> MismatchError: 3 not in [1, 2]

  self.assertTrue(3 in [1, 2])
  >>> AssertionError: False is not true

Change-Id: I4b24b6e00bf26c0a68a9d8f9eb9185c435791dfc
Closes-Bug: #1510007