Update git submodules
* Update openstack-ansible-os_nova from branch 'master'
  - Merge "Install netcat-openbsd for live migration"
  - Install netcat-openbsd for live migration
    
    netcat-openbsd is required on Debian/Ubuntu in order for live migration
    to function. If it is not installed, you get an error that looks like:
    
    libvirt.libvirtError: operation failed: Failed to connect to remote libvirt URI qemu+ssh://nova@hv1/system?no_verify=1&keyfile=/var/lib/nova/.ssh/id_rsa: End of file while reading data:
    sh: 1: nc: not found: Input/output error
    2020-05-19 22:13:32.553 4511 ERROR nova.virt.libvirt.driver [-] [instance: b5a313c0-326c-4e3f-bec4-22926289999f] Migration operation has aborted
    
    This was originally fixed in [1] and then accidentally reverted in a
    package cleanup[2].
    
    [1] https://review.opendev.org/#/c/666759/
    [2] https://review.opendev.org/#/c/662585/
    
    Closes-Bug: #1833644
    
    Change-Id: Ia2747142e6253b286d36d8c71a263ef7ed01341d