Updated openstack/openstack Project: openstack/neutron  de59e1c198a201781052cae0b48b344911fae378
DVR: Do not check HA state on DVR-only routers

Trying to check HA state on a DVR-only compute node
can trigger:

AttributeError: 'DvrLocalRouter' object has no attribute 'ha_state'

Also moved the mode assignment outside of the loops
since it only needs to be done once.

Co-Authored-By: Sean Redmond <sean.redmond1@gmail.com>
Closes-bug: #1691427
Change-Id: I3e48e06e76325939fbc9533b0198924bc96d600e