Update git submodules
* Update python-manilaclient from branch 'master'
  to 8f60f6928f091df6c0cb1e267508d03b1d55f699
  - Fix test to not check service updated_at time
    
    When listing and verifying services, it's possible
    that the service record has been updated within
    manila, and the "updated_at" timestamp varies. So
    lets not expect it to be the same between the prior
    listing and the verification to avoid a mismatch
    error:
    
    ft1.1: manilaclient.tests.functional.osc.test_share_services.ShareServicesTestCase.test_services_listtesttools.testresult.real._StringException: Traceback (most recent call last):
    <snip></snap>
    testtools.matchers._impl.MismatchError: '2022-06-29T20:40:16.852331' != '2022-06-29T20:40:26.856247'
    
    Change-Id: I477ca712edd5d54b2dcd5202848aec564002fabb
    Signed-off-by: Goutham Pacha Ravi <gouthampravi@gmail.com>