Update git submodules
* Update tripleo-upgrade from branch 'master'
  - Merge "Ensure bc package is installed for l3 ping tests."
  - Ensure bc package is installed for l3 ping tests.
    
    When running the l3 ping tests we get the following
    error: bc: command not found.
    Let's make sure the package is present in the system
    when generating the scripts.
    
    Change-Id: I32ad402dc7e42d85e574bf1273664bc7d6d1f9a5