Update git submodules
* Update rpm-packaging from branch 'master'
  - Merge "freezer-api: add missing BuildRequires"
  - freezer-api: add missing BuildRequires
    
    This fixes the following error from CI:
    /usr/bin/python3 setup.py test
    [...]
    error: Could not find suitable distribution for Requirement.parse('astroid==2.1.0')
    
    Change-Id: I3161c69b79ec55ceb9bdf935fd0df37a65c1ec6d