Update git submodules
* Update puppet-manila from branch 'master'
  to cbac1af980950f577b5947d99ec971eec2de1469
  - Merge "Accept a string value for enabled_share_backends"
  - Accept a string value for enabled_share_backends
    
    Currently using a string value for the enabled_share_backends parameter
    causes the following error, which is not quite clear for users.
    ~~~
    Error: Evaluation Error: Error while evaluating a Function Call, 'join'
    parameter 'arg' expects an Array value, got String ...
    ~~~
    
    This change allows usage of a single string value, as is done for
    the other ListOpts, because there is no logic which actually requires
    an array value.
    
    Change-Id: I786e5d477131fa60502a9985f0db4b19f418ce9b