Updated openstack/openstack Project: openstack/nova  a018826f40e1dba9feafa38d0aad4644400e89ec
Tests: Don't require binding to port 4444

If some other process is listening on port 4444,
test_server_pool_waitall will fail with:

error: [Errno 98] Address already in use

This test doesn't require use of this specific port,
so let it pick an unused port to avoid this failure.

Closes-Bug: #1421759

Change-Id: Ib92797e41a2bd37a59d3465b4764f00c1d9c2444