Updated openstack/openstack Project: openstack/zaqar  f722430fd48dc59877e5e2d783aff5df23e75f20
Fix bug in mongodb backend for dead letter queue

In the function{ClaimController:create} for mongodb backend, there
is an error when a message is inserted to the dead letter
queue.Because a mongodb collection(messages) is shared by
many queues, we need to delete first and then insert,
otherwise insert_one will cause the following error:
pymongo.errors.DuplicateKeyError: insertDocument :: caused by ::
11000 E11000 duplicate key error index: admin.test.$_id_  dup key:
{ : ObjectId('xxxxxxxxxxxxxxxxxxxxxx') }

Depends-On: I1ee88a8963e2bc80172710da5ab60313952495e4
Depends-On: I8c3642f3883ecc68853735636fc3a748b9c780b6
Closes-Bug: #1707814
Change-Id: If7824d135ecd6999716954e6fa4fa000434c4ed4