Updated openstack/openstack Project: openstack-infra/zuul  30a433b202a65dd7ddcc6eebf4d34041f6743740
Pin paramiko < 2.0.0

We need to pin parmakio until we fix an expection in
zuul/connection/gerrit.py client.load_system_host_keys()

Traceback (most recent call last):
  File "/opt/ansible-role-zuul/git/openstack-infra/zuul/zuul/connection/gerrit.py", line 168, in _run
    client.load_system_host_keys()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 101, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/usr/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/lib/python2.7/site-packages/paramiko/hostkeys.py", line 331, in from_line
    key = RSAKey(data=decodebytes(key))
  File "/usr/lib/python2.7/site-packages/paramiko/rsakey.py", line 58, in __init__
    ).public_key(default_backend())
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

Change-Id: Ifc12a1ec9f26c0b236ed00e128b707c6fba58b1e
Signed-off-by: Paul Belanger <pabelanger@redhat.com>