Update git submodules
* Update oslo.limit from branch 'master'
  to f1ce4022d6d0c7b775dddbf97e1cb0e6194d4dba
  - Handle missing endpoint, region, service
    
    SDK will not return 'ResourceNotFound' for a list operation (like
    'services'): it will only do that for a fetch operation (like
    'get_service'):
    
      >>> import openstack
      >>> conn = openstack.connect(cloud='devstack-admin')
      >>> set(conn.identity.services(name='foo'))
      []
      >>> conn.identity.get_service('foo')
      Traceback (most recent call last):
        ...
      openstack.exceptions.NotFoundException: No Service found for foo: Client Error for url: http://example.com/identity/v3/services/foo, Could not find service: foo.
    
    Correct our assumptions here.
    
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
    Change-Id: I21bfa283c95ace092bc154e28f5d584d027c29f9