Update git submodules
* Update python-tripleoclient from branch 'master'
  to ec8e13423449841ec701086d50e7414afc7792bf
  - Heat Launcher - bracket IPv6 in db connection URI
    
    In the database connection URI ensure IPv6 address is wrapped in
    brackets. Without this a port number is assumed and error is raised:
      ERROR: invalid literal for int() with base 10: 'dead:beef:4::3'
    
    Related-Bug: #1983121
    Change-Id: I37fda2aa161120369d0e3734b9485c27cb59846c