Update git submodules
* Update puppet-nova from branch 'master'
  - Merge "Fix duplicated declaration when the deprecated parameter is used"
  - Fix duplicated declaration when the deprecated parameter is used
    
    This patch fixes duplicaed declaration of the same parameter when
    nova::compute::ironic::max_concurrent_builds is used.
    
    Error: Evaluation Error: Error while evaluating a Resource Statement,
    Duplicate declaration: Nova_config[DEFAULT/max_concurrent_builds] is
    already declared at ...
    
    Change-Id: I8ac22df2bf0b6ea56c24711ca09082e6b7e1a7b4