Update git submodules
* Update cinder from branch 'master'
  - Fix upload volume to glance
    
    We were missing the 'compress' parameter in the upload_volume method,
    yet we were passing it on the driver, which meant that the call would
    always fail with:
    
      TypeError: upload_volume() got an unexpected keyword argument
      'compress'
    
    Related-Bug: #1824821
    Closes-Bug: #1839069
    Change-Id: Ibe9a0e78ab452c54cc3f1da1f4377034190dd14e