Update git submodules
* Update charm-nova-cloud-controller from branch 'master'
  to 499cfbab9561057533906c2ac9e5e4cc8eb290cd
  - Merge "Fix issues seen with latest netaddr library"
  - Fix issues seen with latest netaddr library
    
    There are a few unit tests failing with this error:
    
      TypeError: inet_pton() argument 2 must be str, not MagicMock
    
    The reason is there is no default return value from the mocking
    of the internal network.
    
    Correctly mock "resolve_address" to be an IP address as
    is done in other tests, making netaddr happy.
    
    TrivialFix
    
    Change-Id: I5151097a53651db0ff054b6649326c8a03e56ddd