Update git submodules
* Update python-openstackclient from branch 'master'
  to d9b95d776aec9df648ab05fffbcdc7be87694dc1
  - Merge "Fix tests on Python 3.12"
  - Fix tests on Python 3.12
    
    We were seeing the following test failures on Python 3.12:
    
      openstackclient.tests.unit.common.test_module.TestModuleList.test_module_list_all
      openstackclient.tests.unit.common.test_module.TestModuleList.test_module_list_no_options
    
    Both failures were caused by missing attributes of 'sys', e.g.
    
      AttributeError: module 'sys' has no attribute 'builtin_module_names'
    
    Fix this by exposing the real 'sys' module as part of our mock of
    'sys.modules'.
    
    Change-Id: I17391a46f08896f49dccaf75ad685dab1375a03d
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>