Updated openstack/openstack Project: openstack/cinder  fc99064856091536e6606c943fa23b94ada372de
Fix NoneType has no attribute get

If volume_type is None and then create volumes with allow-multiattach,
Cinder-schduler will raise error:

AttributeError: 'NoneType' object has no attribute 'get'

Change-Id: Ied42d13b642617dd239ea92c019354b90657821a
Closes-bug: #1683431