Updated openstack/openstack Project: openstack/oslo.vmware  2e31f9bdc5a6aa5c70450a10d7425a36927bf9d7
_trunc_id to check if the session_id is not None

The current code will raise a TypeError if the session_id is None:
TypeError: 'NoneType' object has no attribute '__getitem__'
This will happen specifically when _trunc_id is called by
_is_current_session_active.

This patch adds a check to make sure session_id is not None.

Change-Id: Ifc3cc236f36df1a140b864e53e9eb538797e5580