Update git submodules
* Update python-tripleoclient from branch 'master'
  - Merge "Fix unit test_get_image timezone issue"
  - Fix unit test_get_image timezone issue
    
    tripleoclient unit tests fail due to timezone no UTC.
    TestFileImageClientAdapter.test_get_image
    MismatchError: '2019-11-14T01:33:39' != '2019-11-14T02:33:39'
    
    Closes-Bug: #1864828
    Change-Id: I076f786e8d5ca756e5d73d04e84c4084ec24c579