Update git submodules
* Update neutron-fwaas from branch 'master'
  to 6911bd07bc53c7137ab58c53c3330c3ccc8ba8cd
  - Don't notify/access non-existent ports
    
    When calling need_to_notify() with a list of port ids where one port
    does not exist (could have been concurrently deleted) we'll get a None
    object and with that an AttributeError. To prevent this we skip
    notification checks for ports which we can't find in the database.
    
    Stacktrace without the fix:
    
    AttributeError: 'NoneType' object has no attribute 'get'
      File "neutron_lib/callbacks/manager.py", line 189, in _notify_loop
        callback.method(resource, event, trigger, payload=payload)
      File "neutron_fwaas/services/logapi/common/fwg_callback.py", line 43, in handle_event
        if self.need_to_notify(context, ports_delta):
      File "neutron_fwaas/services/logapi/common/fwg_callback.py", line 57, in need_to_notify
        device_owner = port.get('device_owner', '')
    
    Change-Id: I56256c776efec21ebb2a212085840bfbd03cfe50
    Closes-Bug: #2120429
    Signed-off-by: Sebastian Lohff <sebastian.lohff@sap.com>