Updated openstack/openstack Project: openstack/neutron-lbaas  85581ba5c72c3e91b931b661c7cae3cd711032c1
Use assert(Not)In instead of assertTrue/False

Neutron tests should use:

self.assertIn(value, list) and
self.assertNotIn(value, list)

instead of:

self.assertTrue(value in list) and
self.assertFalse(value in list)

because assertIn and assertNotIn raise more meaningful errors:

self.assertIn(3, [1, 2])
>>> MismatchError: 3 not in [1, 2]

self.assertTrue(3 in [1, 2])
>>> AssertionError: False is not true

To enforce this improvement, this patch is created.

Change-Id: I4a05ad5a5ff9674dd94cff8b11585fd39dc264b3
Related-Bug: #1218713