Update git submodules
* Update placement from branch 'master'
  to 5e61583504c4911ac862e1d0f2d7eb79e37066d0
  - Merge "Fix compatibility with gabbi 4.x"
  - Fix compatibility with gabbi 4.x
    
    gabbi 4.x significantly reworked how interception happens [1]. One side
    effect of this change is interception callable is now invoked during
    test construction (via client creation [2], which is called by test
    suite creation [3]) rather than during test execution. In placement, the
    interception callable used is our WSGI app. This requires oslo.conf's
    CONF singleton to be initialized first else we see errors like so:
    
      =========================
      Failures during discovery
      =========================
      --- import errors ---
      Failed to call load_tests:
      Traceback (most recent call last):
        ...
        File ".../placement/placement/deploy.py", line 47, in deploy
          if conf.api.auth_strategy == 'noauth2':
             ^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'api'
    
    Because gabbi "creates" tests via the custom suite maker, it does not
    appear to be possible to inject the Config fixture earlier in test
    without breaking 'APIFixture' (which is currently responsible for doing
    this). Instead, we opt to implement a "lazy" intercept function which
    will only creation the app when actually invoked by a test.
    
    [1] https://github.com/cdent/gabbi/commit/4d9d3b4
    [2] https://github.com/cdent/gabbi/commit/4d9d3b4#diff-387442266e6c9ad9359689c282903e5b1e406bb31db94c5732384f8fb4ce45f2R36-R44
    [3] https://github.com/cdent/gabbi/blob/4d9d3b4/gabbi/suitemaker.py#L59-L89
    
    Change-Id: Ibf3a87bf986ed158dd049e72a329f643a87630e7
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>