Update git submodules
* Update cinder from branch 'master'
  - Merge "Fix Snapshot object metadata loading"
  - Fix Snapshot object metadata loading
    
    The Snapshot object will fail to correctly load
    metadata.  Initialize the object fully so that
    obj_what_changed() works as intended.
    
    This prevents the error:
       AttributeError: 'Snapshot' object has no
       attribute '_obj_metadata'
    
    Closes-Bug: #1805790
    
    Co-Author: Gorka Eguileor <geguileo@redhat.com>
    Change-Id: Idee4836ee3e4f9b9f4099e7a1a3d7a4bada3f7b8