Updated openstack/openstack Project: openstack/requirements  d502a6e23a26c60cb699b3aa5c11e010d8eceb13
No-python3 classifier for python-memcached

python-memcached doesn't support py34. keystonemiddleware py34 unit
tests fail with an error using python-memcached:

...
  File "/opt/stack/keystonemiddleware/.tox/py34/lib/python3.4/site-packages/memcache.py", line 1299, in send_cmd
    self.socket.sendall(cmd + '\r\n')
TypeError: 'str' does not support the buffer interface

This issue is reported to python-memcached:
https://github.com/linsomniac/python-memcached/issues/70

There's a pull request:
https://github.com/linsomniac/python-memcached/pull/67

Looks like python-memcached is an abandoned project.

Change-Id: Ie3dacedc9a355be914fe30f16dc40c58f779c46b