Updated openstack/openstack Project: openstack/python-novaclient  e62d1e50b785118c9cb34d1a98875f1ea191d653
Better handle key=value pair not being key=value

Previously, --block-device and --ephemeral would error out with an
insctrutable (to the user) error message if one of the key=value pair
it expects wasn't actually key=value, for instance:

nova --block-device 995abd81-2626-413c-9af6-51f105fab214,tag=foo \
     --image CirrOS --flavor custom my_instance

ValueError: dictionary update sequence element #0 has length 1; 2 is
required

This patch makes the error message clearer.

Change-Id: I2dd5dd805df2b0382b015dc625205119d7d0b03b