Update git submodules
* Update cinder from branch 'master'
  to 25043468d3921a23eadd31df47f3d98918465ebf
  - Merge "Fix mypy job"
  - Fix mypy job
    
    With change Ia5950c2dc6186b721c9c9cfc4629d72e3b731889, we added
    some changes that violated the mypy syntax and the mypy job started
    failing due to the following reasons:
    
    1) cinder/volume/volume_utils.py:1129:33: error: Argument 1 to
    "as_int" has incompatible type "Union[str, int, None]";
    expected "Union[int, float, str]"
    
    If we look at method "as_int" definition[1], it accepts int, float
    and str types but virtual_size could be None
    To fix this, Now we only use as_int when virtual_size is not None.
    
    2) cinder/volume/volume_utils.py:1132:40: error: Argument 3 to
    "check_virtual_size" has incompatible type "Union[str, int]";
    expected "str"
    
    The definition of image_meta dict is dict[str, Union[str, int]]
    which means the values are either str or int. Also, the method
    "check_virtual_size" expects a str value[2].
    
    To clear this ambiguity, we typed image_id as string value.
    
    [1] https://opendev.org/openstack/cinder/src/commit/7b424fcdcb6cc3cb2d11da04cb6b7744cb13fe20/cinder/utils.py#L119
    [2] https://opendev.org/openstack/cinder/src/commit/7b424fcdcb6cc3cb2d11da04cb6b7744cb13fe20/cinder/image/image_utils.py#L914
    
    Change-Id: Ibdb2d72e318bf448dfa2e70bc9df721e41aff730