Updated openstack/openstack Project: openstack/nova-specs  445ea946558b5e1c663d18e3fe1d9849487a09ad
Add test to check spec directories

When submitting specs one very common mistake is to submit it to
specs/liberty/ instead of specs/liberty/approved/. Add a new test to
make sure submitted specs are not in the wrong directory.

Test output:

MismatchError: 'foo.rst' not in
['redirects', 'implemented', 'approved']: Found unexpected file in
'specs/liberty', specs should be submitted to 'specs/liberty/approved'

Change-Id: I27a532dc0b85d712698821d77555d2aeb57e83a1