Update git submodules
* Update rally-openstack from branch 'master'
  to 35a6046e8cb2a6b9bf5d50e669dc5e27825972eb
  - Merge "Stop using removed option [scenario]/img_dir"
  - Stop using removed option [scenario]/img_dir
    
    The [scenario]/img_dir configuration option was removed from tempest in
    version 27.0.0. This makes test_minimum_basic_scenario fail with:
    
    Traceback (most recent call last):
      File "/home/ubuntu/.rally/verification/verifier-434bee71-a8c0-480d-a511-11a2bc1bda97/repo/tempest/common/utils/__init__.py", line 70, in wrapper
        return f(*func_args, **func_kwargs)
      File "/home/ubuntu/.rally/verification/verifier-434bee71-a8c0-480d-a511-11a2bc1bda97/repo/tempest/scenario/test_minimum_basic.py", line 109, in test_minimum_basic_scenario
        image = self.image_create()
      File "/home/ubuntu/.rally/verification/verifier-434bee71-a8c0-480d-a511-11a2bc1bda97/repo/tempest/scenario/manager.py", line 769, in image_create
        with open(img_path, 'rb') as image_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'tempest-image'
    
    Use [scenario]/img_file with a full path to the image instead.
    
    + skip several tests at CI
    
    Co-Authored-By: Andrey Kurilin <andr.kurilin@gmail.com>
    
    Change-Id: I9b9f339e758547e059080b247c8bd8bcf1b749ee
    Closes-Bug: #1928807