Update git submodules
* Update octavia from branch 'master'
  to 7221e6f682c94302ab58d95645bccb956c23daf1
  - Merge "Fixed missing mock in TestAmphoraAgentCMD.test_main"
  - Fixed missing mock in TestAmphoraAgentCMD.test_main
    
    The lack of mock for multiprocessing.Manager in this test seems to
    trigger random crashes when running the next test on the same process.
    It also displays a backtrace related to multiprocessing:
    
    Exception ignored in: <function _ConnectionBase.__del__ at 0x7f0cb663b400>
    Traceback (most recent call last):
      File /usr/lib/python3.10/multiprocessing/connection.py, line 132, in __del__
        self._close()
      File /usr/lib/python3.10/multiprocessing/connection.py, line 361, in _close
        _close(self._handle)
    OSError: [Errno 9] Bad file descriptor
    
    Change-Id: I7c699b59954acd5fe1c56e51e8b2c55fba09cdd8
    Closes-Bug: #2136683
    Signed-off-by: Gregory Thiemonge <gthiemon@redhat.com>