Update git submodules
* Update trove from branch 'master'
  to 3468240fae3dc9678f36c9955eb274af01775b73
  - Merge "Fix replication detach error"
  - Fix replication detach error
    
    TypeError: tuple indices must be integers or slices, not str
    
    this is caused by the new version of the sqlachemy library.
    
    Change-Id: I76166f901f961a18ad4297d04e1a75a59b059e23