Update git submodules
* Update pyeclib from branch 'master'
  to 83cd0948d1a9b29af63c69980af3870d89e0dbda
  - Relax test_get_metadata_memory_usage a little
    
    I'm getting tired of seeing CI failures like
    
       AssertionError: 89804 != 89932 : Memory usage is increased
       unexpectedly 89804 -> 89932
    
    When we're doing 400,000 iterations, I don't really care if Python's
    internals are sometimes causing the numbers not to line up *exactly*.
    
    Change-Id: I60812d443a6f823a5c357a1962e355454e1b6488
    Signed-off-by: Tim Burke <tim.burke@gmail.com>