Update git submodules
* Update tripleo-heat-templates from branch 'master'
  - include gcc,python36-devel in bindep, for tests
    
    as of https://review.opendev.org/#/c/751112/
    py36 tests fail w/
        psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
         #include <Python.h>
                  ^~~~~~~~~~
        compilation terminated.
        error: command 'gcc' failed with exit status 1
    
    Change-Id: Ib033f31c9dfad8e4006ce3a476bfddf4e0ba0078