Updated openstack/openstack Project: openstack/designate  9fe583fcb217b3ebfeb8933e3acee831c490cba8
Use assertIn and assertNotIn

Tests should use:
  self.assertIn(value, list)
  self.assertNotIn(value, list)

instead of:
  self.assertTrue(value in list)
  self.assertFalse(value in list)

because assertIn and assertNotIn raise more meaningful errors:
  self.assertIn(3, [1, 2]
  >>> MismatchError: 3 not in [1, 2]

  self.assertTrue(3 in [1, 2])
  >>> AssertionError: False is not true

Change-Id: I38bf94b50dbfff8aa075b8ecbb5b4d03a2cdf2e2
Closes-Bug: #1510007