Updated openstack/openstack Project: openstack-infra/zuul  6444d7b9777e5fdbdacb4c0e34da7f9904d60bda
Add pillow dependency libjpeg-dev to bindep

 This should fix the error we're seeing in gate jobs:
 ValueError: jpeg is required unless explicitly disabled
 using --disable-jpeg, aborting

Change-Id: I686b21e452aad2dfb9358360137070f58dde3882