Updated openstack/openstack Project: openstack/tempest  705342f7dbe8c708fce8108ee4195e34635c588e
Revert "Fix of verify_glance_api_versions"

This reverts commit ff865d625cbb70e858034b06fa494cafc381cd49.

This commits broke at least Gnocchi's gate:

http://logs.openstack.org/97/370897/19/check/gate-gnocchi-dsvm-functional-file-mysql-ubuntu-xenial/6fa2852/logs/devstacklog.txt.gz#_2016-09-19_15_11_33_661

2016-09-19 15:11:30.999 | venv runtests: PYTHONHASHSEED='4186998819'
2016-09-19 15:11:30.999 | venv runtests: commands[0] | tempest verify-config -uro ../../../../tmp/tmp.YD2JoSxiWy
2016-09-19 15:11:33.659 | Traceback (most recent call last):
2016-09-19 15:11:33.660 |   File "/opt/stack/new/tempest/tempest/cmd/verify_tempest_config.py", line 425, in take_action
2016-09-19 15:11:33.660 |     main(parsed_args)
2016-09-19 15:11:33.660 |   File "/opt/stack/new/tempest/tempest/cmd/verify_tempest_config.py", line 403, in main
2016-09-19 15:11:33.660 |     verify_api_versions(os, service, update)
2016-09-19 15:11:33.660 |   File "/opt/stack/new/tempest/tempest/cmd/verify_tempest_config.py", line 165, in verify_api_versions
2016-09-19 15:11:33.660 |     verify[service](os, update)
2016-09-19 15:11:33.661 |   File "/opt/stack/new/tempest/tempest/cmd/verify_tempest_config.py", line 129, in verify_keystone_api_versions
2016-09-19 15:11:33.661 |     versions = _get_api_versions(os, 'keystone')
2016-09-19 15:11:33.661 |   File "/opt/stack/new/tempest/tempest/cmd/verify_tempest_config.py", line 99, in _get_api_versions
2016-09-19 15:11:33.661 |     'glance': os.image_client,
2016-09-19 15:11:33.661 | AttributeError: 'Manager' object has no attribute 'image_client'
2016-09-19 15:11:33.662 | Running config verification...
2016-09-19 15:11:33.712 | ERROR: InvocationError: '/opt/stack/new/tempest/.tox/venv/bin/tempest verify-config -uro ../../../../tmp/tmp.YD2JoSxiWy'

Change-Id: I2eba6c6721c5260c1a117dab9801da50a4b240e4