Updated openstack/openstack Project: openstack/oslo.db  7733f9604da91b466a3620335e4bdaa94cba0938
Fix test_migrations on Python 3

migrate.versioning.api.VerNum() conversion to integer doesn't work in
all cases. Cast explicitly to int in WalkVersionsMixin.walk_versions()
to fix this issue.

Modify unit tests to use VerNum objects instead of using directly
integers. The bug was not seen in tests because tests used int numbers.

Example of error:

    Traceback (most recent call last):
      ...
      File "oslo_db/sqlalchemy/test_migrations.py", line 189, in walk_versions
        versions = range(self.INIT_VERSION + 1, self.REPOSITORY.latest + 1)
    TypeError: 'VerNum' object cannot be interpreted as an integer

This bug impact for example glance.tests.unit.test_migrations of the
Glance project.

Change-Id: I043a66268b957b97f2e8f652c0ee8aec3a00e8dd