Updated openstack/openstack Project: openstack/os-net-config  3199064d4d5ce5a81fb38c831c11ab539ed8716a
Raise NotImplementedError instead of NotImplemented

NotImplementedError is the name of the exception
(https://docs.python.org/2/library/exceptions.html).
NotImplemented is the name of a constant
(https://docs.python.org/2/library/constants.html).
>>> raise NotImplemented()
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
>>> raise NotImplementedError()
Traceback (most recent call last):
  File "<pyshell#32>", line 1, in <module>
    raise NotImplementedError()
NotImplementedError
This patch fix it.

Change-Id: I8b8b47de26b9bf688d9d27a4daa6d9910994ac4a
Closes-Bug: #1339855