Update git submodules
* Update tripleo-ci from branch 'master'
  to 6528ebfb1e84a2e9fda08129ceedeb343172245b
  - Merge "Use virtualenv_command as ensure_pip_virtualenv_command"
  - Use virtualenv_command as ensure_pip_virtualenv_command
    
    In tripleo-ci, oooci-build-images[1] and build-containers[2]
    roles, virtualenv_python and virtualenv_command points to
    virtualenv-3.
    
    On EL9, pip module is throwing error:
    ```
    AttributeError: 'NoneType' object has no attribute 'version_tuple'
    ```
    
    Switching to ensure_pip_virtualenv_command var
    (comes from ensure_pip role) fixes the issue.
    
    Python3 is already available on CS7,8 & 9.
    It also removes the hacks related to python-virtualenv and its
    installation.
    
    Closes-Bug: #1953032
    Closes-Bug: #1745626
    
    Co-Authored-By: Marios Andreou (marios) <marios@redhat.com>
    Signed-off-by: Chandan Kumar (raukadah) <chkumar@redhat.com>
    Change-Id: I6de99ca4d6be46960b6061225e4a16c76edc8455