Update git submodules
* Update python-swiftclient from branch 'master'
  to 16f0034e67f16cb81912bcc6a0f7ac9823f32e1f
  - Switch from pkg_resources to importlib
    
    Seen on Arch Linux:
    
        ModuleNotFoundError: No module named 'pkg_resources'
    
    On new enough Python, we don't need it anyway.
    
    Change-Id: I3d46319a36a1c2477e9f7dae0c7e40a362a17639