Update git submodules
* Update rpm-packaging from branch 'master'
  - Merge "ironic: update requirements"
  - ironic: update requirements
    
    The testsuite started to require pysnmp for executing tests. without
    this change we have this failure:
    
      ironic/tests/unit/drivers/modules/irmc/test_inspect.py", line 21, in <module>
           from pysnmp.proto import rfc1902
      ModuleNotFoundError: No module named 'pysnmp.proto'; 'pysnmp' is not a package
    
    Change-Id: If961b3781bad7cabad5875966cebc18934148c45