Update git submodules
* Update openstacksdk from branch 'master'
  to 5e0c5334a33c9aa7b04de09c76dd65df8f91df13
  - Merge "config: Handle interface list in CloudRegion.get_all_version_data"
  - config: Handle interface list in CloudRegion.get_all_version_data
    
    If a connection is created via an oslo.config cfg.ConfigOpts object,
    then it's possible for interface to be a list of interfaces (due to
    valid_interfaces). We were not previously handling this, resulting in
    the following error:
    
      ❯ python -m cfg_test --config-file sample.conf
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "/dev/cfg-test/__main__.py", line 25, in <module>
          print(conn.config.get_all_version_data('placement'))
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
        File "/dev/openstacksdk/openstack/config/cloud_region.py", line 926, in get_all_version_data
          interface_versions = region_versions.get(interface, {})
      TypeError: unhashable type: 'list'
    
    Correct this by iterating through all interfaces until we find a
    non-null version information.
    
    Change-Id: I6e5e1b0f5357afa0462703eb18b9f2da340e90a4
    Signed-off-by: Stephen Finucane <stephenfin@redhat.com>