Updated openstack/openstack Project: openstack/keystone  e3dcc4f0730c076eea5f5b02a7016ead4f80f587 null Fix db_version failed with wrong arguments
The `keystone-manage db_version` command was failing with an error
like

 TypeError: db_version() takes exactly 2 arguments (1 given)

This is because an engine wasn't being passed to db_version().

Change-Id: I20b4cb10f9c83fc672de2838bac8236938b92e32
Closes-Bug: #1284341