Update git submodules
* Update cloudkitty from branch 'master'
  to d1c962a96fd8cc154461c49ddb9515185822d441
  - Merge "Remove remaining use of iteritems"
  - Remove remaining use of iteritems
    
    iteritems was removed in Python 3 and can no longer be used.
    
    >>> import collections
    >>> a = collections.OrderedDict()
    >>> a.iteritems()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'
    >>> a.items()
    odict_items([])
    
    Change-Id: I4e3d8b144e8ee06c323a8505835ae0a0bfc8e8c5