Update git submodules
* Update charm-cinder-backup-swift-proxy from branch 'master'
  to b2ed809e204da0596f06a5861186d4f99ff4cf6f
  - Fix s390x and pp64el builds
    
    Add build dependencies needed for s390x and pp64el
    
    ::   writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    ::   running build_ext
    ::   generating cffi module 'build/temp.linux-s390x-cpython-310/_padding.c'
    ::   creating build/temp.linux-s390x-cpython-310
    ::   generating cffi module 'build/temp.linux-s390x-cpython-310/_openssl.c'
    ::   building '_openssl' extension
    ::   creating build/temp.linux-s390x-cpython-310/build
    ::   creating build/temp.linux-s390x-cpython-310/build/temp.linux-s390x-cpython-310
    ::   s390x-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/buildd/cinder-backup-swift-proxy/build/parts/charm/build/.tox/build-reactive/include -I/usr/include/python3.10 -c build/temp.linux-s390x-cpython-310/_openssl.c -o build/temp.linux-s390x-cpython-310/build/temp.linux-s390x-cpython-310/_openssl.o -Wconversion -Wno-error=sign-conversion
    ::   build/temp.linux-s390x-cpython-310/_openssl.c:575:10: fatal error: openssl/opensslv.h: No such file or directory
    ::     575 | #include <openssl/opensslv.h>
    ::         |          ^~~~~~~~~~~~~~~~~~~~
    ::   compilation terminated.
    
    Change-Id: Ie5860020ba7a7197371275ba1bba6e983f44efb2