Update git submodules
* Update python-octaviaclient from branch 'master'
  to 86f788adf2fd397f1da1d8802cc2587036b972a0
  - Merge "Bump requirement for osc-lib"
  - Bump requirement for osc-lib
    
    python-octaviaclient unit tests now require osc-lib>=4.3.0.
    
    That fixes issues in the tests when using older osc-lib releases:
    
      AttributeError: 'FakeClientManager' object has no attribute 'sdk_connection'
    
    4.3.0 introduces a few deprecations that will be fixed in a follow-up
    commit
    
    Change-Id: I3a48ea49c3e6d5a8e59effcbf67f1fc90382d065
    Signed-off-by: Gregory Thiemonge <gthiemon@redhat.com>