Update git submodules
* Update bashate from branch 'master'
  - Update sphinx version
    
    This commit updates sphinx version which aligns to g-r. Without this
    patch, py27 tests fail because of an error like this:
    
     ERROR: Sphinx requires Python '>=3.5' but the running Python is 2.7.15
    
    Change-Id: Iaaf4b2dabd04f85217cb4a1af9af79165e5b1ba9
    
  - OpenDev Migration Patch
    
    This commit was bulk generated and pushed by the OpenDev sysadmins
    as a part of the Git hosting and code review systems migration
    detailed in these mailing list posts:
    
    http://lists.openstack.org/pipermail/openstack-discuss/2019-March/003603.html
    http://lists.openstack.org/pipermail/openstack-discuss/2019-April/004920.html
    
    Attempts have been made to correct repository namespaces and
    hostnames based on simple pattern matching, but it's possible some
    were updated incorrectly or missed entirely. Please reach out to us
    via the contact information listed at https://opendev.org/ with any
    questions you may have.