Update git submodules
* Update puppet-nova from branch 'master'
  to 14a1cc5a61ca73e2e8092ad696cfd3a383c27d6f
  - Remove usage of deleted manifest_dir
    
    Recent update in rspec-puppet removed some of the config interfaces for
    old puppet versions[1]. This drops usage of these interfaces to resolve
    the following error in unit tests.
    
    ```
    An error occurred while loading ./spec/unit/provider/manila_spec.rb.
    Failure/Error: c.manifest_dir = File.join(fixture_path, 'manifests')
    
    NoMethodError:
      undefined method `manifest_dir='...
    ```
    
    This also removes explicit setting of mock module. The definition is
    no longer required since we bumped puppetlabs_spec_helper to v 5.0.0.
    
    [1] https://github.com/puppetlabs/rspec-puppet/commit/316d95923cdbab4daf980629cbded351dd61354c
    
    Change-Id: I0e133a13ff3b751ee5bf9f99495b82073f0c6971