Update git submodules
* Update releases from branch 'master'
  to e83bb1f69a4612941c0aec519452f3e6cf7c5cd4
  - Uncap jsonschema
    
    With the latest upper constraints updating generated patch [1] the
    openstack-tox-docs job started to fail, due to conflict:
    
    ERROR: Cannot install jsonschema<4.0.0 and >=3.2.0 because these
    package versions have conflicting dependencies.
    
    The conflict is caused by:
        The user requested jsonschema<4.0.0 and >=3.2.0
        The user requested (constraint) jsonschema===4.7.2
    
    This is because we have jsonschema<4.0.0 in our requirements.txt.
    By uncapping the constraint the docs job is passing.
    
    Date validation needed to be updated as well, because a deprecated
    usage of validator extending method was used in the code, which was
    removed [2] from jsonschema with the 4.0.0 release. This patch replaces
    that with adding a TYPE_CHECKER instead.
    
    With the new jsonschema constraint openstack-tox-py36 job does not pass
    anymore, but py36 is dropped from zed anyway. That job is pulled in by
    an old job template, which needs to be replaced to the new zed job
    templates, too.
    
    [1] I89576353371aa87d181610eb6242cbe961487af6
    [2] https://github.com/python-jsonschema/jsonschema/commit/d9f63840609176f0b7328f2088c3b2a4016526cd
    
    Closes-Bug: #1982757
    Change-Id: Ida6310dd822e587ce9c424a228fdff5192ba0476