Updated openstack/openstack Project: openstack/manila  584ddc414b1f2d6a7b71fa028b4d4e3ada0597bb
Fix undefined attribute in scenario test class

An attribute check is being performed: "if not self.image_ref"
but self.image_ref may not be defined at all, leading to the
following error. So, let's define it first so it can be properly
evaluated.

AttributeError: 'TestShareBasicOpsNFS' object
has no attribute 'image_ref'

TrivialFix

Change-Id: I0c454009b95c5cb0b6fc1304bb0cba1ff87c9fe9