Updated openstack/openstack Project: openstack/ironic  312313ee9caf067b9a272defdb64d6138117821e
Build docs with Python 2 for now

When Python 3.6 is used by default (the case for F26), the build fails:
TypeError: '<' not supported between instances of 'NoneType' and 'str'

It is reported as bug 1714025, let's use Python 2 until it's fixed.

Change-Id: I8c2ba5b587b2919a22ff1d0f078c511d90de0f91
Related-Bug: #1714025